### ISSUE TITLE
P2P - (SubTask)Create data-sharing strategy interface and implement Wifi-Direct as the default interface

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#1078]
- Wifi-direct will be the default data-sharing strategy

```java
interface DataSharingStrategy {

     void searchDevices(OnDeviceFound);

	  void connect(DeviceInfo);
	  
	  void disconnect(DeviceInfo);
	  
	  void send(DeviceInfo, SyncPayload);
	  
	  void receive(DeviceInfo, SyncPayload);
	  
	  void onErrorOccurred(Exception);
	  
	  void onConnectionFailed(Exception);
	  
	  void onPairingFailed(Exception);
	  
	  void onSendingFailed(Exception);

}

```

### Tasks

- [ ] Add the interface
- [ ] Implement this for Wifi-direct
- [ ] Implement a configuration for the strategy. This will require creating a singleton library class that is the source of all configurations for p2p

Target repository: p2p

This interface might not be complete and needs more work

**Comment by Rkareko** [comment]
LOE 2 - 3 FTE days
