### ISSUE TITLE
CQL Approach for FHIR Core

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#109]
[**CQL**](https://cql.hl7.org/) (Clinical Quality Language) is the HL7 standard for providing logic execution for decision support and clinical quality measures. CQL allows for a more modular, flexible, and robust expression of logic. It allows logic to be shared between measures and with clinical decision support. CQL provides the ability to express logic that is human-readable yet structured enough for processing a query electronically. The CQL standards are located on the HL7 Website: CQL [Specification](http://www.hl7.org/implement/standards/product_brief.cfm?product_id=400). CQL Examples can be found [here](http://build.fhir.org/ig/HL7/cql/examples.html)

Our initial goal is to design and implement a  CQL Library to demo the below functionality 
1. Generate a MeasureReport via $measure operation 
2. Load and execute a custom CQL library for decision logic
3. Transform a PlanDefinition to a CarePlan using $apply operation

**Main use cases to model** 
1. How to programmatically implement $apply operation i.e. Use the **$apply** to generate a CarePlan from a PlanDefinition
2. Generate a MeasureReport by running the **$evaluate-measure**  tracked here #202

**Related subtasks** 
- [ ] How to run $apply on Android #309
- [ ] How to run $measure-evaluate on Android #310
- [x] Integrate CQL Library demo app into FHIR core #177
- [ ] Patient CarePlan generation / $apply operation #100
- [x] Create a Plan Definition for the Covax App #101
- [ ] Create a PlanDefiniton for the CHW/ANC app -  #283

**Comment by MuhammadSalman-7214** [comment]
After reading the documentation of CQL, here are some questions that need an answer:

1. What will be the conditions to generate a CQL library for Care Plan / $Apply Operation?
2.  What will be the conditions to generate CQL for measure report?
3.  How will we sync it to server?
4.  Where will we write CQL library(CQL expressions that will be created based on our conditions)?
