### ISSUE TITLE
[Quest/eCBIS] Update the Family profile to display a Group resource

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#1201]
**Name of feature to enhance**
---
- Family representation

**Description of feature**
----

- We currently use the Head of family patient resource to represent a family
- We are moving this to use the [Group resource](https://www.hl7.org/fhir/group.html). 

**Describe the enhancement**
----
- [ ] Load the Group representing the [Family selected here](https://github.com/opensrp/fhircore/issues/1200).
- [ ] List out the Family members based on all the Patients referenced on the Group `member` attribute. 
     - [ ] Clicking on a Family Member row should redirect you to the [Individual Profile](https://github.com/opensrp/fhircore/issues/1202). 
     - [ ] A Group sample can be found [here](https://github.com/opensrp/fhircore/issues/1183)
- [ ] If a Patient is also referenced on the _`managingEntity`_ attribute of the group then should the `Family head` sub header/caption.
- [ ] Deceased and inactive family members should be listed out but their rows should be deactivated. 

**Depends on**  -- https://github.com/opensrp/fhircore/issues/1200 
- Can be done concurrently

**Comment by dubdabasoduba** [comment]
@ellykits How far are you with the Quest Configurability pieces? Can we use your branch for this?
