### ISSUE TITLE
Structure map authoring through XLS form

### ISSUE THREAD

**Issue by ekigamba** [opensrp/fhircore#1360]
### Purpose

- Make it easy to author StructureMaps for developers, PMs and users
- Make it faster
- Reduce mistakes
- Make it more intuitive. Provide better errors

### How to author a structure map using XLS

- A single QuestionnaireResponse maps to multiple resources
- Provide a template XLS structure map authoring form
- Run it through a CLI tool that generates the final QuestionnaireResponse that is going to be uploaded to the server
- Save these XLS forms in the current [OpenSRP fhir-resource repository](https://github.com/opensrp/fhir-resources)

### Functions of the CLI tool

- Convert XLS to structure map JSON
- Provide useful errors to users
- Validate the XLS
- Connect to the current validator tool to generate results when given a questionnaire response

### Tasks

- [ ] Design sample XLS file from the current structure maps
- [ ] Note down weaknesses and complexities that might not be covered by XLS 
- [ ] Request review
- [ ] Develop a beta version for use

**Comment by f-odhiambo** [comment]
@AnnieMungai @ageryck @Gental-Giant @samkanga. You can keep track of this as it may help in authoring of StructureMaps for the various app content to fulfil project workflows

**Comment by pld** [comment]
I'd like to consider using a format other than XLS Form. I think we are biased towards XLS Form because we have experience with it and we have built other tools that use it.

Maybe it is in fact the best option, but I want us to come up with a list of some other formats and look at the pros and cons of them as well before we make a decision.
