### ISSUE TITLE
[Reporting]  - Generating encounters from on the creation of groups (representing families) 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1364]
**Describe the Issue**

1. Generate an [Encounter](http://hl7.org/fhir/encounter.html) post creating a [Group](http://hl7.org/fhir/group.html) (representing families) in order to store the time when the Family was created 
2. We are interested in saving and querying the  - [Encounter.period](http://hl7.org/fhir/encounter-definitions.html#Encounter.period) for tracking when the registration event occurred for the Household among other details that will be stored in the Registration Encounter 

**Tasks**
1. Update the Family creation StructureMap to also create an encounter
2. Add a new data to extract 

            1. New group for a Family 
            2. New patients 
            4. An Encounter to record this event 

**Sample Group**
````
{
    "resourceType": "Group",
    "id": "4e3d671d-83f3-4439-985c-7c679f25fd4a",
    "meta": {
        "versionId": "2",
        "lastUpdated": "2022-04-29T18:04:38.885+00:00",
        "source": "#349ec6e940ec076d"
    },
    "identifier": [
        {
            "use": "official",
            "value": "123"
        },
        {
            "use": "secondary",
            "value": "b8794278-a7d0-4690-9979-7fb8511b52e3"
        }
    ],
    "active": true,
    "type": "person",
    "code": {
        "coding": [
            {
                "system": "https://www.snomed.org",
                "code": "35359004",
                "display": "Family"
            }
        ]
    },
    "name": "skyfall",
    "managingEntity": {
        "reference": "Organization/105"
    },
    "member": [
        {
            "entity": {
                "reference": "Patient/83ca19e1-123a-42c1-8a74-342a85c41f20"
            }
        }
    ]
}
````
**Sample Encounter**   - Updated SNOMED codes for various codable concepts 
````
{
    "resourceType": "Encounter",
    "id": "132802",
    "meta": {
        "versionId": "1",
        "lastUpdated": "2022-06-24T07:52:48.572+00:00"
    },
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\">Encounter with patient @example who is at home</div>"
    },
    "status": "finished",
    "class": {
        "system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
        "code": "HH",
        "display": "home health"
    },
    "type": [
        {
            "coding": [
                {
                    "system": "http://snomed.info/sct",
                    "code": "184048005",
                    "display": "Registration"
                }
            ]
        }
    ],
    "priority": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "17621005",
                "display": "Normal"
            }
        ]
    },
    "subject": {
        "reference": "Group/1122f50c-5499-4eaa-bd53-a5364371a2ba"
    },
    "participant": [
        {
            "individual": {
                "reference": "Practitioner/399"
            }
        }
    ],
    "period": {
        "start": "2015-01-17T16:00:00+10:00",
        "end": "2015-01-17T16:30:00+10:00"
    },
    "reasonCode": [
        {
            "text": "Family Regsitration Task"
        }
    ],
    "location": [
        {
            "location": {
                "reference": "#home",
                "display": "Client's home"
            },
            "status": "completed",
            "period": {
                "start": "2015-01-17T16:00:00+10:00",
                "end": "2015-01-17T16:30:00+10:00"
            }
        }
    ],
    "serviceProvider": {
        "reference": "Organization/105"
    }
}
````
**Acceptance Criteria** 
- [x] 1. Update new StructureMap
- [x] 2.Extract the following resources (Group, Patient(s), Encounter)
- [x] 3. Store the newly created resources (Group, Patient(s), Encounter) on the SQLite DB

Later this will facilitate the 
1. Sync newly created artefacts from SQLite DB before syncing to HAPI, then ship them to the  data warehouse
2. Test the creation of a new Indicator(s) from this

**Comment by maimoonak** [comment]
location not added

{"resourceType":"Group","id":"574eeb3f-f233-4f53-9427-f72b152fb8ba","meta":{"lastUpdated":"2022-07-07T17:03:45.770+05:00"},"identifier":[{"use":"official","value":"10010","period":{"start":"2022-07-07T17:03:45+05:00"}},{"use":"secondary","value":"c84e079f-c1f4-4b8e-9128-87b7ee24a3fc","period":{"start":"2022-07-07T17:03:45+05:00"}}],"active":true,"type":"person","code":{"coding":[{"system":"https://www.snomed.org","code":"35359004","display":"Family"}]},"name":"Eman","managingEntity":{"reference":"Organization/400"}}

{"resourceType":"Encounter","id":"263e8f5f-7ca1-4ed4-a529-74e19cee04a4","meta":{"lastUpdated":"2022-07-07T17:03:45.781+05:00"},"status":"finished","class":{"system":"http://terminology.hl7.org/CodeSystem/v3-ActCode","code":"HH"},"type":[{"coding":[{"system":"http://snomed.info/sct","code":"184048005","display":"Registration"}],"text":"Registration"}],"priority":{"coding":[{"system":"http://terminology.hl7.org/ValueSet/v3-ActPriority","code":"EL","display":"elective"}],"text":"elective"},"participant":[{"individual":{"reference":"Practitioner/130845"}}],"period":{"start":"2022-07-07T17:03:45+05:00","end":"2022-07-07T17:03:45+05:00"},"reasonCode":[{"text":"Family Registration Task"}],"serviceProvider":{"reference":"Organization/400"}}
