### ISSUE TITLE
[Quest/eCBIS] - Configure Quest app to view measure report for Indicator 2 - Pregnancy Count

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1391]
Reference Link: https://docs.google.com/spreadsheets/d/1Kfp0rRYlksrBoSIecAuovZ8Y3k8yH9mkmgHcpQbMtXI/edit#gid=446158820

Narrative
We need to get :
1. How many families are there 
2. Of the family members who are Female, of Reproductive Age and are pregnant

Each household or a family is represented using a group resource as outlined below 
```
{
  "resourceType": "Group",
  "id": "107759",
  "meta": {
    "versionId": "3",
    "lastUpdated": "2022-04-14T13:54:41.656+00:00",
    "source": "#2f77c0c4a5d11f1e"
  },
  "identifier": [ {
    "use": "official",
    "value": "7bb7fa82-59e4-4744-a6d2-96722afca23b"
  }, {
    "use": "secondary",
    "value": "656766"
  } ],
  "active": true,
  "type": "person",
  "code": {
    "coding": [ {
      "system": "https://www.snomed.org",
      "code": "35359004",
      "display": "Family"
    } ]
  },
  "name": "Kamwana Rao",
  "managingEntity": {
    "reference": "RelatedPerson/2e2c9d4e-b67f-4673-8e83-e3f576046296"
  },
  "member": [ {
    "entity": {
      "reference": "Patient/c535f2e6-a17a-4b2a-913e-30e8b42553d0",
      "display": "Rao Kamwana"
    },
    "inactive": false
  }, {
    "entity": {
      "reference": "Patient/d0612f01-01c3-467e-9fbc-4e6ebe8bf9e6",
      "display": "Magarita Rao"
    },
    "inactive": false
  } ]
}
```

**Narrative** 
1. Count of all Female Patients enrolled on the app in each household
3. Count of ANC Clients with active Pregnancies registered in the app, disaggregated by age and gender for each age group. 

this will be via All patients with Pregnancy conditions and SNOMED code `77386006` as shown below

```
    "code": {
        "coding": [
            {
                "system": "http://snomed.info/sct",
                "code": "77386006",
                "display": "Pregnancy"
            }
        ],
        "text": "Pregnancy"
    },
```
4.  Age disaggregation will be (15-49)

**Pre-requisite** 
1. #700 
2. Add a household registration encounter e.g http://hl7.org/fhir/encounter-example-home.json.html
3. #1233 
5. https://github.com/google/android-fhir/pull/1280

**Subtasks**
- [ ] 1. #1379 

**Acceptance Criteria** 
- [x] Create a measure for eCBIS Measure 2  -  Pregnancy Count
- [x] Add Measure Resource library to FHIR Core HAPI FHIR Server 
- [x] List the measure in the Quest Reporting module 
- [x] Trigger measure for Household Indicator filtered by Start and End date and for a given population using the Family group resource 
- [x] View the measure report for eCBIS Indcator 2

**Comment by pld** [comment]
OK, I think we need to update the narrative then, how this factors into the 2 indicators listed above is ambiguous.

> 1. Count of all Female Patients enrolled on the app in each Households

is this the overall count of female patients? or is this the count of households that include a female patient, or something else?

> 2. Count of ANC Clients with active Pregnancies registered in the app, disaggregated by age and gender for each age group.

do families not factor into this?

> 3. Age disaggregation will be (0-11, 1-5, 6-14, 15-49, 50+)

Is this a disaggregation of the age of the pregnant woman? If so, these ranges don't make sense, eg 1-5

**Comment by AnnieMungai** [comment]
@f-odhiambo
- In all the registered household members, need to know the number of females. Of all the females how many are of reproductive age i.e. 15-49yrs. Of these RA women, the number is pregnant. Only the women of reproductive age can be used to compute the number of pregnant women.

**Comment by pld** [comment]
It's still not clear how to calculate this, can you please list out each indicator we will need to show, and for each include an example of what the inputs would be and the formula to calculate it?

**Comment by maimoonak** [comment]
Done. Two PRs for fhir-resources and fhircore are following. (Condition extraction is under progress in other ticket by Fikri)

Household pregnancy by age group | Measure Report from Composition #1404 
Cucumber testing module | Household pregnancy measure [fhir-resources/94 ](https://github.com/opensrp/fhir-resources/pull/94)

<img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/176922589-66726563-7446-4ea9-8118-48be018e442e.png"/> <img width="200" height="400" src="https://user-images.githubusercontent.com/4829880/176922582-fe6c93b2-7efa-44c5-bacb-2c1e45f312cf.png"/>

**Comment by f-odhiambo** [comment]
Check on the Date filter 
We should focus the date on the numerator count of interest thus if I add 1st to 31st January I should only get all ANC Clients enrolled in January
