### ISSUE TITLE
[QA] - Quest eCBIS QA Checklist (Guide)

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1406]
Here is a checklist summary of the items to QA in Quest that can be used to raise Bug Fixes/Enhancement tickets for the Quest/eCBIS app variant 

App Config 
- [x] 1. The user should be able to load the Quest eCBIS variant by loading app config id `ecbis-saa`
- [x] 2. If app id is verified proceed to the app login page else toast appropriate error message 

Authentication 
Login 
- [x] 1. Add the correct credentials (config id : ecbis-saa, username:ecbis)
- [x] 2. User should either be authenticated and move to set a PIN for future logins or else toast appropriate error message 
- [x] 3. Is success proceed to sync app data, load sync progress bar, and then toast success message once done
- [x] 4. In the event of failure  toast the appropriate error message 
Logout 
- [x] 1. Prompt user to logout 
- [x] 2. Proceed to logout and go back to the app config page 

Navigation Drawer  - On click 
- [x] 1. Household register  -  Go to Household listing 
- [x] 2. ANC Clients -  Go to Household listing 
- [x] 3. Children  - Not implemented yet 
- [x] 4. Reports - Go to In-app reporting 
- [x] 5. Device to device sync - Initiate P2P Sync (We shall have a separate test workstream)
- [x] 6. Language - Switch from English to Swahili and vice versa for both Questionnaires, Lablal and Menus)
- [x] 7. Logout  - Should check if we have unsynced data (TBD)

Home Page 
- [x] 1. Show patient list view 
- [x] 2. Add Family button  - Load add family registration questionnaire 
- [x] 3. Search Family by name or ID

Family Registration 
- [x] 1. Ability to view enrolled families 
- [x] 2. Ability to view family profile  
- [ ] 3. Household Routine visit  - load questionnaire 
- [x] 4. Menu items - Family detail (Update details from here ), Change family head (Load Questionnaire to complete), Family Activity (Not Implemented), View Past Encounters (Not Implemented), Remove Family (Load Questionnaire to complete)
- [ ] 5. List Item actions  - Click on a task to initiate task workflow 

Family Member Registration 
- [x] 1. Add new family members (Load Questionnaire to complete)

Family Member Profile  
Menu Items 
- [x] 1. Individual details (Edit profile)
- [x] 2. View Family -> Got to a family profile page 
- [x] 3. Record as ANC  - Should be female of reproductive age (Add check)
- [x] 4. Remove person (Load Questionnaire to complete)

ANC Register 
- [x] 1. ANC Patient list 
- [x] 2. Search for ANC Client (Name, ID)
- [x] 3. View Patient profile 
- [x] 4. In the Menu items, remove Add as ANC
- [x] 5.  In the Menu items, remove person (Load Questionnaire to complete)

In-App Reporting 
- [x] 1. Household Count Measure  - Count the number of households disaggregated by Gender and Age 
- [x] 2. ANC Clients Count Measure  - Count the number of pregnant clients  disaggregated by Age 

_NB. A separate review will be done for the design to see of it conforms to the unified design language proposed and refreshed by the design team_

**Comment by f-odhiambo** [comment]
All the updated resources can be found here https://github.com/opensrp/fhir-resources/tree/main/ecbis

**Comment by NaveenZehra11** [comment]
ISSUE1:

APP Installation Failed:
Device : Android 6 , API 23 , Samsung S5

cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE2:

Summary : HouseHold Search BY ID

house hold search with Id not working.

**Comment by NaveenZehra11** [comment]
ISSUE4:

Summary :  MALE MEMBER OPTION FOR RECORD AS ANC

1-add member (Male)
2-View his profile
3-on option giving record as ANC client option 
![Screenshot_20220707-165611](https://user-images.githubusercontent.com/90256461/177768078-91d353fc-818c-42f7-85f8-e008a2a992e3.png)

**Comment by NaveenZehra11** [comment]
ISSUE 5:

Summary : app crashes on family member profile (indivdual Detail)

1-go to household member
2-click on options
3-click on individual detail
App chrashes.
![Screenshot_20220707-165611](https://user-images.githubusercontent.com/90256461/177769015-04677c10-ca19-4712-8f5a-a178b6b579ea.png)
cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE 6: 

Summary : on Report calendar week days are not in English language
1- login into application
2- from setting select language english
3-for setting go to Reports
4-open start and end date calendar
5-the name of weeks are not in english 

![Screenshot_20220713-124020](https://user-images.githubusercontent.com/90256461/178679564-b39ec25f-f414-4c56-bb3c-8098e463364e.png)
 
cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE 7:

Summary : No Report Generating

1-login into application
2-go to setting
3-go to reporting
4- generate any report

Actual : No Report Generating

cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
**ISSUE 8:**

Summary : ANC Client search With ID not working
1-login into application
2-go to setting
3-go to ANC patient list
4-on search option searched the anc patient with ID
 
Actual : no Result Found
![Screenshot_20220713-125050](https://user-images.githubusercontent.com/90256461/178680893-ccd465f1-6f94-437c-b914-effcda27483e.png)


cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE 11:

Summary : Validation Error on delete family

![Screenshot_20220714-150249](https://user-images.githubusercontent.com/90256461/178957847-7d833b5a-953f-4122-a623-a00dc00c85ab.png)


cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE 12:

Summary :  on Remove Family Questionair : Age of death unknown should before age of death

Actual : age of death then Age of death unknown
Expected: Age of death unknown (if user select no) then age of death is mandtaory to fill

![Screenshot_20220714-151833](https://user-images.githubusercontent.com/90256461/178960981-32cd2f5b-b910-42bc-92bc-438d56a522a8.png)


cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE 13:

Summary : on Add Member quetionair : DOB can not be future date

1- login
2-go to any family
3-add member
4-add DOB ( from future)
actual : successfully added
Expected : DOB cant be future date

![Screenshot_20220714-152303](https://user-images.githubusercontent.com/90256461/178963444-10e5efe9-ff8a-4e79-88d6-215d5b76f717.png)


cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
ISSUE 15

Summary : Add Member DOB is unknown select : list of family disappear

1-login
2-go to family
3- add member
4- select DOB is unknown
5-save
Blocker:
![Screenshot_20220714-152606](https://user-images.githubusercontent.com/90256461/178963704-a555f33a-9929-4fc4-989d-5f7bd9c4c38c.png)



cc @f-odhiambo

**Comment by NaveenZehra11** [comment]
Add Family :
ISSUE 1:
===================
Actual:  user enter the text A
Expected:according to Reference sheet Village should be a drop down and user select one from
drop down
https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=519889948
ISSUE 2:
==============
Actual : houseHold id has no limit i can enter 234,34577,3455
Expected : household id must be 4 digits
https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=519889948
ISSUE 3:
============
Actual : user can create family with existing household id
Expected: the household id should not be duplicated on the same user
ISSUE 4:
=============
Routine visit is not clickable
ADD MEMBER:
ISSUE1:
========
Actual :  open srp id is taken by user
Expected : should be prepopulated
ISSUE2:
Actual :  user can input the future DOB as well
Expected :  future date selection should be disable
ISSUE3:
========
Actual : not given error which field is required and user not filled it at saving form time
Expected: should be * on mandatory field and when user click on save if field is not filled error show in red color below the specific field

cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
**REMOVE FAMILY MEMBER**

**ISSUE 1:**

Select  death
App crash while entering the age 



**CHILD ADDED:**

**ISSUE1:**

Multiple child visit form created on profile of child and at the tiem of child routine visit not enable it is enable after some time

cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
while i m running the build from main with tag [v0.1.1-ecbis-rc](https://github.com/opensrp/fhircore/tree/v0.1.1-ecbis-rc)
i m getting Error on Emulator
2022-08-03 18:31:11.839 3704-3704/org.smartregister.fhircore.quest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.smartregister.fhircore.quest, PID: 3704
    java.lang.RuntimeException: Unable to resume activity {org.smartregister.fhircore.quest/org.smartregister.fhircore.quest.ui.main.AppMainActivity}: java.util.NoSuchElementException: Key navigation is missing in the map.
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.util.NoSuchElementException: Key navigation is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
        at org.smartregister.fhircore.quest.ui.main.AppMainViewModel$navigationConfiguration$2.invoke(AppMainViewModel.kt:253)
        at org.smartregister.fhircore.quest.ui.main.AppMainViewModel$navigationConfiguration$2.invoke(AppMainViewModel.kt:93)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.smartregister.fhircore.quest.ui.main.AppMainViewModel.getNavigationConfiguration(AppMainViewModel.kt:93)
        at org.smartregister.fhircore.quest.ui.main.AppMainViewModel.retrieveAppMainUiState(AppMainViewModel.kt:105)
        at org.smartregister.fhircore.quest.ui.main.AppMainActivity.onResume(AppMainActivity.kt:67)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8129)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by NaveenZehra11** [comment]
While login with Physical Device

2022-09-02 17:58:59.385 19102-19102/org.smartregister.fhircore.quest E/LoginViewModel$response: java.io.IOException: Network call failed with Response{protocol=h2, code=400, message=, url=https://keycloak-stage.smartregister.org/auth/realms/FHIR_Android/protocol/openid-connect/userinfo}
        at org.smartregister.fhircore.engine.ui.login.LoginViewModel$responseBodyHandler$1.handleResponse(LoginViewModel.kt:88)
        at org.smartregister.fhircore.engine.data.remote.shared.ResponseCallback.onResponse(ResponseCallback.kt:30)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$retrofit2-DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:89)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1$$ExternalSyntheticLambda1.run(D8$$SyntheticClass)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by NaveenZehra11** [comment]
**ISSUE : APP Crash on Change family head**

1- open any family 
2- click on change family head (from side menu option)
   APP CRASHES
   
cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
**ISSUE : HouseHold Searching**
 1- 1- open house hold list
 2- search by name household => example **Naveen**
 3- open naveen Family
 4- click Back
 5- now you are on household list screen => on search **Naveen** is already written 
 6- just click enter now "**Naveen** is not searching

<img src="https://user-images.githubusercontent.com/90256461/183707530-25c9c3a3-c01a-4011-b54c-ff427cf7f336.png" width="200" height="400" />

cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
**ISSUE : Child count not correct**
1- add child in any family
2-open side menu
showing children as 0

<img src="https://user-images.githubusercontent.com/90256461/183708394-e3e19984-88e8-4ee1-a300-36057fc96a40.png" width="200" height="400" />

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc

cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
**ISSUE : Child Registered Age**
On routine Visit Of child  questionnaire taking age in year as  child age is already input once the child is registered. So the user can enter a different age as compared with the registered child age.
**registered child age**
<img src="https://user-images.githubusercontent.com/90256461/183988462-1ce1835f-e295-4429-81ad-e1c96259ae99.png" width="200" height="400" />
**age input from routine Visit Of child  questionnaire**
<img src="https://user-images.githubusercontent.com/90256461/183988802-68703b93-3660-439f-9ba5-81bad4a23656.png
" width="200" height="400" />

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc

cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
**ISSUE : Child Registered Age**
On routine Visit Of child  questionnaire taking age in year as  child age is already input once the child is registered. So the user can enter a different age as compared with the registered child age.
**registered child age**
<img src="https://user-images.githubusercontent.com/90256461/183988462-1ce1835f-e295-4429-81ad-e1c96259ae99.png" width="200" height="400" />
**age input from routine Visit Of child  questionnaire**
<img src="https://user-images.githubusercontent.com/90256461/183988802-68703b93-3660-439f-9ba5-81bad4a23656.png" width="200" height="400" />

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc

cc @f-odhiambo @AnnieMungai 
With unknown DOB - age as null and from option its give the option as record sick child
Even i have add the as 30 in add member questionnaire

**Comment by NaveenZehra11** [comment]
**ISSUE** : Unknown DOB consider as Child 

1- add member
2-select unknown DOB
3-add age as 30 
4-save

Actual: when open the member profile age and sex showing as null and from left side option showing the record as sick child option
<img src="https://user-images.githubusercontent.com/90256461/183990030-5883891c-5c9a-4654-b848-3b488020ab96.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/90256461/183990057-9942cd39-d100-4fe9-ba67-5ed307bbf34e.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/90256461/183990077-de84e938-a869-428a-97fe-d3382f684093.png" width="200" height="400" />

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc
cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
ISSUE: SYNCING For DOB as unknown

whose date is unknown and enter the age in add member questionnaire , once sync  the members are removed from the household Family.

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc
cc @f-odhiambo @AnnieMungai

**Comment by NaveenZehra11** [comment]
Issue: Incorrect HouseHold Count

1- on menu showing 17 hosuseHold Count
<img src="https://user-images.githubusercontent.com/90256461/184620594-03b8e761-ce41-4959-b1c2-8caa3f28dd38.png" width="200" height="400" />


2- actual count is 15
<img src="https://user-images.githubusercontent.com/90256461/184620627-9d0573ed-1cfe-45e2-821b-caab00a1ca01.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/90256461/184620628-6dfa3865-da7e-4785-986f-fe1919f74f6d.png" width="200" height="400" />
<img src="https://user-images.githubusercontent.com/90256461/184620631-b740bd5a-f81d-4aeb-a3d4-a2b13b4f4a38.png" width="200" height="400" />

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE :  Members counts not changing according to Date in Reports**
 1- generate any report by selecting any date range  i.e total count 50
 2- than add member member today and sync 
3- generate report the count increase by +1 on date range end date today i.e total count 51
4-but if i select the date range end date yesterday than count should be -1 i.e 50 but still its showing 51

Thats means the date is not reflect any changes on report

**Comment by AnnieMungai** [comment]
> Issue: Incorrect HouseHold Count
> 
> 1- on menu showing 17 hosuseHold Count <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/184620594-03b8e761-ce41-4959-b1c2-8caa3f28dd38.png">
> 
> 2- actual count is 15 <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/184620627-9d0573ed-1cfe-45e2-821b-caab00a1ca01.png"> <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/184620628-6dfa3865-da7e-4785-986f-fe1919f74f6d.png"> <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/184620631-b740bd5a-f81d-4aeb-a3d4-a2b13b4f4a38.png">
> 
> App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba

Is this happening in all registers?

**Comment by NaveenZehra11** [comment]
**ISSUE:** 
**PNC task not trigger immediately after filling pregnancy outcome form**

1-add Female member in any family
2- Record her as ANC client
3-go to profile and fill form for pregnancy outcome
4-Refresh not working 

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE**
**PNC , new born form should be equal to number of children in form**

1- 1-add Female member in any family
2- Record her as ANC client
3-go to profile and fill form for pregnancy outcome live birth and children = 2
showing only 1 new born form on anc client profile
<img src="https://user-images.githubusercontent.com/90256461/185990829-49dfbd8b-5aef-4eac-a12c-1aae64a2dbe8.png" width="200" height="400" />

Family : Biden Family

App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
ISSUE : showing option to mark pregnancy outcome for already mark ANC client for pregnancy outcome

1-go to any anc client 
2-from options select pregnancy outcome 
Actual : still showing it is as anc client also showing it to mark as pregnancy outcome again

<img src="https://user-images.githubusercontent.com/90256461/186236476-5a9957ae-4f92-40e5-8161-a22c1c25eb2d.png" width="200" height="400" />
App Detail: https://github.com/opensrp/fhircore/releases/tag/v0.1.0-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE: logout is not working**

on app click on logout from ecbis is not working

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE: see all form not working thats why new Form can not see on profile**


<img src="https://user-images.githubusercontent.com/90256461/187429171-b739a87a-fe68-47a9-9054-87464d746117.png" width="200" height="400" />

<img src="https://user-images.githubusercontent.com/90256461/187429181-68973038-a012-48f9-9ede-39e9ea28bf4b.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
ISSUE : when ANC client mark as pregnant women all anc Task shpuld be removed or disbaled


<img src="https://user-images.githubusercontent.com/90256461/187430409-f2e91d77-8d3a-4f62-8455-0f4a37c5906a.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
ISSUE : PNC followup task not overdue at end of day

steps:
marks women as pregnant date :  30 aug


<img src="https://user-images.githubusercontent.com/90256461/187433172-3e75ac8d-b75b-49d2-ac62-36f3a35c2a52.png" width="200" height="400" />

change date from mobile to 30 aug


<img src="https://user-images.githubusercontent.com/90256461/187432203-bdd53908-63d5-4099-911f-8976055e2f3f.png" width="200" height="400" />

According to https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=1757872948
Overdue at end of day

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE : 2nd PNC followup task creating at 4th day for normal weight**

Steps:
mark women pregnant outcome with normal weight : 30 aug
change date from Mobile to 1 sept [from my under standing 1sept is 3rd day]
**According to https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=1757872948
Normal Weight 1,3,7 day**
but still new followup not created
change date to 2nd sept [from my understanding 2 sept is 4th day]
New followup task created Even the last one is not overdue (overdue bug already reported)

<img src="https://user-images.githubusercontent.com/90256461/187435351-48db4141-d3ec-4bc0-a850-0098b6f64cad.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
ISSUE : after {dob} + 28 days not able to mark the client again as ANC 

Steps: 
marks anc client as pregrnant outcome
after 28 days all form disable 
but not able to mark the client as anc again
<img src="https://user-images.githubusercontent.com/90256461/187437184-abb3087a-828b-4e96-be52-bc06c4e09b10.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE : 2nd PNC followup task creating at 2nd day for under weight**

Steps:
mark women pregnant outcome with normal weight : 30 aug
change date from Mobile to 31 aug [from my under standing 31aug is 2nd day]
**According to https://docs.google.com/spreadsheets/d/1zi1ELaSCebXfNjMsu9ODAxKeAODy_8LLpPuVqqysa4E/edit#gid=1757872948
Normal Weight 1,2,3,7,14 day**
but still new followup not created
change date to 1 sept [from my understanding 1 sept is 3rd
New followup task created Even the last one is not overdue (overdue bug already reported)

<img src="https://user-images.githubusercontent.com/90256461/187438522-22e6e5f7-cf7f-4423-9e17-1a90f78bcd66.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba

**Comment by NaveenZehra11** [comment]
**ISSUE : Family Planning showing to the age < 15 women** 

<img src="Screenshot from 2022-09-07 11-56-31](https://user-images.githubusercontent.com/90256461/188861582-86e4ec63-0ddd-4f38-934f-9f9c1b4da12d.png" width="200" height="400" />

app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
**ISSUE : showing the add to family option to anc client** 


<img src="https://user-images.githubusercontent.com/90256461/188865125-00cdd6d4-4709-4b87-b8dd-472ec867b05d.png" width="200" height="400" />

ticket: https://github.com/opensrp/fhircore/issues/1601
app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE: family planning option is not showing to male 15 < age >=49 age 

<img src="https://user-images.githubusercontent.com/90256461/188870332-213c0677-066d-4c08-82ac-812fb124ab94.png" width="200" height="400" />

ticket: https://github.com/opensrp/fhir-resources/issues/49
app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
> ISSUE: family planning option is not showing to male 15 < age >=49 age
> 
> <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/188870332-213c0677-066d-4c08-82ac-812fb124ab94.png">
> 
> ticket: [opensrp/fhir-resources#49](https://github.com/opensrp/fhir-resources/issues/49) app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

issue Resolved 
app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
> **ISSUE : showing the add to family planning option to anc client**
> 
> <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/188865125-00cdd6d4-4709-4b87-b8dd-472ec867b05d.png">
> 
> ticket: #1601 app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

issue Resolved
app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
> **ISSUE : Family Planning showing to the age < 15 women**
> 
> <img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/188861582-86e4ec63-0ddd-4f38-934f-9f9c1b4da12d.png">
> 
> app Detail : https://github.com/opensrp/fhircore/releases/tag/v0.1.2-ecbis-rc cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

issue Resolved
app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Not showing the add to family option again for case {{already using family planning = YES}} and {{FP Method = Absistance }}

Actual  : no FP start but also not showing the add to family option again
Expected : no FP start also show the add to family option 

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis 
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Not showing the add to family option again for case {{already using family planning = YES}} and {{FP Method = Withdrawl }}

Actual : no FP start but also not showing the add to family option again
Expected : no FP start also show the add to family option

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
SSUE : Not showing the add to family option again for case {already using family Planning = NO} and {interested instarting FP = NO}
 
ISSUE : Not showing the add to family option again for case {{already using family planning = YES}} and {{FP Method = Withdrawl }}

Actual : no FP start but also not showing the add to family option again
Expected : no FP start also show the add to family option

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Not showing the add to family option again for case {already using family Planning = NO} and {interested in starting FP = YES} and {is Women Pregnant = YES} and {refered to facilty = YES} 

Actual : 2 refferal forms created also not showing the add to family option again
Expected : 1 referal task created and also show the add to family option

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Not showing the add to family option again for case {already using family Planning = NO} and {interested in starting FP = YES} and {is Women Pregnant = YES} and {refered to facilty = NO}

Actual : no FP start, no referal task create  but also not showing the add to family option again
Expected : no FP start also show the add to family option again

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Not showing the add to family option again for case **{already using family Planning = NO} and {interested in starting FP = YES} and  {is Women Pregnant = NO} and all{period_7days , birth_6weeks,abstained,miscourage_7days,birth_6month=NO}**

Actual : no FP start, no referal task create but also not showing the add to family option again
Expected : no FP start also show the add to family option again

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Not showing the add to family option again for case  **{already using family Planning = NO} and {interested in starting FP = YES} and  {is Women Pregnant = NO} and {period_7day =YES} and {{method_client_interested =NONE}**

Actual : no FP start, no referal task create but also not showing the add to family option again
Expected : no FP start also show the add to family option again

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer

**Comment by NaveenZehra11** [comment]
ISSUE : Invalid workflow for case **{{already using family Planning = NO} and {interested in starting FP = YES} and {is Women Pregnant = NO} and {period_7day =YES} and {{method_client_interested = IUD} and {reffred_to_facilty=YES}**
<img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/190127998-8d38c198-c347-4c06-87ed-3b03f439d306.png">

Actual : FP start,  referal task create 
<img alt="" width="200" height="400" src="https://user-images.githubusercontent.com/90256461/190128036-6b2ef6ce-688b-4b86-bbe7-aa98eda3a7e5.png">

**Expected : no FP start, create refferal task  also show the add to family option again**

app Deatial https://github.com/opensrp/fhircore/releases/tag/v0.1.3-ecbis-rc
configid = ecbis
preview apk
cc @f-odhiambo @AnnieMungai @dubdabasoduba @aurangzaibumer
