### ISSUE TITLE
[Quest/Geo Widget] - Add Geo-widget to FHIR Core 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1536]
**Epic**
Add a POC to demo, FHIR Core reference app developed, tested, and QA to support loading, displaying, and interacting with the widget.

**Subtasks** 
- [x] #1537 for Digital Health  Applications
- [x] Update to AndroidX, Gradle version and plugin updates (Kukjaku)- https://github.com/onaio/kujaku/pull/357 

**Content only subtasks**
- [x] #1538
- [x] #1539
- [x] #1558
- [x] Demonstration of GeoWidget features, with demo content for viewing geo-data on a map and stored  in FHIR Location & Group(Household) resource 
- [x] QA viewing and creation of new structures on a map

**Comment by pld** [comment]
^ added a note on what of this is content only
