### ISSUE TITLE
[QA] - Quest eCBIS Supply Chain Release v0.0.1 QA Checklist (Guide)

### ISSUE THREAD

**Issue by roywanyaga** [opensrp/fhircore#1556]
QA checklist for the initial eCBIS Supply Chain Release. 
Note: This is a separate apk from the eCBIS apk but moving forward the supply chain functionality will be merged into the eCBIS apk

**App Config**
- [x] The user should be able to load the eCBIS Supply Chain application variant by loading app config id `ecbis_sc`
- [ ] If app id is verified proceed to the app login page else toast the appropriate error message

**User Authentication**

Login
- [x]  1. Add the correct credentials (app id : `ecbis_sc`, username: `ecbis_sc`)
- [x]  2. User should either be authenticated and move to set a PIN for future logins or else toast appropriate error message
- [x]  3. If success proceed to sync app data, load sync progress bar and then toast success message once done
- [x]  4. In the event of failure toast the appropriate error message

Logout
- [x]  1. Prompt user to logout
- [x]  2. Proceed to log out and go back to the app config page

**Navigation Drawer**
- [x] Record Stock Button - Launches the Physical Inventory Count and Stock Supply Questionnaire

Registers
- [x] All Households - Launches the households register if data is available
- [x] ANC - Launches the ANC register if data is available
- [ ] Stock Inventory - Launches the commodity register if data is available

Static Menu
- [x] Transfer Data - Launches the P2P screens
- [x] Profile - Launches the settings page

Sync
- [x] Sync Button initiates online data sync and text displays the last sync time

**Physical Inventory Count and Stock Supply Questionnaire**
Based on the [data dictionary](https://docs.google.com/spreadsheets/d/10LeXwSLvbAaMe9dk9A-LSUD4upUiolKkPYuYkF2cHbk/edit?usp=sharing)

**Commodity Register**
- [ ] Based on the provided list of commodities
- [ ] Artemether 20mg + Lumefatrine 120mg (1x6) tabs
- [ ] Artemether 20mg + Lumefatrine 120mg (2x6) tabs
- [ ] Amoxicillin 250mg tabs
- [ ] Female Condom
- [ ] Albendazole 400mg tabs
- [ ] MUAC Strap
- [ ] MNP
- [ ] AS (25mg)   +   AQ (67.5mg)   ( 2-11months) tablets
- [ ] AS (50mg)   +   AQ (135mg)	( 1-5years) tablets
- [ ] Male Condoms
- [ ] Microgynon
- [ ] Microlut
- [ ] Rapid Diagnostic Test (RDT)
- [ ] Sayana Press
- [ ] Artesunate 100mg Suppository
- [ ] Oral Rehydration Salt 20.5g/L
- [ ] Paracetamol 100mg tabs
- [ ] Zinc sulfate 20mg tabs
- [ ] dispensing bags for tabs s
- [ ] Disposable Gloves
- [ ] Dispensing Envelopes
- [ ] Examination/Nitrile Gloves (S)
- [ ] Examination Gloves (Nitrile) Medium
- [ ] Examination/Nitrile Gloves (L)
- [ ] Face Shield (Flexible, Disposable)
- [ ] Goggles
- [ ] Face Mask, Surgical
- [ ] PPE Suit - Coverall, M
- [ ] PPE Suit - Coverall, L
- [ ] Hand sanitizer gel 250ml w/ pump
- [ ] Safety boxes , Box

**Stock Level Adjustment Questionnaire**

- [ ] On clicking an item on the commodity register the Stock Level Adjustment Questionnaire should launch
- [ ] Questionnaire based on the [data dictionary](https://docs.google.com/spreadsheets/d/1NT0-fOnUCzzbj_cahmXZv8bEXF__VWLCRRC9GNXhlms/edit?usp=sharing)

**Comment by charlene-570** [comment]
QA results :User Authentication

**Login** -Pass
Test steps:
- Download the App
- Enter correct credentials i.e app id : ecbis_sc, username: ecbis_sc
      **Actual Results** :
User can successfully Login see screen cast attached


https://user-images.githubusercontent.com/85434942/185629736-65f69ced-1f2a-43a8-8c1f-754e04858928.mp

**Record Stock Button** -Bug
Test Steps:
-Login successfully
-Click on R**ECORD  RESTOCK**
-Fill the fields 
-Click Save

**Actual Results**
1.User is unable to fill in some field
2.Save fails with a  dialog "*Submit details please confirm that you have all details filled before submission**
3.After the above dialog this dialog this message is displayed **Validation Failed**
See screen cast attached

https://user-images.githubusercontent.com/85434942/185631205-712cb5af-79a6-438e-9e3d-ddced74975dc.mp4



**Sync Functionality** -Bug
Test steps:
1.Login the App
2.Click on Sync on the side menu

**Actual Results**
1.The timestamp is on syncing is wrong

See screenshot attached


https://user-images.githubusercontent.com/85434942/185631596-6f45d5c2-3e5d-4f44-a6a4-acf1057aa9e3.mp4

**Comment by charlene-570** [comment]
@AnnieMungai 
Bug Description- Stock inventory module : User cannot enter Enter Balance data and App crashes after user clicks on the Save Button

Steps to reproduce:

1.login the App
2.Click on the Stock Inventory under menu
3.Click on any inventory data
4.Enter Usable stock on hand field
5.Click on save

See Screen cast attached

https://user-images.githubusercontent.com/85434942/187919622-e5504ed7-0170-4a5f-941d-9b75806692b6.mp4

**Comment by charlene-570** [comment]
@AnnieMungai 

Bug Description - User is unable to click on the Households list

Steps to reproduce:
1.Login the App
2.Click on All Households under the menu
3.Click on any household data

Actual results:
-Clicking on the household data and or member is unresponsive

See screen cast attached

https://user-images.githubusercontent.com/85434942/187922030-3422eb82-aa22-4d93-998d-b3cc86b96fe3.mp4

**Comment by charlene-570** [comment]
@AnnieMungai   
Error during App configuration on Android version 8
see screenshot attached 
![Screenshot_20220914-223856_MOH eCBIS](https://user-images.githubusercontent.com/85434942/190329782-100c6e97-e817-45c7-96cd-59723e7fb3c1.jpg)
