### ISSUE TITLE
[Roadmap] Notice D - mADX : Objective 1.1: Verify that Open Source Java Libraries can run efficiently on Android

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#168]
- [x] Activity 1.1.1: Identify the core FHIR resources that are required for implementing FHIR on Aggregate Data Exchange (ADX) in the Android client. #204
- [ ] Activity 1.1.2: Build FHIR Measure and MeasureReport resources in Android building on the Android FHIR SDK. #205
- [ ]  Activity 1.1.3: Test, enhance and run the CQL Engine on the Android FHIR SDK. #206

**Comment by pld** [comment]
Can we please change the title to include what the objective is?
