### ISSUE TITLE
[Roadmap] Notice D - mADX : Objective 1.2: Develop and test an end-to-end prototype for a RMNCH workflow

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#169]
- [x] Activity 1.2.1.1: Develop a sync mechanism of FHIR MeasureReport from Android to the HMIS #207
- [x] Activity 1.2.1.2 Demonstrate that measureReports could independently sync from the Android client to the FHIR server #208
- [ ] Activity 1.2.2: Develop an end-to-end reference application that supports generating an RMNCH MeasureReport on the Android SDK and pushing that report to the HMIS #209
  - [ ] Activity 1.2.2.1 Provide PATH with link to the source code #210
  - [ ] Activity 1.2.2.2 Demonstration of the MeasureReport generation and user interface in the Android client #211
  - [x] Activity 1.2.2.3 Demonstration that the MeasureReport is pushed from the Android client to the FHIR server #212

**Comment by pld** [comment]
Can we please change the title to include what the objective is?
