### ISSUE TITLE
[Roadmap] Notice D - mADX : Objective 1.3: Integrate the mobile Aggregate Data Exchange (mADX) on Android feature with OpenSRP

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#170]
- [x] Activity 1.3.1.1: Integrate these libraries with the OpenSRP Android client #213 
- [ ] Activity 1.3.1.2: Demonstration of the feature, and documentation on how we accomplished this task #214 
- [x] Activity 1.3.1.3 Provide PATH with link to the source code #215

**Comment by pld** [comment]
Can we please change the title to include what the objective is?
