### ISSUE TITLE
[Roadmap] Notice E0 - Shelf Readiness: Work package 1 : Adding an automated testing framework and improving modular test coverage to 80% 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#171]
- [x] Automated test framework across the platform and link to GitHub code #233
- [x] Selection of Test framework - documented #234 
- [x] Testing Plan documented covering what will be tested (Android client, data warehouse, and server libraries) #235 
- [x] Gherkin test cases (or similar definition of tests) - documented/hosted [require test definitions] #236 
- [x] Code test cases that are operational on the test harness. #237 
- [x] Link to the code/test cases. #238 
- [x] Demonstration of the working test framework. #239 
- [x] #807
