### ISSUE TITLE
[Roadmap] Notice E0 - Shelf Readiness: Work package 2a - OpenSRP FHIR API

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#172]
- [x] OpenSRP FHIR API (FHIR v4, planning to use HAPI to achieve this) #245 
- [x] Add documentation for the Design and Implementation on Github #246 
- [x] API endpoints that expose FHIR compliant pattern Locations, Organizations, Practitioners, and Practitioner Roles #247 
- [ ] Valid test cases showing the ability to consume and produce valid messages (including tests of the negative cases) #248
