### ISSUE TITLE
[Roadmap] Notice E0 - Shelf Readiness: Work package 2b - FHIR API supporting specific resources

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#173]
- [ ] Build and demonstrate that the HAPI FHIR server can support Healthcare Service, Operation Outcome, and Bundle by being a consumer of mCSD profile #249 
- [ ] Add documentation for the Design and Implementation on Github. #250 
- [x] API endpoints that expose FHIR compliant pattern Healthcare Service, Operation Outcome, and Bundle #251 
- [ ] Interfaces that allow OpenSRP to be a consumer of the mCSD profile and functionality that show this being used within the workflow of the application. #252 
- [ ] Valid test cases showing the ability to consume and produce valid messages (including tests of the negative cases) #253
