### ISSUE TITLE
[Roadmap] Notice E0 - Shelf Readiness: Work package 2c - Demonstration of integration with Instant OpenHIE

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#174]
- [ ] Demonstration of integration with Instant OpenHIE and installation as part of Instant OpenHIE #254 
- [ ] Demonstrate the system can contribute and consume data into Instant OpenHIE. #255 
- [ ] OpenSRP DevOps aligned to be deployed alongside Instant OpenHIE. #256 
- [ ] Project Blog post published on the website and/or on Digital Square website #257
