### ISSUE TITLE
[UX] Register view enhancement | Round 1

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#1969]
**Describe the enhancement**

|  <img width="383" alt="image" src="https://user-images.githubusercontent.com/4540684/213169894-34478e54-7566-48eb-89e1-585a687b4852.png">   | <img width="311" alt="image" src="https://user-images.githubusercontent.com/4540684/213411822-ec99181b-4039-47f6-be40-dc9adcf6ae0b.png">    |

**Implementation**
- [ ] Fix the tasks buttons display. Right now the tasks buttons are cut off in both registers.  
    - [ ] Update the UI to show the correct character count for the buttons that show tasks. 
    - [x] Update the UI to show the correct button size for the task buttons.
    - [x] Update all the button properties to match the designs
- [x] Update the UI to show the correct character count for the labels.
- [ ] Update the UI to show the correct character count for the names.

@HenryRae and @ellykits to lead the review of designs and character counts on the three elements.

**Comment by mberg** [comment]
We also really need to figure out a strategy to improving the usability of the tasks.  Right now you can't read what they say.  We probably need to allow them to be a bit wider. We may want to consider dropping the + and shortening the descriptions to reduce the length of the task labels.

**Comment by dubdabasoduba** [comment]
After this round of updates then we can move to https://github.com/opensrp/fhircore/issues/2040

**Comment by HenryRae** [comment]
**On the family profile: (360px screen width)**
<img width="445" alt="Screenshot 2023-02-13 at 16 54 54" src="https://user-images.githubusercontent.com/31955469/218476487-5ca9a84b-8bf7-4cc3-83fa-a8d310cf5fcf.png">
1. Patients with long names should allow the text box to move to 2 lines max. The text/copy can be truncated with ellipses in case it's more than the available text length.
2. Long task names should be truncated too in case they can't fit the available text box width. However, task names used should be as short as possible and clear i.e use concise and precise keywords for call-to-action text or buttons. The idea is to keep it short but meaningful. cc: @AnnieMungai @f-odhiambo 


**For larger screens 400px width:**
<img width="483" alt="Screenshot 2023-02-13 at 17 00 33" src="https://user-images.githubusercontent.com/31955469/218477679-67ca87da-dba1-427e-8a42-1cfd7897271d.png">
1. the patient names container can be fixed, and 
2. the task button container set to fill the available space
3. and the label fits the available space with 8px padding left and right

**Task buttons guide:**
Button guides and rules:
1. To ensure task buttons remain functional, we recommend the button label to be limited to approximately 12 - 16 characters. If the required label exceeds 12 or 16 characters, it may still be used(but will be truncated), but it may be worth evaluating the copy.
2. Use concise and precise keywords for call-to-action text or buttons. The idea is to keep it short but meaningful


[Link to page with the specs](https://www.figma.com/file/gDW2MxoHNI77hv1O49xgAk/FHIR-Apps-~-Design-System?node-id=18853%3A124502&t=kX8SkvW6s6CvXpXB-1)

**Comment by HenryRae** [comment]
<img width="202" alt="Screenshot 2023-02-13 at 17 18 38" src="https://user-images.githubusercontent.com/31955469/218482631-146cc21a-7652-4c23-ad1e-01d0968e6b8a.png">
Most button names(99%) should be able to fit if the proposed properties in design are implemented.

**Comment by rowo** [comment]
@dubdabasoduba @AnnieMungai related to the above, here is a spreadsheet with potential button/task label names (column E, highlighted means it is long): https://docs.google.com/spreadsheets/d/1lT2M9I55RtTdxsp9iBDSHbcmsKZJRj2L3Zcj8WP-4jY/edit#gid=0. We can work together to finalize. The two items I'm not sure about are: (1) if it's possible to modify labels, and (2) what is the final list of tasks we have? Is the spreadsheet complete or maybe it needs to be updated because of how we're handling immunizations now.
