### ISSUE TITLE
Closing/Revoking CarePlans and associated Tasks using configured PlanDefinitions

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2168]
**Describe the feature request.**
Extend the current event handling system to handle configuring a Questionnaire to close a CarePlan and all the CarePlan's associated Tasks when the Questionnaire is submitted.

**Implementation plan (For Engineers)**
- [ ] Create a `CarePlanConfig` data class that has the following fields
- Conditional FHIRPath expression
- ~CarePlan operation - An enum with the values `close` and `complete`~
- [ ] Update the [QuestionnaireConfig](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/QuestionnaireConfig.kt) to have a new field that holds a list of `CarePlanConfig` objects
- [ ] Create a function that 
- Takes QuestionnaireConfig as a parameter
- Iterates through the list of PlanDefinitions. For each PlanDefinition 
   - Fetch the corresponding CarePlan. Example can be found [here](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt#L95-L98)
   - Evaluate the conditional FHIRPath expression found in the CarePlan config. The resource to use for this is referenced in the `QuestionnaireResponse.subject` field
   - If the FHIRPath expression evaluates to false then terminate execution at this point
   - If the FHIRPath expression evaluates to true then continue to the steps outlined below
       - Update CarePlan status to ~`revoked`~ `completed`
       - Fetch all Tasks linked to the CarePlan. Use the `CarePlan.activity.outcomeReference`
       - Then update all the linked Tasks to `cancelled` that are not 'complete'
- [ ] invoke the function in the [extractCarePlan](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/questionnaire/QuestionnaireViewModel.kt#L337-L360) function after the `fhirCarePlanGenerator.generateOrUpdateCarePlan` call

**Acceptance criteria**
The following are examples of workflows that would trigger closing of a CarePlan and associated Tasks
- [ ] An ANC patient will have a pregnancy outcome form. When this form is submitted with a pregnancy outcome of any type the ANC CarePlan and Tasks should be canceled since the patient will move to a different workflow with a different CarePlan.
- [ ] If a patient/family is removed through the family or patient removal forms then all the CarePlans and Tasks for the patient/family should be marked as canceled.
- [ ] All child-related CarePlans should be closed if the patient's Age is updated to more than 5yrs.  Current Child CarePlans are Immunization, Child Routine Visit and Sick Child

**Comment by qiarie** [comment]
@f-odhiambo @dubdabasoduba How should cancelled tasks be displayed on the profile? Currently they appear as active and clickable after cancellation.

![Screenshot_1679579190](https://user-images.githubusercontent.com/696759/227223487-84c4f880-cd84-4323-9670-f91649f3878d.png)

**Comment by pld** [comment]
> @f-odhiambo @dubdabasoduba How should cancelled tasks be displayed on the profile? Currently they appear as active and clickable after cancellation.
> 
> ![Screenshot_1679579190](https://user-images.githubusercontent.com/696759/227223487-84c4f880-cd84-4323-9670-f91649f3878d.png)

@rowo @HenryRae any thoughts from your perspective on this?

**Comment by pld** [comment]
> @f-odhiambo @dubdabasoduba How should cancelled tasks be displayed on the profile? Currently they appear as active and clickable after cancellation.
> 
> ![Screenshot_1679579190](https://user-images.githubusercontent.com/696759/227223487-84c4f880-cd84-4323-9670-f91649f3878d.png)

@rowo @HenryRae any thoughts from your perspective on this?

**Comment by f-odhiambo** [comment]
Here is a narrative of Task colour coding https://github.com/opensrp/fhircore/discussions/1557 
<img width="839" alt="Screenshot 2023-03-24 at 10 41 23 AM" src="https://user-images.githubusercontent.com/4540684/227456329-a043e6e5-fe25-45e5-afa3-c53543827bc7.png">

**Comment by f-odhiambo** [comment]
Here is another sample 

<img src="https://user-images.githubusercontent.com/4817531/222687440-039ee696-1b6f-4c2d-998a-97082871710b.png" width="400">

**Comment by pld** [comment]
Cool looks good, we can change the icon/coloring in follow-up

**Comment by pld** [comment]
give what we now know about the usage of "revoked" we should probably always set this to complete, see https://github.com/opensrp/fhircore/issues/2169#issuecomment-1479468679

**Comment by pld** [comment]
also given that, I don't think we need the CarePlanOperation enum, since the won't vary the outcome based on that value

**Comment by qiarie** [comment]
@f-odhiambo It's still not clear how cancel should be represented

**Comment by HenryRae** [comment]
> Here is a narrative of Task colour coding #1557 <img alt="Screenshot 2023-03-24 at 10 41 23 AM" width="839" src="https://user-images.githubusercontent.com/4540684/227456329-a043e6e5-fe25-45e5-afa3-c53543827bc7.png">
> 
> Here is another sample, though yes cancelled & expired are not provided in the current mocks/workflows
> 
> <img alt="" width="400" src="https://user-images.githubusercontent.com/4817531/222687440-039ee696-1b6f-4c2d-998a-97082871710b.png">

@f-odhiambo @pld @qiarie 
canceled tasks shouldn't show on the profile, same goes for expired tasks. This is because they are no-longer actionable, however in the past encounters, CHA should be able to view which tasks got expired or cancelled.
cc: @rowo correct me if am wrong here

Example below of past encounters, I think we use stalled for cancelled but not 100% sure. 
Question: Why and how would a task get cancelled?
<img width="351" alt="Screenshot 2023-03-30 at 11 25 37" src="https://user-images.githubusercontent.com/31955469/228776072-fd10b317-8d85-4254-a9a6-b213c5a02ac8.png">
