### ISSUE TITLE
Complete or cancel Careplans depending on status of linked Tasks

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2169]
**Describe the feature request.**
There are 2 scenarios affecting update of careplan status that are not handled in the current implementation. These are
1. Completing a careplan when all associated tasks are completed before they expired (are past there `executionperiod.end`)
2. Closing a careplan when all associated tasks are cancelled before they expired (are past there `executionperiod.end`)

**Acceptance criteria**
@f-odhiambo assist with this

**Area path**
@f-odhiambo assist with this

**Implementation plan (For Engineers)**
- [ ] Create a new CoroutineWorker name `FhirCarePlanWorker` that will handle both completion and closing careplans depending on the status of associated tasks
- [ ] Fetch all the careplans. For each do the following
  - Fetch all the associated tasks. 
  - Iterate through the tasks
  - If all the tasks have a status of `completed` then update the careplan status to `completed`
  - If all the tasks have a status of `cancelled` then update the careplan status to `revoked`
- [ ] Schedule the `FhirCarePlanWorker` to run periodically. This is done [here](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainViewModel.kt#L293-L313)

**Comment by pld** [comment]
Some questions

1. What happens if all the Tasks for a CarePlan are expired?
2. In step (2) of the implementation, can we add conditions to the fetch of CarePlans to reduce what we fetch? Would it be possible to join on Tasks and only fetch CarePlans that have any Tasks that are completed or cancelled? More generally, how can we push more of this operation to the db layer to improve performance, any ideas on that?
3. What happens when all of the Tasks for a CarePlan are a mix of cancelled and completed, is that CarePlan marked `completed` or `revoked`?

**Comment by Rkareko** [comment]
> What happens if all the Tasks for a CarePlan are expired?

The current implementation updates the CarePlan status to 'completed' when the last task for the CarePlan has expired

**Comment by Rkareko** [comment]
> In step (2) of the implementation, can we add conditions to the fetch of CarePlans to reduce what we fetch? Would it be possible to join on Tasks and only fetch CarePlans that have any Tasks that are completed or cancelled? More generally, how can we push more of this operation to the db layer to improve performance, any ideas on that?

One of the things we can do is filter care plans by `status` i.e only fetch careplans that are not `revoked | completed`  i.e those with the following values `draft | active | on-hold | entered-in-error | unknown`

**Comment by Rkareko** [comment]
> What happens when all of the Tasks for a CarePlan are a mix of cancelled and completed, is that CarePlan marked completed or revoked?

@f-odhiambo @dubdabasoduba This is has not been handled as part of this ticket. What are your thoughts on this?

**Comment by f-odhiambo** [comment]
Initial thought on this I think this may be a business requirement/edge case and also depends on the type of Task and how critical it is for continuity of care for example if this is a household task we may decide to close the Task but in the event of let's say HIV tracking this becomes an entry point to LTFU (Loss to Follow Up) where perhaps closing the plan may not be appropriate. To revisit later

**Comment by Rkareko** [comment]
@maimoonak in the current fhircore implementation is there any functionality that completes a careplan when all the associated tasks have been completed? cc @f-odhiambo @dubdabasoduba

**Comment by dubdabasoduba** [comment]
@Rkareko @f-odhiambo 

- A CarePlan should not be left with `status` == `active` if all the tasks tied to it are of `status` == `completed` or `cancelled` 
    - A CarePlan with all its tasks marked as `status` == `completed` or `cancelled` should have `status` == `Completed` or `revoked`. The following rules should apply to achieve the said CarePlan status
        - If all the tasks have a `status` == `completed` then update the CarePlan `status` to `completed`
        - If any of the tasks have a `status` == `cancelled` then update the CarePlan `status` to `Revoked`

cc: @pld

**Comment by pld** [comment]
Is there FHIR documentation to back that up or is it a convention we're defining?

**Comment by dubdabasoduba** [comment]
@pld this is inferred from the definition of the CarePlan statuses. https://www.hl7.org/fhir/valueset-request-status.html

![Screenshot 2023-03-21 at 10 15 42](https://user-images.githubusercontent.com/4817531/226576743-643d64f1-b1b1-4037-8f57-b827d2f1b2d6.png)

**Comment by maimoonak** [comment]
> @maimoonak in the current fhircore implementation is there any functionality that completes a careplan when all the associated tasks have been completed? cc @f-odhiambo @dubdabasoduba
@Rkareko Yes. Here is an example android/engine/src/test/resources/plans/anc-visit/plandefinition.json . Check line 195, and 134

**Comment by f-odhiambo** [comment]
> @pld @Rkareko We asked the same question on the Implementors call and the feedback was interesting.
> 
> **Revoked** -- This Is to be used for authorization purposes. e.g you created a CarePlan coz you thought the client had insurance but later find out they don't. So you revoke the CarePlan based on that. **Entered in Error** -- This is to be used in cases where the CarePlan was created by mistake. e.g you added the wrong client to ANC and want to revert that. This might be useful when we introduce tasks and form submission editing. **Completed** -- Used when the CarePlan is no longer active either because the actions are complete or something happened to close it. e.g a patient died.
> 
> Based on this I am tempted to say we use completed for everything but I am not sure what you guys think.
> 
> cc: @f-odhiambo

I concur

**Comment by pld** [comment]
I guess I also, somewhat reluctantly, concur.

Big pro is this will definitely simplify the code, so yay @Rkareko.

Con, which is a future problem, is we might want to create metrics around whether a CarePlan was "completed" and what completed means from a health systems perspective, probably something close to all the related tasks are completed does NOT sound the same as what "completed" means from a billing perspective.

Also, the comments about this being used for insurance don't sound like they're prescriptive. @dubdabasoduba was it like this is how we've used, or was it more, this how you/in general it SHOULD be used?

Looking at the code system, there's nothing here that's related to insurance, it seems more generic, but the word "revoked" does definitely sound billing/insurance related, https://www.hl7.org/fhir/codesystem-request-status.html.

**Comment by dubdabasoduba** [comment]
@pld it was more of this is how it should be used.  The insurance use case was an example of where you would have to revoke authorization.  

The revoking is more around restricting access or the ability to perform the CarePlan.

**Comment by Rkareko** [comment]
@dubdabasoduba @f-odhiambo  since @maimoonak confirmed that there is another operation that completes Careplans when related tasks are completed is it accurate to say that the remaining piece to be handled by this ticket is to complete Careplans when
1. All the tasks are `cancelled`
2. All tasks are a mix of  `completed` or `cancelled`
