### ISSUE TITLE
CHW/ANC SubTask - Profile view

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#217]
User story : 
As a CHW, I want to view a patient's profile so that I can be able to view their bio-data and history

Acceptance criteria : 
- [ ] On the landing page, you can view a list of card that contain patient biodata such as name, address, telephone number 
- [ ] The patient profile  can be extracted from [patient](https://www.hl7.org/fhir/patient-example.json.html)  & [observation](https://www.hl7.org/fhir/observation-example-f001-glucose.json.html) history FHIR  resources 
- [ ] Allow for scroll view if details do not fit in the field of view

For ANC
- [ ] Ability to show registered patients and their enrollment and referral status. Eg. referred for ANC service to HVP Gatagara in Nyanza.  Ability to click on the patient to view and edit information on the patient (eg. contact information) and referrals made.

4.5 days FTE + 20% buffer

**Comment by f-odhiambo** [comment]
Same as #286
