### ISSUE TITLE
Invalidation/refresh cache after form completion

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2234]
**Describe the feature request.**
Since we currently cache the registers and profiles data we need to refresh/invalidate the cache every time a patient or family is removed from the app.

For the family register we need to filter out `inactive` families. The [Filter out inactive families using custom search parameters](https://github.com/opensrp/fhircore/issues/2233) addresses this.

**Acceptance criteria**
- [ ] When a family is removed, it should not appear on the household register
- [ ] When a patient is removed, it should not appear on the patient register

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Navigate to HouseHold register
2. Click on one family
3. Click on `Remove Family` on the household profile overflow menu
4. Fill out and save the `Remove Family` questionnaire
5. Navigate back to the `HouseHold` register
6. The removed family should not appear on the register

**Implementation plan (For Engineers)**
- [ ] Add a `refreshContent` boolean that determines whether the register cache should be invalidated
- [ ] Add a `dataRefreshLivedata` boolean live data object in `AppMainViewModel`
- [ ] Check whether `questionnaireConfig.refreshContent` is true in `AppMainActivity.onSubmitQuestionnaire`. If true post a value of true using `dataRefreshLivedata`
- [ ] Observer `dataRefreshLivedata` in `RegisterFragment.onViewCreated`
- [ ] When `dataRefreshLivedata` is updated to `true` invoke `registerViewModel.retrieveRegisterUiState` with a `clearCache` value of `true`
- [ ] Reset the `dataRefreshLivedata` value to false
