### ISSUE TITLE
Implement LastSyncTimeStamp update Per Resource in FHIR Core

### ISSUE THREAD

**Issue by allan-on** [opensrp/fhircore#2254]
### Context 

The migration to the latest Engine version among other changes introduces a [TimestampContext Interface](https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt#L131) that allows saving and getting the `LastUpdatedTimestamp` per resource in the `ResourceParamsBasedDownloadWorkManager`. 

This is a breaking change on FHIR Core and the implementation of the TimeStampContext would need to be supplied to the FHIR Core [AppSyncWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/sync/AppSyncWorker.kt#L44)

Currently, on FHIR Core, we update the `LAST_SYNC_TIMESTAMP` in the SharedPreference on sync finished/complete and not per resource

This SharedPreference value is also used to show the last sync date+time on the Navigation Drawer

#### Implementation plan

- [ ] Update the SDC version to the latest published artefact on Sonatype
- [ ] Update the Engine version to the latest published artefact on Sonatype
- [ ] Implement the `TimeStampContext` interface methods and inject this with `HILT` in the AppSyncWorker class
   - [ ] Use SharedPref to store the Resource type as the key and the timestamp as the value
   - [ ] Implementation for getLastUpdatedTimestamp will retrieve the timestamp value from the SharedPreference using the Resource type as the key
- [ ] Add relevant Tests for the implementation i.e for the save and get `lastUpdated` timestamp implementations
- [ ] Update the last sync timestamp on the nav drawer using the SyncJob completion timestamp
