### ISSUE TITLE
Refactor cache invalidation after form completion to use generis event bus

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2273]
**Describe the feature request.**
A generic event bus implementation has been added as part of ticket #2265.
The purposed of this ticket is to refactor the current implementation that handles invalidation of cache after form completion to use the generic event bus.

**Acceptance criteria**

- [ ] When a family is removed, it should not appear on the household register
- [ ]  When a patient is removed, it should not appear on the patient register

**Area path**

1. Navigate to HouseHold register
2. Click on one family
3. Click on Remove Family on the household profile overflow menu
4. Fill out and save the Remove Family questionnaire
5. Navigate back to the HouseHold register
6. The removed family should not appear on the register

**Implementation plan (For Engineers)**

- [ ]  Add a `QuestionnaireSubmission` event in the `Appevent` class
- [ ]  Check whether `questionnaireConfig.refreshContent` is true in `AppMainActivity.onSubmitQuestionnaire`. Trigger a `QuestionnaireSubmission` event using the event bus.
- [ ]  Subcribe to the `event` SharedFlow provided by the EventBus and filter events of type `RefreshCache` in RegisterFragment.onViewCreated
- [ ]  When the `RefreshCache` event is received invoke registerViewModel.retrieveRegisterUiState with a clearCache value of true

**Comment by Rkareko** [comment]
Following discussions with @ellykits @f-odhiambo, we saw the need for refactoring [AppMainActivity.onSubmitQuestionnaire](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt) into 2 events instead of the existing livedata components which are `questionnaireSubmissionLiveData` and `dataRefreshLivedata`.
This tickets handles the refactor for `dataRefreshLivedata`.

**Comment by Rkareko** [comment]
One of the use-cases for event management as outlined in the [event management discussion](https://github.com/opensrp/fhircore/discussions/1953) is `Redirecting to different screens`.  An example of this would be redirecting the user to the family register after a family has been removed. The current implementation redirects the user to the household profile.

@ellykits @dubdabasoduba it would be prudent to have a discussion about the different use cases that would need to be handled in addition to how configurability would be approached

**Comment by Rkareko** [comment]
> Following discussions with @ellykits @f-odhiambo, we saw the need for refactoring [AppMainActivity.onSubmitQuestionnaire](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/main/AppMainActivity.kt) into 2 events instead of the existing livedata components which are `questionnaireSubmissionLiveData` and `dataRefreshLivedata`. This tickets handles the refactor for `dataRefreshLivedata`.
> 
> A ticket for the `questionnaireSubmissionLiveData` refactor will be added [here](https://github.com/opensrp/fhircore/issues/2290)

The ticket for the `questionnaireSubmissionLiveData` refactor has been added here
