### ISSUE TITLE
Refactor handling of questionnaire submission to use generic event bus

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2290]
**Describe the feature request.**
A generic event bus implementation has been added as part of the ticket https://github.com/opensrp/fhircore/issues/2265.
The purpose of this ticket is to refactor the current implementation that handles questionnaire submission to use the generic event bus.

**Acceptance criteria**

- [ ]  When a family is added, it should appear on the household register
- [ ]  When a patient is added, they should appear on the patient register

**Area path**

- [ ] Navigate to the side menu
- [ ] Click on `ADD HOUSEHOLD`
- [ ] Fill out and save the `Add Household` form
- [ ] App should automatically navigate to the `All households` register
- [ ] The newly added family should appear on the register

**Implementation plan (For Engineers)**
- [ ]  Create a new `OnSubmitQuestionnaire` event in the Appevent class to take a `QuestionnaireSubmission` param
- [ ]  Confirm that `questionnaireConfig` and `questionnaireResponse` values are not null in AppMainActivity.onSubmitQuestionnaire function. Trigger a OnSubmitQuestionnaire event using the event bus.
- [ ]  Subscribe to the event SharedFlow provided by the EventBus and filter events of type OnSubmitQuestionnaire in `RegisterFragment.onViewCreated` and `ProfileFragment.onViewCreated`
- [ ]  When the OnSubmitQuestionnaire event is received do the following in the `RegisterFragment`
    1. Refresh data
    2. Retrieve the app's main UI state
    3. Display snackbar message
- [ ]  When the OnSubmitQuestionnaire event is received do the following in the `ProfileFragment`
    1. Refresh data
    2. Display snackbar message

**Comment by Rkareko** [comment]
A few issues to discuss with @ellykits concerning the implementation plan

1. Do we use the same event i.e `RefreshCache` to handle both `questionnaireSubmissionLiveData` and `dataRefreshLivedata`
2. If so how do we distinguish between the 2 events

**Comment by Rkareko** [comment]
> A few issues to discuss with @ellykits concerning the implementation plan
> 
> 1. Do we use the same event i.e `RefreshCache` to handle both `questionnaireSubmissionLiveData` and `dataRefreshLivedata`
> 2. If so how do we distinguish between the 2 events

Implementation plan has been updated
