### ISSUE TITLE
[In-App Reporting] Add configuration to enable loading of specific reports in the background

### ISSUE THREAD

**Issue by roywanyaga** [opensrp/fhircore#2307]
**Describe the feature request.**
Update measure report configuration to allow loading of specific reports in the background. 
The configuration will include:

- [ ] An indication of whether the report is to be loaded in the background
- [ ] ISO Period indicating the frequency of the background job

Research to ensure that the Measure report is generated in the background without affecting users

**Additional context**
An implementation to load all in-app reports in the background had been done but disabled because it was affecting performance and application use;
As CQL evaluation is being reviewed to enhance performance this will be an initial solution to enable loading of specific reports in the background

**Acceptance criteria**

- [ ] User update a specific measure report config to enable loading in the background
- [ ] Measure report is generated in the background without affecting users
- [ ] ~Whenever a background task is running show a message in the UI so the user knows the reason if the UX lags~
    - should this be a non-dismissable toast?
    - should this show for all background tasks regardless, or only ones that are configured to run on a schedule?

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
@roywanyaga marking this as blocked, before we work on configuration we need to verify that we can get background tasks running acceptably well for user interaction at all. It's also not obvious this is the type of functionality that should be user configurable (or at least at this level of detail).

**Comment by f-odhiambo** [comment]
@roywanyaga Will be working on this as the performance issues are being worked on in parallel. Removing `blocked` label for now 

CC @pld

**Comment by pld** [comment]
@roywanyaga can you please make a PR with this code going into main, https://github.com/opensrp/fhircore/pull/2515/files

**Comment by pld** [comment]
I guess we're not doing the toasts for now, that's ok, we can do that in response if we see perf problems
