### ISSUE TITLE
Enhancements to Closing CarePlans based on form submission

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2308]
**Describe the feature request.**
Closing of CarePlans and associated Tasks using configured PlanDefinitions scoped [here](https://github.com/opensrp/fhircore/issues/2168) is limited to only running fhirpath expressions against a single resource.
There is a need to extend this funcitonality to handle running fhirpath expressions against resources contained inside the bundle generated when a questionnaire is submitted.

Examples of such a fhirpath expressions are

-  [Checking whether a sick child has fully recovered](https://github.com/opensrp/fhir-resources/blob/325123dd61029db03c4534aa0595c9725aa29e49/ecbis_liberia/plan_definition/sick_child_follow_up_visit.json#L137)     
`"%resource.entry.where(resource is QuestionnaireResponse).resource.where(questionnaire = 'Questionnaire/3276f55c-b25e-455b-ae4e-8846fb8fd039').exists() and %resource.entry.where(resource is QuestionnaireResponse).resource.repeat(item).where(linkId = '0e2d8659-22ee-44ca-8c26-bf81cca6b366' and answer.value.code = 'fully-recovered').exists()"`
- [Checking whether an FP visit form has been submitted](https://github.com/opensrp/fhir-resources/blob/325123dd61029db03c4534aa0595c9725aa29e49/ecbis_liberia/plan_definition/fp_routine_visit.json#L278) 
`"$this is Patient and %resource.entry.where(resource is QuestionnaireResponse).resource.where(questionnaire = 'Questionnaire/450cb100-0c5b-47c6-9f33-2830a79be726').exists()"`

**Acceptance criteria**
- [ ] Should be possible to close multiple CarePlans and linked Tasks at once. 
- [ ] We should be able to close CarePlans based on FHIR path expressions.  

**Area path**
@dubdabasoduba see this

**Implementation plan (For Engineers)**

- [ ] Update [FhirCarePlanGenerator.conditionallyUpdateCarePlanStatus](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt#L326) function to take in a bundle as a param
- [ ] Update the method to run fhirpath expressions against the bundle
- [ ] Remove `fhirPathResource` and `fhirPathResourceId` form the [CarePlanConfig](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/CarePlanConfig.kt#L34-L35) and refactor affected logic

**Comment by Rkareko** [comment]
Questions @dubdabasoduba @owais-vd 

1. How do we decide when to run the fhirpath expression against the `QuestionnaireResponse.subject` versus the `bundle`
2. Are all resources needed for running the fhirpath expressions present in the bundle. If true seems we may not need [`fhirPathResource` and `fhirPathResourceId` ](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/CarePlanConfig.kt#L34-L35)in the careplanconfig

**Comment by Rkareko** [comment]
> Questions @dubdabasoduba @owais-vd
> 
> 1. How do we decide when to run the fhirpath expression against the `QuestionnaireResponse.subject` versus the `bundle`.
>    We could introduce a boolean (`evaluateBundle`)  in the `carePlanConfig`
> 2. Are all resources needed for running the fhirpath expressions present in the bundle. If true seems we may not need [`fhirPathResource` and `fhirPathResourceId` ](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/domain/model/CarePlanConfig.kt#L34-L35)in the careplanconfig

Following discussions with @owais-vd it appears that all fhirpath expressions are run against either the `subject` or the `bundle`. Removing `fhirPathResource` and `fhirPathResourceId`  appears to be the way forward
