### ISSUE TITLE
Run Background task workers in batches

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2329]
**Describe the feature request.**
Background tasks worker such as [FhirTaskPlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt), [FhirTaskExpireWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorker.kt) and [FhirCompleteCarePlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCompleteCarePlanWorker.kt) operate by fetching and apply a filter to all tasks from the app db. With the with the growth of number of tasks this process slows down the performance of the app.

One of the ways to improve the app performance would be to run the background workers against a smaller batch (e.g 1000) at a time.

**Acceptance criteria**
A check list of all things to verify once the implementation by the engineer is complete

**Implementation plan (For Engineers)**

- [x] Add keys in [SharedPreferenceKey](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/util/SharedPreferenceKey.kt) that keeps track of the last offset for a particular worker e.g `FHIR_TASK_PLAN_WORKER_LAST_OFFSET`
- [x] Update the fhirEngine search logic for fetching tasks in the worker to have an `count` (1000) and a `from` (last offset + 1)
- [x] Investigate whether the [secondary filter](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt#L64-L71) on the list of returned tasks is still required since [Old and outdated resource indexes still present in the database](https://github.com/google/android-fhir/issues/1825) issue has been fixed
