### ISSUE TITLE
[Event Management] Closing CarePlans and Related resources configuration update

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2371]
**Describe the feature request.**
- Update the event management closing of CarePlans and Tasks functionality to close other related resources. 

**Additional context**
- When closing the CarePlan e.g. Sick Child we have a couple of other resources that need to be closed too.  The current functionality will only close a CarePlan and its related Tasks. 
- An example of another related resource would be the Condition that's open for the child when a sick child CarePlan is assigned to them. 

**High-Level Implementation Plan**
- [ ] Add a config named`eventWorkflows` that will be used for all event management configurations. 
- [ ] These configs will hold to the following configs
    - [ ] The event type is represented by an ENUM class on code.  
    - [ ] The condition that needs to be satisfied for the event to run. This should allow rules execution. 
    - [ ] The PlanDefinition that triggers the workflow to be closed. 
    - [ ] The resources that will need to be closed/deactivated after the condition is fulfilled. 

**Configuration Sample**
```json
{
  "eventWorkflows": [
    {
      "eventType": "EventType",
      "condition": [],
      "PlanDefinition": [],
      "fhirResource": {
        "relatedResources": [
          {
            "resource": "Condition",
            "searchParameter": "subject",
            "attributesToUpdate": [
              {
                "attribute": "status",
                "value": "in-active"
              }
            ],
            "relatedResources": []
          },
          {
            "resource": "Appointment",
            "searchParameter": "subject",
            "attributesToUpdate": [
              {
                "attribute": "status",
                "value": "cancelled"
              }
            ],
            "dataQueries": [
              {
                "paramName": "appointment-type",
                "filterCriteria": [
                  {
                    "dataType": "CODING",
                    "value": {
                      "system": "https://www.snomed.org",
                      "code": "35359004"
                    }
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
```

**Acceptance criteria**
- [ ] All defined resources should be closed on CarePlan closure.  

**Implementation plan (For Engineers)**

- [ ] Create data models to handle the config json referenced [here](https://github.com/opensrp/fhircore/issues/2371#issuecomment-1561226160)
- [ ] Update the function for  [conditionally updating CarePlan status](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCarePlanGenerator.kt#L325-L368) to
    1. Use the new models
    2. Iterate through the related resources, retrieve them from the db using the data queries provided and update the `status` of the the attributes stated in the config

**NB** - The Configs here is a sample. Please feel free to update the naming as you see fit. It is just used to show the functionality required

**Updated configuration sample**

```
"eventWorkflows": [
              {
                "eventType": "RESOURCE_CLOSURE",
                "triggerConditions": [
                  {
                    "eventResourceId": "carePlanToBeClosed",
                    "matchAll": false,
                    "conditionalFhirPathExpressions": [
                      "Patient.active = true"
                    ]
                  }
                ],
                "eventResources": [
                  {
                    "id": "carePlanToBeClosed",
                    "resource": "CarePlan",
                    "configRules": [
                      {
                        "name": "patientId",
                        "condition": "true",
                        "actions": [
                          "data.put('patientId', fhirPath.extractValue(Patient, 'Patient.id'))"
                        ]
                      }
                    ],
                    "dataQueries": [
                      {
                        "paramName": "instantiates-canonical",
                        "filterCriteria": [
                          {
                            "dataType": "REFERENCE",
                            "value": "PlanDefinition/e994ab6f-30a5-4450-9a90-691c8199f379"
                          }
                        ]
                      },
                      {
                        "paramName": "subject",
                        "filterCriteria": [
                          {
                            "dataType": "REFERENCE",
                            "computedRule": "patientId"
                          }
                        ]
                      }
                    ],
                    "relatedResources": [
                      {
                        "resource": "Task",
                        "searchParameter": "based-on"
                      }
                    ]
                  }
                ]
              }
            ]
```

**Comment by pld** [comment]
@dubdabasoduba how important is it we do this? Like what is the use case that this is required for?

**Comment by pld** [comment]
> @dubdabasoduba how important is it we do this? Like what is the use case that this is required for?

Thanks to @dubdabasoduba who explained that this is important because we may have Register or Profile views, or other business logic that depend on the the status of Conditions.

**Comment by ageryck** [comment]
> > @dubdabasoduba how important is it we do this? Like what is the use case that this is required for?
> 
> Thanks to @dubdabasoduba who explained that this is important because we may have Register or Profile views, or other business logic that depend on the the status of Conditions.

a good example is the pregnancy condition we use that to load the pregnant woman icon and use it to query for registers as well

**Comment by pld** [comment]
yea good example, until this issue is closed we can change the register config to use the existence of an ANC careplan attached the patient to determine whether to show that icon

**Comment by ellykits** [comment]
@dubdabasoduba We have discussed and update the configuration to the JSON below for more flexibility:

```json
{
  "eventWorkflows": [
    {
      "eventType": "RESOURCE_CLOSURE",
      "triggerConditions": [
        {
          "eventResourceId": "carePlanToBeClosed",
          "matchAll": true,
          "conditionalFhirPathExpression": [
            "CarePlan.active == false",
            "CarePlan.name == 'ANC CarePlan'"
          ]
        },
        {
          "eventResourceId": "carePlanToBeClosed",
          "matchAll": false,
          "conditionalFhirPathExpression": [
            "CarePlan.active == false",
            "CarePlan.name == 'ANC CarePlan'"
          ]
        }
      ],
      "eventResources": [
        {
          "id": "carePlanToBeClosed",
          "resource": "CarePlan",
          "searchParameter": "subject",
          "PlanDefinition": [],
          "attributesToUpdate": [
            {
              "key": "status",
              "value": "in-active"
            }
          ],
          "relatedResources": [
            {
              "resource": "Condition",
              "searchParameter": "subject",
              "attributesToUpdate": [
                {
                  "key": "status",
                  "value": "in-active"
                }
              ],
              "relatedResources": []
            }
          ]
        },
        {
          "id": "groupToBeClosed",
          "resource": "Group",
          "searchParameter": "subject",
          "attributesToUpdate": [
            {
              "key": "status",
              "value": "cancelled"
            }
          ],
          "dataQueries": [
            {
              "paramName": "type",
              "filterCriteria": [
                {
                  "dataType": "CODING",
                  "value": {
                    "system": "https://www.snomed.org",
                    "code": "35359004"
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by ageryck** [comment]
@Rkareko if we stick to using the `attributesToUpdate` and hardcode the update method, will it work for all foreseeable resources? If not then what if we target a list of specific resources?
cc @f-odhiambo @ndegwamartin @dubdabasoduba

**Comment by Rkareko** [comment]
> @Rkareko if we stick to using the `attributesToUpdate` and hardcode the update method, will it work for all foreseeable resources? If not then what if we target a list of specific resources? cc @f-odhiambo @ndegwamartin @dubdabasoduba

Are you referring to option 1 or 3 ?

**Comment by ageryck** [comment]
@Rkareko I was referring to Option 1, however hard coding the update implementation and targeting a specific list of resources eliminates the need to keep the configs as we can query all known resources. This should only be the approach after determining that we have no way to dynamically update the resources or just as a stop-gap measure.

**Comment by pld** [comment]
I think we should go with Option 1 for now, and leave an issue open to consider moving to option 3. I'm not convinced reflection is better we might to want to be confident we don't have any unexpected field status changes

**Comment by ageryck** [comment]
potential related resources include;
[Careplan Resource](https://www.hl7.org/fhir/careplan.html)
[Task Resource](https://www.hl7.org/fhir/task.html)
[Condition Resource](https://www.hl7.org/fhir/condition.html)
[Procedure Resource](https://www.hl7.org/fhir/procedure.html)
[Appointment Resource](https://www.hl7.org/fhir/appointment.html)
[CommunicationRequest Resource](https://www.hl7.org/fhir/communicationrequest.html)
[ServiceRequest Resource](https://www.hl7.org/fhir/servicerequest.html)
[ImmunizationRecommendation Resource](https://www.hl7.org/fhir/immunizationrecommendation.html)
[MedicationRequest Resource](https://www.hl7.org/fhir/medicationrequest.html)
[DeviceRequest Resource](https://www.hl7.org/fhir/devicerequest.html)
[NutritionOrder Resource](https://www.hl7.org/fhir/nutritionorder.html)
[SupplyRequest Resource](https://www.hl7.org/fhir/supplyrequest.html)

cc @dubdabasoduba

**Comment by Rkareko** [comment]
@ageryck @f-odhiambo @dubdabasoduba Kindly update the table below with the appropriate values

| Resource | Field | Value |
| :---         |     :---      |           :--- |
| Careplan  | status     | Completed   |
| Task     | status      | cancelled      |
|      | lastModified      | current date      |
| Condition     |       |       |
| Procedure     |       |       |
| Appointment     |       |       |
| CommunicationRequest     |       |       |
| ServiceRequest     |       |       |
| ImmunizationRecommendation     |       |       |
| MedicationRequest     |       |       |
| DeviceRequest     |       |       |
| NutritionOrder     |       |       |
| SupplyRequest     |       |       |

**Comment by pld** [comment]
Let's only address those we are currently using for eCHIS and eCBIS.

For other projects or future use in those projects we can do that in a future update
