### ISSUE TITLE
Background task worker performance improvements 

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2373]
**Describe the feature request.**
UI becomes unresponsive when Background tasks worker such as [FhirTaskPlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt), [FhirTaskExpireWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorker.kt) and [FhirCompleteCarePlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCompleteCarePlanWorker.kt) are running.

When the background workers are running content on the registers or profiles is not displayed until the workers complete.

Ways to improve performance of background workers

- [x] Run Background task workers in batches #2329
- [x] Research on SQLite Parallelism Resources [here](https://www.skoumal.com/en/parallel-read-and-write-in-sqlite/) and [here](https://medium.com/inloopx/transactions-and-threads-in-sqlite-on-android-215e46670f2d)
- [ ] Explore preventing running of background workers concurrently by use of [chaining](https://developer.android.com/guide/background/persistent/how-to/chain-work)

**Acceptance criteria**

- [ ] When user navigates between register and profile screens, data should load normally even when the background workers are running

**Implementation plan (For Engineers)**

- [ ] Update the current duration configurations for the background workers to be staggered e.g 15 mins, 30 mins and 45 mins

**Comment by Rkareko** [comment]
> Explore preventing running of background workers concurrently by use of [chaining](https://developer.android.com/guide/background/persistent/how-to/chain-work)

@ndegwamartin  @ellykits While chaining of background workers ensures that they don't run concurrently, this functionality only applies to one time workers.  [FhirTaskPlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt), [FhirTaskExpireWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorker.kt) and [FhirCompleteCarePlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCompleteCarePlanWorker.kt) are scheduled workers so this does not worker.

While enqueeing period workers it's possible to set an [initialDelay value](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/WorkManagerExtensions.kt#L49-L53). At the moment it is set to the same value as the repeat interval for the jobs. This can be updated so that each worker sets it's own `initialDelay` value so that the jobs can be staggered. This will may reduce the possibility of jobs starting at the same time.

**Comment by Rkareko** [comment]
> Research on SQLite Parallelism Resources [here](https://www.skoumal.com/en/parallel-read-and-write-in-sqlite/) and [here](https://medium.com/inloopx/transactions-and-threads-in-sqlite-on-android-215e46670f2d)

The SDK already offers support for [enabling write ahead logging](https://github.com/google/android-fhir/blob/3d6c259bb3381d27d0fce1732d6634ad356e8161/engine/src/main/java/com/google/android/fhir/db/impl/SQLCipherSupportHelper.kt#L80-L81)

Inspecting the `Quest` dbs listed on the file manager for the G60 phone shows that the `WAL` file is generated
