### ISSUE TITLE
[Event Management] - Closing Related Resources by the background worker

### ISSUE THREAD

**Issue by ageryck** [opensrp/fhircore#2421]
**Describe the feature request.**
Currently, the background worker uses a [service](https://github.com/opensrp/fhircore/issues/1703) to mark tasks as expired, it then goes ahead to close CarePlans whose `Task.status` are all `completed/cancelled`. However, the service doesn't close related resources that will be closed via configs once this #2371 is completed hence the need to implement the closure of related resources to avoid leaving active related resources

**Additional context**
Use case: If a PNC client has overdue tasks that expire after the defined PNC care period the background worker will close them and the CarePlan however the PNC condition will be left intact

**Acceptance criteria**
- [ ] Closure of all related resources

**Implementation plan (For Engineers)**

- [x] Add event workflow to the `ApplicationConfiguration`
- [x] Add `filterFhirPathExpression` config to the `ResourseConfig` . Sample json shown below
```
{
  "filterFhirPathExpression": [
    {
      "key": "Task.status",
      "value": "ready"
    }
  ]
}
```
- [x] Remove the hard coded logic for handling `PNC` and `sick child` condition closure in the existing [DefaultRepository.closeResource](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt#L744-L798) function
- [x] Add a utility function that 
1. Retrieves the event work flow configs from the application config
2. Retrieves all the event resources plus any related resources
3. Applies a filter on the retrieved related resources using the `filterFhirPathExpression` if available
4. Closes the retrieved resources using the existing [DefaultRepository.closeResource](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt#L744-L798) function
- [x] Invoke the utility function when Careplans are closed in the [FhirCompleteCarePlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirCompleteCarePlanWorker.kt#L76-L78) and [FhirTaskUtil](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskUtil.kt#L90-L91)

**Comment by dubdabasoduba** [comment]
**MVP implementation plan**

We will hardcode the `eventResourceId` and number of days check [here](https://github.com/opensrp/fhircore/blob/9c1938c5afc10a7d9d4e31a99d8c5e5b7d8768ae/android/engine/src/main/java/org/smartregister/fhircore/engine/data/local/DefaultRepository.kt#L674-L699). This means the workflow will only be able to close the PNC workflow Condition resources 

The default `eventResourceId` to use is `pncConditionToUse`
The default PNC time period is 28 days

**Comment by f-odhiambo** [comment]
Related ticket https://github.com/opensrp/fhircore/issues/2488
