### ISSUE TITLE
Write a function in RulesEngineService to transform Task status to ServiceStatus

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2462]
**Terms Definition**
- Task State --> This is the UI state shown to the users based on the color coding. These are **OVERDUE** (Red), **DUE** (Blue), **UPCOMING** (Grey), **COMPLETED** (Gray with a Green Check Mark)
- `Task.status` --> This is the actual status added to the Task resource. These are listed below

![Screenshot 2023-06-13 at 15 45 09](https://github.com/opensrp/fhircore/assets/4817531/c5eb17b4-f806-4ab2-98f8-279c296c145f)

**Describe the feature request.**
- We currently use the rules on the configs to identify the Task UI states. This is both cumbersome and prone to mistakes. 
- We have also redefined the Tasks status and added an Expired state.  This means the OVERDUE Task state does not have a `Task.status` tied to it.  
    - This calls for the function to perform the necessary calculation to identify the OVERDUE state and then use the `Task.status` to identify the rest of the Task state.

| Task Status (`Task.status`)     | Task State ( `Service Status`)  | Task State Definition                                                                                                                             | 
|---------------------------------|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------|
| Requested (`requested`)         | UPCOMING    | This state is given to a Task when the `Task.executionPeriod.start` date is in the future.                                                        |
| Ready (`ready`)                 | DUE         | This state is given to a Task when the `Task.executionPeriod.start` date is <= to `today()` and the `Task.executionPeriod.end` date >= `today()`. |
| In Progress (`in-progress`)     | IN PROGRESS | This state is given to a Task when the QuestionnaireResponse it acts on is marked as `QuestionnaireResponse.draft`.                                                     | 
 |                                 | OVERDUE     | This state is inferred from the following logic. A **Ready** / **In Progress** task that the `Task.executionPeriod.end` date < `today()`.         |
| Completed (`completed`)         | COMPLETED   | This state is given to a Task when the QuestionnaireResponse it acts on is marked as `QuestionnaireResponse.completed`.                                                 |
| Cancelled (`cancelled`)         | EXPIRED     | This state is given when the date `today()` > `Restriction.period.end`.                                                                           |

The different implementation tickets and color coding can be found linked [here](https://github.com/opensrp/fhircore/discussions/1557).

**Implementation tickets actions**
- [x] Validate that all the background workers and Task State change functions are updated to match the above behaviour. 
- [x] Write a Task State function on the `RulesFactory` class to allow the projects to easily determine the Task States.
- [x] Update the documentation to reflect how the above service function is to be used.

**Implementation plan (For Engineers)**

- [x] Verify [FhirTaskExpireUtil](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireUtil.kt#L45-L77) sets correct Task status
- [x] Verify [FhirTaskPlanWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskPlanWorker.kt#L86-L120) sets correct Task status
- [x] Add a `EXPIRED` entry to `ServiceStatus` class
- [x] Write a Task State function on the [RulesEngineService](https://github.com/opensrp/fhircore/blob/8f00977219f9a84882a80cd635f8cfab8aed4940/android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt#LL123C15-L123C33) class that
        1. Takes a `Task` as a parameter
        2. Determines the Service Status using the criteria defined above
        3. Returns the Service Status
- [x] Update the documentation to reflect how the above service function is to be used.

**Comment by pld** [comment]
does this need to go into a milestone, it seems pretty core, but how should we prioritize it?

**Comment by dubdabasoduba** [comment]
@pld yes. We already have @Rkareko earmarked to work on it.

**Comment by Rkareko** [comment]
@dubdabasoduba @ellykits Some of the Task States require checking the `QuestionnaireResponse` status, since this method is called in the configs, where will the `QuestionnaireResponse` be retrieved from?

**Comment by dubdabasoduba** [comment]
@Rkareko I think the 2 States (In_Progress and Complete) are updated immediately after a Questionnaire is saved at that point you would have the QuestionnaireResponse.

**Comment by dubdabasoduba** [comment]
The Tasks state function on the `RulesFactory` Should just take in a Task and then return the Task State based on the status the Task has.
