### ISSUE TITLE
[In-app Reporting] Add the Practitioner selection screen on the In-app reporting workflow. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2472]
**Describe the feature request.**
- Supervisors need the ability to filter the in-app reports based on the different practitioners they supervise. This means we need to provide an option for them to select the practitioner while on the reports page. 
- This screen should however be hidden based on a config for patient-centric applications
- Below is the screenshot of the desired reporting workflow. 

![Screenshot 2023-06-14 at 21 48 46](https://github.com/opensrp/fhircore/assets/4817531/42996c7d-a275-4c66-bd40-33a473996cae)

**Acceptance criteria**
- [x] Show a list of practitioners on the first screen of in-app reports. 
    - [x] This list should be configurable like the other registers on the app. 
    - [ ] The single practitioner in-app reporting should be enabled if this page is shown
- [ ] Add the ability to hide to the Practitioner selection screen. 
    - [ ] The single practitioner in-app reporting should be disabled if this page is hidden  

**Implementation plan (For Engineers)**

- [x] Add register configs for displaying practitioners
- [x] Update `navigation_config` to launch the practitioner register
- [x] Add action to launch report screen when practitioner row is clicked using `LAUNCH_REPORT` workflow
- [x] Update logic for generating reports to add pass `practitionerId` to the `evaluatePopulationMeasure` function
- [x] Refactor navigation logic to open the `Module selection` screen before the `Report date selection` screen

**Comment by AnnieMungai** [comment]
@madrinekariuki the service delivery (MSR) reports are not yet worked on. They are in the next phase of work. However, the SSRR reports are looking good as they are. 

LGTM!
