### ISSUE TITLE
Add generic date service function to add or subtract days, weeks, months or years from/to current date

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2569]
**Describe the feature request.**
The current implementation has a [DateService.addOrSubtractYearFromCurrentDate](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/services/DateService.kt#L25C16-L39) function that adds or subtracts years from the current date.
There is need to extend this functionality to handle addition and subtraction of days, weeks, months and years. 

**Acceptance criteria**

- [ ] Users can use this method to add/subtract days to/from current date
- [ ] Users can use this method to add/subtract weeks to/from current date
- [ ] Users can use this method to add/subtract months to/from current date
- [ ] Users can use this method to add/subtract years to/from current date

**Implementation plan (For Engineers)**

- [ ] Add a utility function in the [DateService](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/services/DateService.k) class that can add or subtract days, weeks, months or years from/to current date
