### ISSUE TITLE
Add ability to configure resource Id used to open profiles

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2580]
**Describe the feature request.**
The current implementation for launching questionnaires relies on the `baseResource.Id` to open profiles as shown [here](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/util/extensions/ConfigExtensions.kt#L66).
This works well for registers where the baseResource is the same resource used to launch a profile e.g Group resource in the HouseHold register is the same resource used to load the HouseHold register.
For cases where the baseResource is not the same resource used to open a profile this will not work. Case in point is in the task register where we need to open the patient profile which requires a different resource i.e `Patient`

There is need to update the app logic to allow configuration of the `resource id` used to open a profile.

**Acceptance criteria**

- [ ] One is able to open a profile that uses a different base resource from the one used in the register, e.g opening a patient profile from a task register

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. On the side menu click on the `Task Register`
3. Click on on any row on the register.
4. App should navigate the the appropriate patient profile

**Implementation plan (For Engineers)**

- [x] Add a new `ActionParameterType` titled `RESOURCE_ID`
- [x] In the `ConfigExtension` class when handling the `ApplicationWorkflow.LAUNCH_PROFILE `, check whether the `RESOURCE_ID` is available. If availabe use it as the `NavigationArg.RESOURCE_ID` else use the `baseResourceId`.
- [x] Add documentation
