### ISSUE TITLE
Implement an optional and configurable code path that uses $apply for PlanDefenition execution

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#2733]
**Describe the feature request.**
As a content creator and project implementer I want to be able to run $apply on a PlanDefinition and any referenced CQL to create output resources, e.g. CarePlans.

I want to be able to optionally enable this instead of, or in addition to, the current method of executing PlanDefinitions.

**Additional context**
Our current approach to executing PlanDefinitions is to run a StructureMap on the PlanDefinition that uses FHIRPath within it to create additional resources.

The android-fhir repo has an [example app](https://github.com/google/fhir-app-examples/tree/main/configurablecare) that executes a [PlanDefinition](https://github.com/google/fhir-app-examples/blob/main/configurablecare/app/src/main/assets/fhir-resources-example.json) using $apply through their [Workflow API](https://github.com/google/fhir-app-examples/blob/main/configurablecare/app/src/main/java/com/google/fhir/examples/configurablecare/care/CarePlanManager.kt#L138).

**Acceptance criteria**

- [ ] Google's example PlanDefinition is loaded into an app config that also includes a config to execute it through the app UI
- [ ] Executing the PlanDefinition through the app UI produces the expected output

**Area path**

1. Login to the WHO EIR
2. Open _Navigation bar_
3. Click on _Patient register_
4. Click on _Add a patient_
5. Click on _Run plan def_ configured in the add patient questionnaire

**Implementation plan (For Engineers)**

- [ ] Introduce a new boolean config property called `QuestionnaireConfig.generateCarePlanWithWorkflowApi`. When set to `true`, use $apply from the Workflow library to generate CarePlan otherwise default to using the current approach in `FhirCarePlanGenerator#generateOrUpdateCarePlan()`. 

- [ ] Update the signature for the function `FhirCarePlanGenerator#generateOrUpdateCarePlan()` to include a new parameter `generateCarePlanWithWorkflowApi`. The value for this param should be obtained from the `QuestionnaireConfig`, which is available in the `QuestionnaireViewModel` (where the generate CarePlan function is called).

- [ ] NOTE: The `FhirCarePlanGenerator#generateOrUpdateCarePlan()` is an overloaded function. The one to be updated has `planDefinitionId: String` in its parameters and is invoked directly in the `QuestionnaireViewModel`.

- [ ] Implement functionality to execute $apply to generate CarePlan. Ideally, this should be done in a separate class (`WorkflowCarePlanGenerator`). The class will be injected into the `FhirCarePlanGenerator` constructor. 

- [ ] Update the implementation inside `FhirCarePlanGenerator#generateOrUpdateCarePlan()` to either use the new `WorkflowCarePlanGenerator.generateCarePlan()` or the current depending on the value passed through the `QuestionnaireConfig.generateCarePlanWithWorkflowApi` property.

- [ ] The implementation for `WorkflowCarePlanGenerator.generateCarePlan()` can be adapted from this function [applyPlanDefinitionOnPatient](https://github.com/google/fhir-app-examples/blob/e6db1370e9734872472153292cdc1ee2cbed06a2/configurablecare/app/src/main/java/com/google/fhir/examples/configurablecare/care/CarePlanManager.kt#L126C44-L126C44) in the sample application. Copy and modify all the necessary functions from the sample code to `WorkflowCarePlanGenerator` as required. 

- [ ] Remember to document the functions and use the HILT injected instances of the [KnowledgeManager](https://github.com/opensrp/fhircore/blob/c6e17d3dcc2520beeaa930f48bb23c7134b790c3/android/engine/src/main/java/org/smartregister/fhircore/engine/di/CoreModule.kt#L63) and [FhirOperator](https://github.com/opensrp/fhircore/blob/c6e17d3dcc2520beeaa930f48bb23c7134b790c3/android/engine/src/main/java/org/smartregister/fhircore/engine/di/CoreModule.kt#L70). The two can be injected as constructor properties of the `WorkflowCarePlanGenerator` class.

- [ ] Update the tests for `FhirCarePlanGenerator#generateOrUpdateCarePlan()` and write new tests for `WorkflowCarePlanGenerator.generateCarePlan()`. Avoid using mocks unless really necessary, test the actual implementation instead, using injected dependencies.

**Comment by ellykits** [comment]
@owais-vd I've updated the implementation plan for this issue. Do let me know if you need any clarification. 

cc: @dubdabasoduba
