### ISSUE TITLE
CHW/ANC SubTask - Family register -  see a list of all families registered

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#275]
- [ ] User can see a list of all families registered. This may be integrated into the activity view 
2.5 days FTE + 20% buffer

**Comment by isabelcshaw** [comment]
In the CHW workflow, the family register will be the equivalent of the patient list view in the COVAX app. This view will be what the user lands on when logging into the app. It will show all registered families. This issue does not include the ability to filter, sort, or search this list. 

[Here is a link to the mocks](https://www.figma.com/file/QZ4cdpgBNy86XTOUnrnLap/COVID19-FHIR-Future-Design-System?node-id=1063%3A14329) with the screens ordered as well as an an image of the register view below. 

<img width="218" alt="Screen Shot 2021-06-29 at 6 41 23 PM" src="https://user-images.githubusercontent.com/12836913/123889081-9f91d600-d909-11eb-817b-d0ec7b655c6a.png">

Notes on this view: 
- [ ] The individual family components on the list view will show the family name, location, and an icon to represent the relevant care plans of the family members (ANC, PNC, child health). This is the same as we previously did in OpenSRP. 
- [ ] The individual family components will each also have an indication on the right side as to whether that family has any services due. This is also a carryover from older OpenSRP apps. If any service is overdue for any member of the family, it will be red instead of blue. The number will represent the sum of all services due. 
- [ ] This feature does not have to be delivered as an MVP, but the "All Families" title at the top is meant to be clickable (note the carrot). The idea is that you would change to an ANC register (for example) here instead of in a side menu. 
- [ ] The navigation at the bottom is yet to be confirmed. At the moment it can be left blank or placeholders can be used.

**Comment by isabelcshaw** [comment]
As is being discussed, the goal here would be to implement a configurable view - with the list components for each app being tailored to the implementation. 

Attached here is a screenshot of what these different list components will look like across apps. 

<img width="197" alt="Screen Shot 2021-06-29 at 6 51 33 PM" src="https://user-images.githubusercontent.com/12836913/123889783-08c61900-d90b-11eb-847b-beaab33eec94.png">

**Comment by maimoonak** [comment]
https://github.com/opensrp/fhircore/pull/493 The was supposed to address the first mockup (without services count part) the issue but now it needs to be on new code structure.

**Comment by maimoonak** [comment]
The family list in first mock is shown with PR https://github.com/opensrp/fhircore/pull/547.

The navigation is yet to be decided and would be implemented across app.

![Screenshot from 2021-09-20 13-44-56](https://user-images.githubusercontent.com/4829880/133976558-4f2d11a9-622d-446e-9ee3-c294e50df294.png)

@f-odhiambo

**Comment by f-odhiambo** [comment]
Done
