### ISSUE TITLE
Add Register filter UI and configs

### ISSUE THREAD

**Issue by allan-on** [opensrp/fhircore#2760]
**Describe the feature request.**
A filter button from which a user can trigger the loading of filter the options form (Questionnaire) is required as part of the Register filters implementation

**Additional context**
This is a first subtask of #2698 

#### Mockups
![image](https://github.com/opensrp/fhircore/assets/16164649/8f35c843-4433-4f84-a1a6-e726d638bf6b)

**Acceptance criteria**
- [x] Show the filter icon on the app bar if enabled and hidden if filtering is disabled
- [x] Show the configured filter questionnaire with filter options (attributes) based on the filter configs when the filter icon is clicked

**Implementation plan (For Engineers)**

- [x] Update the UI and add a new filter button with the filter icon in the app bar. This button should be disabled/hidden by default and only enabled through configs
- [x] The button action should support the workflow defined in the filter action configuration
- [x] Introduce new advanced filter configuration to be part of register configurations.
  - [x] The configs should allow enabling/disabling the filter feature
  - [x] Include the _actions_ definitions of the trigger, workflow and questionnaire to be launched
- [x] Update the Questionnaire configs and introduce a **`save`** attribute to indicate if resources should be extracted and persisted when the Questionnaire is submitted
