### ISSUE TITLE
Implement filtering of register records

### ISSUE THREAD

**Issue by allan-on** [opensrp/fhircore#2764]
**Describe the feature request.**
When filters are applied to a register we should show results of filtering the records

**Additional context**
This is the second subtask of #2698

**Acceptance criteria**

- [ ] Applying filters should filter the records on the register based on the filter attributes/selection
- [ ] Display the count of filtered records when the filter is applied
- [ ] No new resources should be created on account of the register Questionnaire form submission 

**Implementation plan (For Engineers)**
- [ ] Add a filterQueryId attribute to the` "dataQueries": []` section whose value is the linkId in the Questionnaire which has the question item with the filter values as the choice options
- [ ] Update handling of questionnaire submissions to: 
  - [ ] Not extract resources (but instead retrieve the filter values) when the save config (saveQuestionnaireResponse) is set to false
  - [ ] Extract and build data queries for use in filtering.  The data queries to be updated will be referenced using the **linkIds** from the Questionnaire. 
- [ ] Add updating the register configuration `baseResourceConfig` with the new data queries built from the retrieved filter values. We want to update the ` List<DataQuery> dataQueries` with the new queries. 
- [ ] Invoke the `loadRegisterData()` to show filtered records
- [ ] Clearing all filters should reload the register and display clients in that register based on the register config dataQueries + filterCriteria
