### ISSUE TITLE
CHW/ANC SubTask - User can view a family profile

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#284]
- [x] Family profile details  - Members 
- [ ] Which family member has actual services due 
- [x] View Visit History  - Last Visit 2 or 3 dates (Encounters) - #290

![image](https://user-images.githubusercontent.com/4540684/125637185-0aae7a35-f9c8-407b-8bdc-a083f6fabd23.png)

**Acceptance criteria** 

- [x] User can be able to query for all members of a household from the Head of household's profile 
- [x] Use can be able to add a new member from the family profile 
- [x] User can be able to view the past 3 encounters with the ability to view more once clicking the see all button

**Comment by mwkhan1983** [comment]
waiting on PR https://github.com/opensrp/fhircore/pull/503

**Comment by syedowaisali90** [comment]
@f-odhiambo the above ui mock showing some `task/task overdue` in a family member item, have you know that where to get the task and I also want to know that which icon should be used based on the encounter

**Comment by f-odhiambo** [comment]
Good point @syedowaisali90  At the moment you can use a generic icons which we can replace once the design team provides fresh icons.
On the second item about the tasks , the mock alludes that we shall be querying they patients plus the associated dues takes wether upcoming(green) or due (red) . This will be retrieved via careplan which you can omit for now and come back to it later

**Comment by pld** [comment]
Cool so for now no Tasks, is there a discussion on how we'll do the Tasks in this card to add somewhere else? Putting it below for now.

I think there's also an open question of whether we link a Task directly to a Patient. The .for field of a Task would be appropriate for this, alternatively we'd have to look for the appropriate CarePlan attached to the Patient (or maybe any CarePlans attached to the Patient) and get the Tasks attached to those CarePlans.

Looking at the [Task](https://www.hl7.org/fhir/task-definitions.html#Task.for), using .for seems semantically appropriate and maybe more efficient *if* we don't care about filtering the Tasks by CarePlan (tbd I guess on how CarePlan and Tasks are connected)
