### ISSUE TITLE
Background worker for closing resources related to copleted Service requets

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2841]
**Describe the feature request.**
There is a need to close resources when a service request is completed. This comes from a WDF requirement docemented [here](https://github.com/ona-health/hisp-wdf-fhir-resources/issues/96). The service request in this particular isntance is completed by a 3rd party system. Once the completed service request is synced down the app, a process should be triggered which closes any related resources such as tasks, careplans e.t.c

**Acceptance criteria**
- [ ] For a completed Service Request, all the resources that have been configured for closure should be closed.

**Implementation plan (For Engineers)**

- [ ] Add a new function in [FhirResourceUtil](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirResourceUtil.kt) that fetches `completed` `ServiceRequests` from the db and calls the [FhirResourceUtil.closeRelatedResources](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirResourceUtil.kt#L212C15-L225) method
- [ ] Call the newly created method in the [FhirTaskExpireWorker](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/task/FhirTaskExpireWorker.kt)
- [ ] Rename `FhirTaskExpireWorker` to `FhirResourceExpireWorker`
