### ISSUE TITLE
Test out the latest Upstream JPA and support HAPI release against the Info Gateway

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2850]
**Describe the feature request.**
- We currently have the info gateway complete with all the plugins developed. 
- We would like to test a move from to the latest versions of the [JPA](https://github.com/hapifhir/hapi-fhir-jpaserver-starter/releases/tag/image%2Fv6.10.0) and supported [HAPI](https://github.com/hapifhir/hapi-fhir/releases/tag/v6.10.0) releases

**Implementation Plan**
- [x] Check if the new JPA and HAPI update the DB structure. If yes, document the differences and potential migration issues
- [ ] Check whether the gateway filtering works as expected on these versions for fhircore and web clients 
- [ ] Review if the FHIR Core application works as expected with these versions
     - [ ] Check whether sync works well
     - [ ] Check the sync times 
     - [ ] Check the API request and response times. 
- [ ]  ~~Benchmark the performance of the new releases~~ : To be tracked by https://github.com/opensrp/fhircore/issues/2884

**Comment by dubdabasoduba** [comment]
@pld Please review and share feedback

**Comment by pld** [comment]
Thanks, lgtm! moved to current milestone

**Comment by ndegwamartin** [comment]
Currently blocked by this ticket https://github.com/onaio/infrastructure/issues/7517

**Comment by ndegwamartin** [comment]
This is now unblocked, the Docker image of FHIR Gateway Plugins version 1.0.2 is available on Docker hub here https://hub.docker.com/r/onaio/fhir-gateway-plugin/tags

**Comment by ndegwamartin** [comment]
@dubdabasoduba [see comment here](https://github.com/opensrp/fhircore/pull/2880#issuecomment-1825626567)

**Comment by ndegwamartin** [comment]
@dubdabasoduba @rehammuzzamil I've decoupled the performance testing from this ticket to this one here https://github.com/opensrp/fhircore/issues/2884 . The other items can be worked on and closed as part of this ticket.

Also note, newer versions of the JPA Starter and HAPI FHIR Server have been released for **v6.10.0**

**Comment by lincmba** [comment]
Currently being addressed here https://github.com/onaio/infrastructure/pull/8121

**Comment by f-odhiambo** [comment]
**Update July 1st 2024**

1. We can deploy a new gateway with the latest HAPI to resolve this issue but we cannot upgrade the HAPI version to the latest without resolving the issue it introduces with the latest updates

**Comment by f-odhiambo** [comment]
This is to resume Aug 6th 
CC @ageryck @Wambere

**Comment by f-odhiambo** [comment]
This needs to be reassigned as per Aug 13th Update
CC @dubdabasoduba @ndegwamartin

**Comment by ndegwamartin** [comment]
Un-assigning the current assignments to await reassignment based on shifting priorities

**Comment by Wambere** [comment]
Quick update:
Test deployment for this was successful, included some cli migrations - [link](https://github.com/onaio/infrastructure/issues/8346)
Testing of app is ongoing. Small blocker on gateway, getting assistance from @ndegwamartin to check it out

**Comment by Wambere** [comment]
Tested the different sync strategies and they all seem to sync as expected
Great job team!
