### ISSUE TITLE
CHW/ANC SubTask - User can record a pregnancy 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#288]
Create an Episode of Care and Encounter to record a pregnancy 
**The Use case**
1. Select a patient from the household and ​Enroll a patient as an ANC Client e.g.  [Patient/charity](https://build.fhir.org/ig/who-int/anc-cds/Patient-charity.html)  See screenshot attached from ANC flow 
2. ​The mother self-reports pregnancy, CHW could ask some follow up questions (see screenshot) and then resulting in the creation of the [Condition/charity-pregnancy](https://build.fhir.org/ig/who-int/anc-cds/Condition-charity-pregnancy.html)
3. Adding the  pregnancy triggers the  creation of the following resources   - Examples linked 
- [ ] [EpisodeOfCare/charity-pregnancy-episode](https://build.fhir.org/ig/who-int/anc-cds/EpisodeOfCare-charity-pregnancy-episode.html)
- [ ]  [Encounter/charity-first-contact](https://build.fhir.org/ig/who-int/anc-cds/Encounter-charity-first-contact.html) 
- [ ] [Goal/charity-pregnancy-goal](https://build.fhir.org/ig/who-int/anc-cds/Goal-charity-pregnancy-goal.html)
- [ ] CarePlan/charity-pregnancy-plan - _To be done by Workflow API once ready_ 

**Screenshot**
![image](https://user-images.githubusercontent.com/4540684/131988119-f1b2f6b4-0267-4e8d-b5f2-a7c71bb3496c.png)

**Comment by isabelcshaw** [comment]
For all female clients of childbearing age, there will be an option to record a pregnancy. In order to do so, the end user will hit the option menu in the top right corner (see image below). One of the options in the menu will be to record a pregnancy. That will open a short questionnaire. _Fields to be confirmed._   

When the questionnaire is submitted, the ANC plan definition will be added to that woman's care plan. 

In the future, we may build the ability to record the fact that a woman is pregnant during the family registration workflow, but, for now, we will leave it as a separate step. 

<img width="259" alt="Screen Shot 2021-07-15 at 7 06 04 PM" src="https://user-images.githubusercontent.com/12836913/125880656-d927b15d-49e4-47d8-9626-5574b8588bfa.png">

**Comment by pld** [comment]
How do we record this in FHIR?

**Comment by f-odhiambo** [comment]
The Pregnancy can be recorded as a [condition](https://build.fhir.org/ig/who-int/anc-cds/Condition-charity-pregnancy.json.html) 

cc @isabelcshaw @pld

**Comment by pld** [comment]
Sounds good, from the dependencies looks like we will close this in the course of working on #406
