### ISSUE TITLE
Implement Register Footer configuration properties

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2889]
**Describe the feature request.**
As part of the styling updates documented [here](https://github.com/opensrp/fhircore/issues/2887) there is a need to make the footer component on the registers configurable. The initial implementation will only cover the configurability of the bottom padding so as to adress the issue of the Fab button overlaying the content of the register.

**Additional context**
If available add any other context or screenshots about the feature here.

**Acceptance criteria**

- [ ] Should be possible to define the value for the bottom padding of the register footer via configs

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on HouseHold register
4. Note that for registers with content that fills the screen, the register footer is obstructed by the Fab button as seen below

![Screenshot from 2023-11-28 10-59-43](https://github.com/opensrp/fhircore/assets/47570855/f7dd7473-2322-4185-a83d-a4e23d4a52f3)

**Implementation plan (For Engineers)**

- [x] Add a `RegisterFooterProperties` data class in the [configuration.view](https://github.com/opensrp/fhircore/tree/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/view) package.
  - The class should only inherit from `Parcelable`
  - Contains the variable `bottomPadding` with default value of 32

- [x] Update the [RegisterCardConfig](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/configuration/register/RegisterCardConfig.kt) to have a new variable named `registerFooter` of type `RegisterFooterProperties`

- [x] Update the [RegisterFooter](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/ui/components/register/RegisterFooter.kt) component to
  - Take  constructor parameter named `registerFooterProperties`  of Type `RegisterFooterProperties` with a default value of `RegisterFooterProperties()`
  - Update the Row modifier bottom padding value to the one define in the `registerFooterProperties`

- [ ] Update the call for the `RegisterFooter` in the [RegisterCardList](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/register/components/RegisterCardList.kt#L105-L111) to pass the configured register footer properties

- [ ] Update the [HousHold register config ](https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/assets/configs/app/registers/household_register_config.json) with the `registerFooter` configuration

**Comment by Rkareko** [comment]
Fixes issue raised on #2821

**Comment by ellykits** [comment]
Do you know if we need a new configuration just for the padding? The alternative would be to use a condition that updates the padding depending on whether the `RegisterConfiguration` has configurations for fab actions. If the FAB configurations exist use more padding otherwise default to the current. Unless this new property will be useful in other aspects I do not think it is necessary. There is a potential abuse/misuse of this config by the way if we leave it open.

**Comment by Rkareko** [comment]
> Do you know if we need a new configuration just for the padding? The alternative would be to use a condition that updates the padding depending on whether the `RegisterConfiguration` has configurations for fab actions. If the FAB configurations exist use more padding otherwise default to the current. Unless this new property will be useful in other aspects I do not think it is necessary. There is a potential abuse/misuse of this config by the way if we leave it open.

The thinking is that the padding for the footer would be configurable so that if the design requirements change in future, code changes would not be required.

**Comment by Rkareko** [comment]
@HenryRae we have the options of making the padding for the register footer either configurable (projects set the padding value in configs) or not (the values 32 for registers without a Fab and 80 for registers with A fab are set in code)

The concern with making it configurable is that, as Kitoto mentioned, there is the risk of abuse of this config which would result in different registers or different projects not having a consistent padding.

The concern with not making it configurable is that the padding values may change in the future which would require changes in the code itseself

What would your advice be on this? cc @f-odhiambo @dubdabasoduba @allan-on @ellykits

**Comment by HenryRae** [comment]
> The concern with not making it configurable is that the padding values may change in the future which would require changes in the code itseself

would the change in code require to be done project by project?
Else, I think not abusing it would be the ideal way to go.

**Comment by Rkareko** [comment]
Implementation will be done using approach documented on #2892

**Comment by ageryck** [comment]
Re-opening this issue to create a PR of the same pointing to `0.2.5`
