### ISSUE TITLE
Fix main content padding on various screens

### ISSUE THREAD

**Issue by Rkareko** [opensrp/fhircore#2892]
**Describe the feature request.**
Update the implementation for the register, profile and reporting screens to use the padding requirements set out on this issue #2887

**Acceptance criteria**

- [x] The bottom padding for the various screens should match the updated designs listed on [this issue](https://github.com/opensrp/fhircore/issues/2887)

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**

- [x] Set bottom padding for list (LazyColumn) used to render views in profile and measure report screens, as well as the row in the register footer to `80.dp` if fab configuration exists in profile / register configuration otherwise default to `32.dp`
- [x] The UI to be updated are in `MeasureReportListScreen`, `ProfileScreen` and the `RegisterFooter` composable screens

**Comment by ageryck** [comment]
Re-opening this issue to create a PR of the same pointing to 0.2.5
