### ISSUE TITLE
Add functions to fetch Assignment data using Rules on the Configs

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#2900]
**Describe the feature request.**
- The OpenSRP app stores assignment data in the secure shared preferences. We would like to write some methods on the  [RulesFactory](https://github.com/opensrp/fhircore/blob/main/android/engine/src/main/java/org/smartregister/fhircore/engine/rulesengine/RulesFactory.kt) to allow the fetching of this assignment data via rules on the configs
- Each assignment data point should be fetched separately

**Acceptance criteria**
- [ ] Define methods that allow the fetching of the following assignment data
    - [ ] Practitioner Id
    - [ ] Practitioner Assigned CareTeam(s)
    - [ ] Practitioner Assigned Organization(s)
    - [ ] Practitioner Assigned Location(s) 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by ellykits** [comment]
@Raynafs  You can access the `SharedPreference` instance from the injected `ConfigurationRegistry`
