### ISSUE TITLE
Configurable Questionnaire config type

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#2912]
**Describe the feature request.**
A clear and concise description of the feature or what problem is being solved 
There is a requirement that results in the need of configurable Questionnaire config type using rules.

**Additional context**
- Needed for Engage, but it should be a common use case.
- Use case: After user initially submits a task related Questionnaire, the user wants to open the Questionnaire again to edit it's answer. This is a change of Questionnaire config type from DEFAULT to EDIT.

**Acceptance criteria**
- [x] The Questionnaire config type accept a rule from the rules engine

**Area path**
Checkout and run the QuestionnaireConfigTest.

**Implementation plan (For Engineers)**
- [x] Change the Questionnaire config type property from ENUM to STRING
- [x] Interpolate the Questionnaire config type
- [x] Adapt the functions that are affected by the change of Questionnaire config type property change from ENUM to STRING
- [x] Adapt the test to accept rules

**Comment by FikriMilano** [comment]
@f-odhiambo LOE less than a day
