### ISSUE TITLE
Refactor data migration logic to run in the background

### ISSUE THREAD

**Issue by ellykits** [opensrp/fhircore#2945]
**Describe the feature request.**
Create a new Job to be run post-login for data migration. Sync should be triggered once the task is completed. Once the data migration is complete, notify the user via snack bar/toast message.

**Additional context**
The current implementation is blocking UI

**Acceptance criteria**

- [x] Migrate data based on configuration
- [x] Trigger sync on migration completion 
- [x] Notify user once the migration is completed 

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Observe data migration is triggered in the background
3. Observer toast/snackbar notification once migration is done

**Implementation plan (For Engineers)**
- Move the data migration code to a work manager job 
- Schedule job immediately after login 
- Listen to job completion status to notify the user about the status of the job
