### ISSUE TITLE
Update the `Application_Config.syncStrategy` to a String

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3004]
**Describe the feature request.**
- The Application_Config has a `syncStrategy` attribute that helps direct  the FHIR Info Gateway on how the app should sync data.  
- This attribute is currently an Array.  However the FHIR Info Gateway expects it to be a string since only one Sync Strategy can be effected at a time. 
- This issue is to update the OpenSRP 2.0 mobile app configs to defne this attribute as a string.  
- We would also need to check the OpenSRP FHIR Info Gateway Plugins to make sure it also expects a string. 
- This change should be effected for the `main` and `opensrp-0.2.5` branches on fhircore. 

**Acceptance criteria**
- [ ] The `Application_Config.syncStrategy` should be a string and not an Array
- [ ] The update should also work with the OpenSRP FHIR Info Gateway Sync plugins
- [ ] Update configuration docs to reflect (from Array to String) 

**Implementation plan (For Engineers)**
@ndegwamartin  and any other assigned engineer can update
