### ISSUE TITLE
Add the ability to calculate distance between 2 locations

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3039]
**Describe the feature request.**
- We would like to add the functionality to calculate the distance between two `Location`'s.  The main constraint for this implementation is the need for the Locations to have the `Longitude` and `Latitude`
- We also need to have the ability to calculate the distance between a location and the current GPS location of the device in question. 
- The functionality should be accessible via the configurations. 

**Acceptance criteria**
- [ ] Should be able to calculate the distance between 2 location resources in Kilometres or Metres.
- [ ] Should be able to calculate the distance between a location resource and the current GPS location of the device in Kilometre and Metres.
- [ ] Should be able to reference the functionality from the OpenSRP 2.0 configs using rules

**Implementation plan (For Engineers)**
- Add a location service on the Engine module 

- Implement the following functions on the LocationService File

```kotlin
data class Point(longitude: Double, latitude: Double)

private fun calculateDistance(pointA: Point, pointB: Point) logic goes here

fun calculateDistance(locationA: Location, locationB: Location) //function wrapping the each location latitude and longitude in the point class 

fun calculateDistanceFromCurrentLocation(location: Location) // function wrapping the each location latitude and longitude in the point class 
```

- Add the LocationService to the facts map for access in the rules
- Additional resources to get the GPS co-ordinates is on this [file](https://github.com/opensrp/fhircore/blob/8431a58da76ba0707e30b5a4b191530063944cb8/android/quest/src/main/java/org/smartregister/fhircore/quest/util/LocationUtils.kt#L46)

**Comment by dubdabasoduba** [comment]
We had something similar implemented for the OpenSRP 1.0 version of EUSM. I think [this](https://github.com/opensrp/opensrp-client-eusm/blob/3083ef5c14792682f9f762cb3835e6ba20fd9447/opensrp-eusm/src/main/java/org/smartregister/eusm/util/AppUtils.java#L68) function would be a good place to borrow the implementation from.

**Comment by AnnieMungai** [comment]
@Mstjamush This is ready for QA on EUSM.
