### ISSUE TITLE
[Sync Enhancement | Data Access Checker] Add a deployment config called `ClientLocation.userAssignedLocation`

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3053]
**Keyword Definition**
- **Client** - An entity that has data collected against it (e.g. Family/Household, Family/Household member, Patient, Service Point or Product).
- **Client Location** - This term is used to refer to location(s) associated with the client.
    - This would mean the location where the family or family member lives for the case of the SID (Summit Institute for Development) applications
    - This would mean the service point of where data collected belongs to for the case of EUSM (End User Supply Monitoring)
- **Sync Locations** - These are the locations used to filter the data to be synced to the application.

**Describe the feature request.**
- OpenSRP 2.0 is adding a new Sync Strategy called Client Location. This strategy will sync data based on the Client Location `meta.tag`. 
- It will heavily depend on the Sync Locations, which can be generated in 2 ways i.e 
    - User Assigned Locations - These are the locations assigned to a user via OpenSRP web. 
    - User Selected Locations - These are the locations selected by the user on app log in.  

**Technical Description of enhancement**
- [ ] Create a deployment config for the FHIR InfoGateway. This config should be created the same way all the other FHIR Info gatway configs are.  It should be named `ClientLocation.userAssignedLocation` i.e `{"clientLocation":{"userAssignedLocation":true}}`
- [ ] `true` should be the config default

**Acceptance criteria**
- [ ]  Have a config that can only be defined and altered during deployment

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
Is this defining the sync strategy? Or the metatag? I think the sync strategy

**Comment by pld** [comment]
Hmm, does this go in the OpenSRP mobile app or in the gateway? I don't think we'd want the app to be sending something that affects how the validation occurs, because in an adversarial situation they could change that validation.

**Comment by dubdabasoduba** [comment]
@pld as discussed this goes to the gateway

**Comment by pld** [comment]
nb following or terminology change, updating this to `relatedEntityLocation`

**Comment by dubdabasoduba** [comment]
@ndegwamartin @lincmba closing this after our chat on Friday. We do not need it.
