### ISSUE TITLE
Test variable evaluation via cqf expressions

### ISSUE THREAD

**Issue by ageryck** [opensrp/fhircore#3060]
**Describe the feature request.**
Allow the SDC to evaluate variables passed with definite values to be evaluated via cqf expression. An example will be testing a `minDate` value of a static date provided to validate the `datepicker` widget.

**Additional context**
Refer to these two tickets
https://github.com/google/android-fhir/issues/2292
https://github.com/google/android-fhir/issues/1759

And the Implementing PR  - https://github.com/google/android-fhir/pull/2326

**Acceptance criteria**
 - [x] Ability to set a `minDate` on the date picker and use it for widget validation
 - [x] Ability to use a static date such as patient dob as a `minDate`
 - [ ] Documentation on feature use

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem

### Demo
| Image of when date min value is today - 6 days and max date is today                         | Image of when min date is birthdate and max date is today                                  |Image of when max date is today five days beyond                                  |
| ---------------------------- | -------------------------- | ----------------------------------- |
| ![minvaluedatepicker](https://github.com/opensrp/fhircore/assets/60472476/5dd21d65-24de-4f55-b5ec-7ddd7fbd1fb3)|![pdobmindate](https://github.com/opensrp/fhircore/assets/60472476/94b1d682-9b8f-4196-990f-dc617695c0b3)|
![maxdate_5days](https://github.com/opensrp/fhircore/assets/60472476/0e034be7-df53-4c9f-b585-8f1baa5483aa)|

**Comment by ageryck** [comment]
@brandy-kay the first screenshot looks okay however it is not visible on the second kindly confirm it is restricted based on the patient birthdate queried through an expression and equally limits the max value as set. If yes then you can proceed to add some documentation about this.
