### ISSUE TITLE
Add a `ClientLocation.userAssignedLocation` config on the fhircore gradle.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3066]
**Keyword Definition**
- **Client** - An entity that has data collected against it (e.g. Family/Household, Family/Household member, Patient, Service Point or Product).
- **Client Location** - This term is used to refer to location(s) associated with the client.
    - This would mean the location where the family or family member lives, for the case of the SID (Summit Institute for Development) applications
    - This would mean the service point where data collected belongs to, for the case of EUSM (End User Supply Monitoring)
- **Sync Locations** - These are the locations used to filter the data to be synced to the application.

**Context**
- Sync by Client Location means getting all the resources that have a Client Location ID that is a child or equal to the user sync locations. 
- The Sync Locations will be part of the request parameters. These will be found on the `syncLocation` param. 
- This ticket is to add the ability to define how the `Client Location` sync strategy defines the `syncLocation`  param
    - If the `ClientLocation.userAssignedLocation == true` the mobile application does not need to generate the syncLocation params.  This will be handled by the FHIR Info Gateway as defined [here](https://github.com/opensrp/fhircore/issues/3052) 
- This config should also be set to `true` by default 

**Technical Description of enhancement**
- [ ] Update the gradle to add the `ClientLocation.userAssignedLocation` config
    - [ ] This should be added to the flavours configs since each flavour can define its own value.  

**Acceptance criteria**
- [ ] Fhircore flavours should be able to define the `ClientLocation.userAssignedLocation` on their own

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
Let's discuss this a bit more

**Comment by dubdabasoduba** [comment]
@pld closing this since we do not need it any more after our discussion
