### ISSUE TITLE
Update fhircore to add `syncLocation` params to all GET requests when using the sync by `Client Location` sync strategy

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3067]
**Keyword Definition**
- **Client** - An entity that has data collected against it (e.g. Family/Household, Family/Household member, Patient, Service Point or Product).
- **Client Location** - This term is used to refer to location(s) associated with the client.
    - This would mean the location where the family or family member lives, for the case of the SID (Summit Institute for Development) applications
    - This would mean the service point where the data collected belongs, for the case of EUSM (End User Supply Monitoring)
- **Sync Locations** - These are the locations used to filter the data to be synced to the application.

**Context**
- Sync by Client Location means getting all the resources that have a Client Location ID that is a child or equal to the user sync locations. 

- The Sync Locations will be part of the request parameters. These will be found on the `syncLocation` param. 
- This ticket is to add the ability to create and add the `syncLocation` param to the GET request from the data stored in the secure shared prefs on the app

**Technical Description of enhancement**
- [ ] If the value of the `ClientLocation.userAssignedLocation` config is `false` and the Sync Strategy for the apps is `Client Location`
    - [ ] Generated request params based on the information stored in the `syncLocation` key on the secure shared prefs. 
    - [ ] Add this request params to every GET request on the app. Data fetched via the configs should be exempted from operation

**Acceptance criteria**
- [ ] All GET requests from fhircore should have the `syncLocation` param if `ClientLocation.userAssignedLocation == false` and the app sync strategy is `Client Location`

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by pld** [comment]
`Client Location` seems misleading as the sync strategy, because if `ClientLocation.userAssignedLocation == false` then isn't your' sync strategy not the client location?

But instead, more generally, the strategy is by location? And, even if it isn't true, can we still send the `syncLocation` param, but have it be the logged in users assigned location, to match how it works now?
