### ISSUE TITLE
Implement a configurable location selector UI

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3068]
On the Android app, users will be allowed to select different locations including the ones they are not assigned to. These locations will be selected from the location selector. The location selector should be accessible from the side menu or the map view during initial login (no locations selected). 
- This accessibility flow should be added as a configuration so that this UI can be launched from somewhere else e.g the Settings, Profile or Register pages

**Business requirements**
- The ability for users to select or deselect a location they would like to visit during a field visit. 

**Functional requirements**
- [ ] The user can access the location selector from the side menu by tapping on the set location. 
![image](https://github.com/onaio/fhir-resources/assets/58034047/6f52c6ae-c0fa-477f-ac36-1b66ecf52fab)
- [ ] User can access the location selector from the map view by tapping on set location on initial login. 
![image](https://github.com/onaio/fhir-resources/assets/58034047/739b42d5-acf7-42e7-91cf-0058da92bfc3)
- [ ] User can access the location selector from the register view by tapping on the set location (initial login).
![image](https://github.com/onaio/fhir-resources/assets/58034047/a34c4ddc-0ed0-4135-9515-2102e4421172)
- [ ] Once the user lands on the location selector, the location hierarchy is displayed and they can select the location where the service points they want to visit are located. 
- [ ] User can select more than 1 location. 
- [ ] User can also use the search bar on the page to filter a location. When the user types in a few letters, the locations with those letters are shown. The finer /more detailed the search, the finer the results. 
- [ ] Once the locations are selected, sync is triggered by clicking the **Sync Data** button

**Technical Requirements**
- [ ] The hierarchy displayed on this view should be configurable i.e
    - [ ] Content authors can define up to what node of the location hierarchy should be shown here. 
    - [ ] Add the ability to launch this bottom sheet like any other workflow since it can be launched from multiple pages.
- [ ] All the selected locations should be stored in the secure shared prefs. 
    - [ ] If this feature is enabled and no selected locations can be found on the secure shared prefs, sync should be paused until the locations are selected and the **Sync Data** button is clicked.
    - [ ] If the secure shared prefs has an entry, sync should work as defined here https://github.com/opensrp/fhircore/issues/3067
- [ ] The search on this view should only search through the content of the tree view on this screen.

**Acceptance criteria**
- [ ] All functions highlighted in the functional requirements are working correctly. 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by dubdabasoduba** [comment]
Updated location selection screenshot

![Side menu 1 1 - Side menu 1 1 - bottom sheet (1)](https://github.com/opensrp/fhircore/assets/4817531/55fe6343-36e2-4602-92fd-2eedaf4a2100)

@ellykits raised an interesting observation on the linked screenshot. Right now based on how the select and drill down icons are placed shows kinda of shows that the user has to select and then drill down.  

would it make more sense to have the selection checkbox at the start? like in the screenshot below

![Multi Level Select](https://github.com/opensrp/fhircore/assets/4817531/aa96c127-19b2-4693-a4d4-7b9658352431)

cc: @HenryRae  @rowo

**Comment by rowo** [comment]
I'm wary about both solutions on mobile screens because of the small area to tap for the checkboxes and arrows. For our users, I'd prefer the whole line as a tappable button that can either expand or select the line item. 

However, I'm not sure about the exact solution though. I wonder if adding a "select all" option to lists with children could work. The problem is any choice with children will not be obviously selected (for example Lavington, if you select Nairobi). 

@HenryRae any ideas?

**Comment by HenryRae** [comment]
The touch areas could be manageable to a minimum of 48px, @ellykits you can let me know if this is possible with our current tech.

The icons can be swapped, what is proposed by Elly is the most common UX.

I've updated the design and also tried to cater for other scenarios like search and selecting of location. See below
![image](https://github.com/opensrp/fhircore/assets/31955469/97d48fe4-8a02-4fdc-8f7a-e30de214c55c)

**Comment by ellykits** [comment]
> The touch areas could be manageable to a minimum of 48px, @ellykits you can let me know if this is possible with our current tech.

This should be possible @HenryRae
