### ISSUE TITLE
Input validation   for data types and also mandatory/optional fields based on the questionnaire

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#311]
- [x] Support minValue maxValue in the SDC library [#164](https://github.com/google/android-fhir/issues/164)
- [ ] Create validation APIs for the UI widgets [#388](https://github.com/google/android-fhir/issues/388)
- [ ] Test HAPI's profile validation on Android [#383](https://github.com/google/android-fhir/issues/383)
- [ ] Validate details as entered by the user for data types and also mandatory/optional fields based on the questionnaire
- [ ] If there is an error, prompt the user with an error notification or with a success notification upon successful submission
Some more notes here  - http://build.fhir.org/ig/HL7/sdc/behavior.html
