### ISSUE TITLE
Advanced Register filtering based on the user selected location

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3114]
**Describe the feature request.**
- This ticket https://github.com/opensrp/fhircore/issues/3068 is adding the ability for users to sync data for locations they select. 
- We would like to have a 2nd use case for the location selection UI. This is to filter the data shown on the registers and maps (for applications that use maps)
- The idea is to reduce to amount of data shown on the registers based on the locations that have been selected. e.g if we have synced data for 4 locations and we deselect 3 the register should only show the data for the 1 selected location 
![image](https://github.com/opensrp/fhircore/assets/31955469/97d48fe4-8a02-4fdc-8f7a-e30de214c55c)

**Acceptance criteria**
- [ ] Only the data for the selected locations should be shown on the register or maps
- [ ] This filtering functionality should be configurable e.g 
    - [ ] Have the ability to turn it on and off
    - [ ] Have the ability to use the same UI for Sync and for data filtering

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by dubdabasoduba** [comment]
@ellykits I think we can also achieve the filtering by using cascading selectable dropdowns or checkboxes. This way we still reuse the Questionnaire approach in advanced filtering. What are your thoughts?

**Comment by ellykits** [comment]
If it is possible to render the UI via Questionnaire, then use the answers in data queries that should be an easier option.

**Comment by pld** [comment]
OK, then in that case would you define the UI via a content, and do we have a new config file for this?

**Comment by dubdabasoduba** [comment]
> If it is possible to render the UI via Questionnaire, then use the answers in data queries that should be an easier option.

@ellykits  what do you mean when you say the UI?  Does it mean the location hierarchy select widget or does it mean the cascading dropdowns

**Comment by ellykits** [comment]
> > If it is possible to render the UI via Questionnaire, then use the answers in data queries that should be an easier option.
> 
> @ellykits what do you mean when you say the UI? Does it mean the location hierarchy select widget or does it mean the cascading dropdowns

@dubdabasoduba I meant the location hierarchy select widget. The default cascading dropdowns in Questionnaire can be used.

**Comment by ellykits** [comment]
> OK, then in that case would you define the UI via a content, and do we have a new config file for this?

@pld Yes we have configurations for this.
