### ISSUE TITLE
Add the ability to define the default view between the register and the map view

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3138]
**Describe the feature request.**
- We would like to add the ability to define a default view between the Register and Map view. 

**Acceptance criteria**
- [x] Add the ability to define the default view while defining the navigation drawer on. 

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by AnnieMungai** [comment]
@Mstjamush this is ready for QA on EUSM.

**Comment by ndegwamartin** [comment]
Marking as complete following Geowidget PR merge - https://github.com/opensrp/fhircore/pull/3020

**Comment by AnnieMungai** [comment]
**Acceptance Criteria**
- [ ] The app navigates user to the map view upon logging.
- [ ] User can switch between the map view and the register view by tapping the icon on the top navigation drawer. 
- [ ] While on the register view, user can change to map view by tapping on the left icon on the top navigation drawer.
