### ISSUE TITLE
Add the ability to define the bottomsheet that is displayed when a location point is clicked.

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3140]
**Describe the feature request.**
- With the addition of the Geo-Widget on OpenSRP 2, we would like to be able to navigate from the map to the Location Profile.  
- This redirect after an icons on the map has been clicked can happen in 2 routes
    - **Route 1**: Clicking on the icons on the maps redirects to the Profile directly
    - **Route 2**: Clicking on the icons on the map launches a configurable bottom sheet that allows the users to view summary data of the location item. 
- This ticket is to add the ability to display and configure the bottom sheet on the **Route 2** 

**Acceptance criteria**
- [x] Content authors should be able to define which route the icon click should take.  
- [x] A configurable bottom sheet should be launched if **Route 2** above is selected. This bottom sheet should have the following configurations
    - [x] Ability to fetch data,  and define FHIR core widgets to display the data
    - [x] Ability to add buttons that allow redirecting to other views on the app

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by ellykits** [comment]
Any feedback on the QA for this issue? @AnnieMungai @Mstjamush?

**Comment by AnnieMungai** [comment]
@Mstjamush - linked ticket: https://github.com/onaio/fhir-resources/issues/2955

**Comment by AnnieMungai** [comment]
Passed QA on the resources repo.
