### ISSUE TITLE
Configure PDF Generation

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#3235]
**Describe the feature request.**
Using configuration, connect the HTML structure to be used to generate PDF together with the questionnaire that intends to use that HTML structure.

**Additional context**
N/A

**Acceptance criteria**
A check list of all things to verify once the implementation by the engineer is complete
- [x] HTML is saved as Binary resource
- [x] Create a property in the config to accept the Binary ID of the HTML structure
- [x] Create a button action type in the config that will trigger the PDF generation

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Go to a profile
2. Tap the button that will trigger the PDF generation
3. App shows a print manager dialog
4. Tap save as PDF

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
1. Safe the HTML as a Binary resource
2. Create a rule in the profile, if the taskQuestionnaireId is X then return that Binary resource ID
3. Pass that rule that contains the Binary resource ID to the questionnaireConfig's property, probably called pdfStructureId
5. In the code, use that ID to get the HTML Binary resource
6. Use the HTML

**Comment by pld** [comment]
looks great!
