### ISSUE TITLE
Populate HTML Content with QuestionnaireResponse Data

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#3257]
**Describe the feature request.**
Create a feature that's able to:
- Hide UI elements if there is no answer in the referred link id
- Populate answers as a list or a single value in the HTML
- Populate the submitted date in the HTML content

**Additional context**
I was initially thinking to use configuration + rules engine, but I feel it will take much more time since the implementation of those 2 need to be refactored first before it can be used by this feature. So, that's why I create a new class then do some simple string manipulation to the html.

**Acceptance criteria**
- [x] Hide UI elements if there is no answer in the referred link id
 ```
If the answer is empty:
"@is-not-empty('link-id')<p>Text</p>@is-not-empty" -> (nothing)
     
If the answer is not empty:
"@is-not-empty('link-id')<p>Text</p>@is-not-empty" -> <p>Text</p>
```

- [x] Populate answers as a list or a single value in the HTML

```
"</ul>@answer-as-list('link-id')</ul>" -> <ul><li>answer 1</li><li>answer 2</li></ul>
```

```
"<p>@answer('link-id')</p>" -> <p>(the answer)</p>
     
"<p>@answer('link-id')</p>" -> <p>14-May-2024</p> (if it's a date type)
     
"<p>@answer('link-id','MMMM d, yyyy')</p>" -> <p>May 14, 2024</p>
```

- [x] Populate the submitted date in the HTML content
```
"@submitted-date" -> 14-May-2024

"@submitted-date('MMMM d, yyyy')" -> May 14, 2024
```

**Area path**
Run the test cases, we couldn't directly use this feature in the app until ticket https://github.com/opensrp/fhircore/issues/3235 is complete.

**Implementation plan (For Engineers)**
1. Create HtmlPopulator class
2. Create populateHtml() method, it will accept a raw HTML string and return the populated HTML string with the data from the QuestionnaireResponse
3. Create these methods: processIsNotEmpty(), populateAnswerAsList(), populateAnswer(), populateSubmittedDate(). These will handle specific tasks such as hiding UI elements, populating answers as list items or single values, and populating the submitted date in the HTML content, mainly using string manipulation by finding the tags for each functionality, then replacing it with the correct string/answer.

**Comment by ellykits** [comment]
@FikriMilano Is the question displayed against the answer or just the link id?

**Comment by ellykits** [comment]
My question was whether we also display the question, as in question and answer response.

**Comment by pld** [comment]
Let's have those loops cleaned up before merge, moving to sprint 11
