### ISSUE TITLE
Updating Sync button on the Navigation menu based on Sync Status

### ISSUE THREAD

**Issue by Gental-Giant** [opensrp/fhircore#3294]
**Describe the feature request.**
We would like to update the UI/UX for manual sync. This would be done by updating the UI to allow users to know when they have unsynced data, and track sync progress and final status.

**Additional context**
- [ ]  Update the sync button as shown below:
<img src= "https://github.com/opensrp/fhircore/assets/52551080/2d2703c6-4df9-4195-8fed-7088c11ebba9" width="620" height="520">

**Acceptance criteria**

- [ ] When there are unsynced data, the sync button on the side navigation has a warning icon and changes colour to yellow as shown in the image (b).
- [ ] When we do not have unsynced data, (all resources have successfully been synced to the server), the sync button should appear as shown in the image (a).
- [ ] The time last successful sync was  conducted is also shown.

**Area path**
1. Login to the app
2. Open the Navigation bar
3. If there is no unsynced data, sync button should appear as on image (a)
4. If there are unsynced data, the sync button should appear as on image (b)

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _checklist_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by AnnieMungai** [comment]
Tested with https://github.com/onaio/fhir-resources/releases/tag/v2.0.0-opensrp-eusm-rc5
LGTM!
