### ISSUE TITLE
Add (or use) QR code widget in Questionnaire

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#3350]
**Describe the feature request.**

- Extend the [Android FHIR SDK barcode/QR code reading widget](https://github.com/google/android-fhir/blob/master/contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/LiveBarcodeScanningFragment.kt)

1. In Questionnaires support setting the field type to ["barcode"](https://github.com/google/android-fhir/blob/master/contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/BarCodeReaderViewHolderFactory.kt), this renders as the QR code widget
1. QR code fields show as a text entry with a QR code icon to the right of the input field
1. When you tap the icon load a QR code reader, start with the [ML Kit barcode reader](https://developers.google.com/ml-kit/vision/barcode-scanning/android), note in comments if there are challenges and we need to pursue alternatives
1. After successfully reading a QR code, fill the field with the string read from the QR code
1. The field is read-only, it cannot be edited except by text received from the QR code reader
2. Extend the [Questionnaire docs](https://docs.opensrp.io/engineering/app/configuring/config-types/forms/questionnaire) to add this field type

**Additional context**

<img width="2619" alt="Screenshot 2024-06-25 at 10 41 40 AM" src="https://github.com/opensrp/fhircore/assets/50706/0fc7085a-d6ae-4fa0-acd6-e8e74d99f0da">

- [Figma designs and discussion](https://www.figma.com/board/AtMDYIlI1hrrSsuam7lg4H/QR-code-scanning-high-level-use-cases-(Copy)?node-id=2031-153&t=eBjkPJ8FC9hZepCc-0)

**Acceptance criteria**
- [x] `qr-code` type in Questionnaire renders the field as a QR code
- [x] QR code field text cannot be edited manually
- [x] Clicking QR code icon to right of field loads QR code scanner
- [x] Scanned QR code populates field
- [x] If field populated already, scanning a new QR code populates the field
- [x] On save, text stored in QR code field is stored in a QuestionnaireResponse

**Area path**

Write a Questionnaire that contains a `qr-code` type field and integrate the Questionnaire into the app

1. Login to the app
7. Launch the Questionnaire with a QR code
8. Click on the field with the QR code icon
9. Read a QR code
10. Submit the Questionnaire
11. Sync the device
12. Inspect the QuestionnaireResponse stored on the server and device, validate that the QR code data is equivalent

**Implementation plan (For Engineers)**

- Implement as a widget for QR codes
- The widget uses [ML Kit barcode reader](https://developers.google.com/ml-kit/vision/barcode-scanning/android) to read QR codes

**Comment by pld** [comment]
K, looks like we're missing a view? Do we need to pull code for the widget in? This is in contrib, not the releases, https://github.com/google/android-fhir/blob/master/contrib/barcode/src/main/java/com/google/android/fhir/datacapture/contrib/views/barcode/mlkit/md/LiveBarcodeScanningFragment.kt
