### ISSUE TITLE
Add search by QR code option to register search field

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#3351]
**Describe the feature request.**
1. Add a binary option for `search-by-barcode` to the register config
    1. it is not required, and default is False
2. When search-by-barcode is True
    5. Show a QR code icon on the right side of the search field in the register
    6. On-click launch the QR code reader
        1. Execute the same code as was used for the barcode reader widget
    8. After reading a QR code
        1.  Follow the code-path as if the string read from the QR code had been entered in the search field
        1. show the results in the register
        2. place the value read from the QR code as the text in the search query field
3. Update [register docs](https://docs.opensrp.io/engineering/app/configuring/config-types/register) to add a description of this option

**Additional context**

<img width="619" alt="Screenshot 2024-06-25 at 12 23 03 PM" src="https://github.com/opensrp/fhircore/assets/50706/35441156-d52e-4a6e-b445-81ec8e8694b7">

- [Figma designs and discussion](https://www.figma.com/board/AtMDYIlI1hrrSsuam7lg4H/QR-code-scanning-high-level-use-cases-(Copy)?node-id=2031-153&t=eBjkPJ8FC9hZepCc-0)

**Acceptance criteria**
- [ ] When `search-by-qr-code` is not set, the QR code icon does not show
- [ ] When `search-by-qr-code` is False, the QR code icon does not show
- [ ] When `search-by-qr-code` is True
    - [ ] The QR code icon does show
- [ ] When clicking the QR code icon the QR code reader loads
- [ ] After reading a QR code it
    - [ ] Goes to the register and shows the QR code in the search field and no results if there are no results
    - [ ] Goes to the register and shows the QR code in the search field and multiple results if there are >=1 results

**Area path**

1. Modify the register config to enable the QR code reader
2. Open the register
4. Read QR codes using the button in the register search bar

**Implementation plan (For Engineers)**

- [ ] Use the [ML Kit barcode reader](https://developers.google.com/ml-kit/vision/barcode-scanning/android) to read QR codes
    - [ ] Isolate the QR code loading into its own module so in the feature we can launch the QR code from places other than the search bar
- [ ] Figure out how to encode the search query to use based on the result returned from reading a QR code

**Comment by pld** [comment]
nb: this is not blocked by https://github.com/ona-health/hisp-wdf-fhir-resources/issues/376, but it makes sense to do that first so we have experience integrating QR codes

**Comment by LZRS** [comment]
Closed in https://github.com/opensrp/fhircore/pull/3367
