### ISSUE TITLE
On reading QR go directly to profile if a single result returned

### ISSUE THREAD

**Issue by pld** [opensrp/fhircore#3361]
**Describe the feature request.**
Extend the search by barcode register option to support
- [optional] profile-launch to define the profile to open if a single result is returned

After reading a QR code
1. If profile-launch is defined and there is 1 result, open the result using the profile defined in profile-launch
1. If there are 0 or >=2 results
    1. show the results in the register
    1. place the value read from the QR code as the text in the search query field

- Update [register docs](https://docs.opensrp.io/engineering/app/configuring/config-types/register) to add a description of this option

**Additional context**
Blocked by https://github.com/opensrp/fhircore/issues/3351

**Acceptance criteria**
- [ ] After reading a QR code it
    - [ ] Goes to the profile of whatever is specified in the profile-launch field with that QR code if there is one result
    - [ ] Goes to the register and shows the QR code in the search field and no results if there are no results
    - [ ] Goes to the register and shows the QR code in the search field and multiple results if there are >1 results

**Area path**
1. Modify the register config to enable the QR code reader and add a profile-launch key and value
2. Open the register
4. Read QR codes using the button in the register search bar

**Implementation plan (For Engineers)**
- [ ] Figure out how to define the profile to load when the search returns a single result

**Comment by ellykits** [comment]
The new properties -> `RegisterContentConfig.searchByQrCode` and `RegisterConfiguration.onSearchByQrResultActions`
```kotlin 

@Serializable
data class RegisterContentConfig(
  val separator: String? = null,
  val display: String? = null,
  val rules: List<RuleConfig>? = null,
  val visible: Boolean? = null,
  val computedRules: List<String>? = null,
  val searchByQrCode: Boolean? = null
)


// RegisterConfiguration

@Serializable
data class RegisterConfiguration(
  override var appId: String,
  override var configType: String = ConfigType.Register.name,
  val id: String,
  val registerTitle: String? = null,
  val fhirResource: FhirResourceConfig,
  val secondaryResources: List<FhirResourceConfig>? = null,
  val searchBar: RegisterContentConfig? = null,
  val registerCard: RegisterCardConfig = RegisterCardConfig(),
  val fabActions: List<NavigationMenuConfig> = emptyList(),
  val noResults: NoResultsConfig? = null,
  val pageSize: Int = 10,
  val activeResourceFilters: List<ActiveResourceFilterConfig> =
    listOf(
      ActiveResourceFilterConfig(resourceType = ResourceType.Patient, active = true),
      ActiveResourceFilterConfig(resourceType = ResourceType.Group, active = true),
    ),
  val configRules: List<RuleConfig>? = null,
  val registerFilter: RegisterFilterConfig? = null,
  val filterDataByRelatedEntityLocation: Boolean = false,
  val topScreenSection: TopScreenSectionConfig? = null,
  val onSearchByQrResultActions: List<ActionConfig>? = null
) : Configuration()
```

**Comment by pld** [comment]
> The new properties -> `RegisterContentConfig.searchByQrCode` and `RegisterConfiguration.onSearchByQrResultActions`
> 
> ```kotlin
> @Serializable
> data class RegisterContentConfig(
>   val separator: String? = null,
>   val display: String? = null,
>   val rules: List<RuleConfig>? = null,
>   val visible: Boolean? = null,
>   val computedRules: List<String>? = null,
>   val searchByQrCode: Boolean? = null
> )
> 
> 
> // RegisterConfiguration
> 
> @Serializable
> data class RegisterConfiguration(
>   override var appId: String,
>   override var configType: String = ConfigType.Register.name,
>   val id: String,
>   val registerTitle: String? = null,
>   val fhirResource: FhirResourceConfig,
>   val secondaryResources: List<FhirResourceConfig>? = null,
>   val searchBar: RegisterContentConfig? = null,
>   val registerCard: RegisterCardConfig = RegisterCardConfig(),
>   val fabActions: List<NavigationMenuConfig> = emptyList(),
>   val noResults: NoResultsConfig? = null,
>   val pageSize: Int = 10,
>   val activeResourceFilters: List<ActiveResourceFilterConfig> =
>     listOf(
>       ActiveResourceFilterConfig(resourceType = ResourceType.Patient, active = true),
>       ActiveResourceFilterConfig(resourceType = ResourceType.Group, active = true),
>     ),
>   val configRules: List<RuleConfig>? = null,
>   val registerFilter: RegisterFilterConfig? = null,
>   val filterDataByRelatedEntityLocation: Boolean = false,
>   val topScreenSection: TopScreenSectionConfig? = null,
>   val onSearchByQrResultActions: List<ActionConfig>? = null
> ) : Configuration()
> ```

Some questions:

1. Can we rename this to be clear it is only when a single result is returned?

`onSearchByQrSingleResultAction: ActionConfig? = null`

2. Also, can you explain why it needs a list? It is not clear to me how we could perform more than 1 action

**Comment by ellykits** [comment]
> Some questions:

> 1. Can we rename this to be clear it is only when a single result is returned?
onSearchByQrSingleResultAction: ActionConfig? = null

> 2. Also, can you explain why it needs a list? It is not clear to me how we could perform more than 1 action

On the first question, I agree with the new name it's more descriptive. On the second question, conventionally we have been providing a list of actions, in anticipation that an event would trigger more than one workflow (which might be the case for particular use cases; but not on this one).

**Comment by pld** [comment]
On the list of actions, I'm strictly against that but I want to understand the use case, can you give some example use cases?

**Comment by ellykits** [comment]
An example use case is when you'd want to copy the text extracted by the barcode scanner to the clipboard via the COPY_TEXT action and then launch the profile via the LAUNCH_PROFILE action.

**Comment by pld** [comment]
OK got it, makes sense

**Comment by LZRS** [comment]
Closed by https://github.com/opensrp/fhircore/pull/3367
