### ISSUE TITLE
Checklist for the Covax Demo app for the WHO call  - July 12th 2021

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#343]
Here is a checklist of the items to check for while packaging the APK for this demo 
**Views**
- [x] Patient list (Record vaccine, Vaccine 1, Overdue, Fully vaccinated)  - Styling of vaccine status in patient list and profile view #224
- [x] Patient Registration #19
- [x] Barcode scanning for patient enrollment  - [COVAX demo app] Build barcode scanner #127
- [x] Patient search  - name (First name, Last name) - Patient search #20, Filter and pagination for search #54, On patient search if patient not found, display error message and show Register patient button #231
- [x] Filter patients whose second dose is overdue #176
- [x] Profile view #22 - View Regisrtation date, Vaccine 1 date , Overdue (date), Fully vacinnated  - 
- [x] Corect dates for Vaccination (Profile view & Patient List) #195

**Vaccination workflow**
1. When I open the app I should see a patent list with different statuses (Record vaccine, Vaccine 1, Overdue, Fully vaccinated)
2. I can be able to enrol a patient through barcode scanning or add a patient by clicking the registration button 
3. I can be able to search for a patient via the search bar or barcode scanning (barcoded id to be provided)
4. When you record the 1st vaccine - add the date it was received 
5. For overdue use 12 weeks 
6. When you add dose 2 update the date and change status to fully vaccinated 
7. When 12 weeks laps  - change status to overdue 
8. When fully vaccinated change status to Full Vaccinated  
More of this here #421 

**Most Important**

- [x] Patient saved to HAPI FHIR server e.g https://fhir.labs.smartregister.org/fhir/Patient/Cook
- [x] Immunization resource saved with Vaccination details  - https://fhir.labs.smartregister.org/fhir/Immunization/59bbd3b5-0673-4b23-8e20-56286e012025
- [x] Full Immunization records https://fhir.labs.smartregister.org/fhir/Immunization?_pretty=true

**See mocks attached** 

<img width="213" alt="Screen Shot 2021-06-03 at 12 30 13 PM" src="https://user-images.githubusercontent.com/4540684/123924525-b92b3000-d992-11eb-8397-83d4abe96f77.png">

<img width="213" alt="Screen Shot 2021-06-03 at 12 30 13 PM" src="https://user-images.githubusercontent.com/4540684/123924594-c9dba600-d992-11eb-831c-c8c8bdd4c8d3.png">

<img width="213" alt="Screen Shot 2021-06-03 at 12 30 13 PM" src="https://user-images.githubusercontent.com/4540684/123924625-d2cc7780-d992-11eb-844e-2ba2ba844aa9.png">

<img width="845" alt="Screen Shot 2021-06-03 at 12 29 58 PM" src="https://user-images.githubusercontent.com/4540684/120622503-8a8b6980-c467-11eb-99a9-4026ad66e622.png">

**Comment by rkodev** [comment]
Code Clean-Up steps

- [ ] 

- [ ]  Update search and count query to use SDK (2 hrs)
- [ ]  Cherry-pick the main register status changes to the master branch (2 hrs)
- [ ]  Create a Facade to hide all hard corded implementations related implementation (1 day)
- [ ]  Cherry Pick / Implement the scan bar code with revised code sdk (4 hrs)
- [ ]  Add tests (1 day)

**Comment by f-odhiambo** [comment]
Closing this ticket for now as all items have been fulfilled. Will create new tickets if required on any follow-up item 
CC @ndegwamartin
