### ISSUE TITLE
Check if Questionnaire has it's pair of QR in the HtmlPopulator class

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#3490]
**Describe the feature request.**
A need of more precise way to check if Questionnaire has been submitted i.e. the QR of that Q exists in the context of HtmlPopulator class. Previously, we tried to check if the item answer inside a QR has value, but that's feels less direct.

**Additional context**
N/A

**Acceptance criteria**
- [ ] A new html tag has been added to the HtmlPopulator class to check if the corresponding QR of a Questionnaire exists

**Area path to review**
1. Define an Html with the new tag
2. Pass QRs to the HtmlPopulator class
3. Process the html
4. If QR exists, the content inside the tag should be display, otherwise it shall be hidden

**Implementation plan (For Engineers)**
- [ ] Define a list in the HtmlPopulator class to keep the questionnaire ids of the passed QRs
- [ ] Add a new function and tag to check if the questionnaire id exists from that list
