### ISSUE TITLE
Define SDK summary mode in QuestionnaireConfig

### ISSUE THREAD

**Issue by FikriMilano** [opensrp/fhircore#3494]
**Describe the feature request.**
Add a new property in the questionnaire config, to allow to use this SDK API

https://github.com/google/android-fhir/blob/6ad0a6751fea3e53d9e2be327ca205cca1112af8/datacapture/src/main/java/com/google/android/fhir/datacapture/QuestionnaireFragment.kt#L347-L351

**Additional context**
- In SDK, they call this `read-only` mode, BUT, we also already have read-only mode, PLUS the `read-only` mode from SDK looks more like summary mode (I would call it). So, to make it not confusing, we will name this `summary` mode in OpenSRP 2.
- Our `read-only` mode, is a disabled fields that contains text
- The SDK's `read-only` mode i.e. `summary` mode, is purely texts (the fields are changed to texts only)

[336119332-a874d74f-91e2-4c0c-950a-f364e333d7ea.webm](https://github.com/user-attachments/assets/a10fea14-8d24-4195-80ad-eb284d8654d4)
 
**Acceptance criteria**
- [ ] Should be able to use the read-only mode from SDK

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Define a QuestionnaireConfig
2. Set the SDK summary mode via QuestionnaireConfig to true
3. Start the app
4. Open the Questionnaire

**Implementation plan (For Engineers)**
- [ ] Add a new variable for summary-mode in the QuestionnaireConfig
- [ ] Pass that variable to the QuestionnaireBuilder

**Comment by ellykits** [comment]
@dubdabasoduba @f-odhiambo Do you have any comment on this? @FikriMilano Has explained why a new property is necessary. It would be great to pick a name that would not cause any confusion.
