### ISSUE TITLE
[UI/UX] Add Icon to Profile and Overflow menu 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#3512]
**Description** 
Add Icon to Profile and Overflow menu 

**Screenshot**
![image](https://github.com/user-attachments/assets/8c690184-4280-4b7e-bd4d-da153de8c269)

**Comment by f-odhiambo** [comment]
**TODO**

- [ ] - Update the user profiles user details card vie to be able to have a placeholder for an image 
- [ ] - Get the image from the assets folder and update the compose to support it (dimensions)
- [ ] - Configure the rule to show and hide the icon based on the user details provided interpreted  by the rules engine

**Comment by f-odhiambo** [comment]
@HenryRae Kindly provide an SVG image for this

**Comment by ellykits** [comment]
Can you share a sample screen with an image?

**Comment by ellykits** [comment]
It's possible to use configurations to provide the images for the overflow menu items.

**Comment by ellykits** [comment]
I'd need to confirm the position.

**Comment by f-odhiambo** [comment]
Icon config works but need to check wether their is property to move is to the right and not left

```
"icon": {
                "type": "local",
                "reference": "ic_household"
            },
```

![image](https://github.com/user-attachments/assets/7eee4b9d-c488-477c-b637-bcd266f4b71a)

**Comment by f-odhiambo** [comment]
This class can be used to create a config to add image on profile https://github.com/opensrp/fhircore/blob/main/android/quest/src/main/java/org/smartregister/fhircore/quest/ui/shared/components/Image.kt

**Comment by pld** [comment]
is the issue that you can't specify which side of the text to add the image?

**Comment by HenryRae** [comment]
@f-odhiambo here's a [link](https://www.figma.com/design/d1VJsrJPinT0Qce3PEbH2u/PATH-GIZ-EIR?node-id=1057-12317&m=dev) to the designs, you can export SVG direct

**Comment by ssykx4** [comment]
Is this issue still needed to be sloved? I think I could help!

**Comment by ellykits** [comment]
Sure @ssykx4, please go ahead
