### ISSUE TITLE
[Roadmap] FHIRCore Milestone 8

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#352]
At the end of this milestone, we expect to have accomplished 80% of the below-listed items 

**WIP to complete** 
- [ ] Define and scope  Single APK Approach #296 & #379
- [ ] Remining tasks in [Sprint 8](https://github.com/opensrp/fhircore/milestone/16)

**Updated Covax app**
- [ ] Code cleanup & merge complete
- [ ] APK to be delivered   = Covax Demo App for WHO before the July 12th demo  - #343
- [ ] Implement any feedback, bugs or features to support the creation of the Smart Vaccine Certificate 

**CHW/ANC App**
Based on the milestone -  [CHW ANC App MVP](https://github.com/opensrp/fhircore/milestone/17)
- [x] Auth  - #272 & #282
- [x] App version ID  - #342
- [ ] Sync configs resources based on creds - To be done once #296 is complete 
- [ ] Family/Household ( Head of family & members) registration - #276 
- [ ] Patient registration  (to be configured based on the CHW Questionnaire) - #276
- [x]  Patient profile (to be configured based on the requirements)   -  #217
- [ ] Family profile/Register -  #217

**G6PD**
- [ ] Requirments validation and scoping done
- [ ] Clinical workflow validation workshop 
- [ ] Revised designs
- [ ] Updated project plan & budget
- [ ] Revisewd LOEs for the different work package items.

If above is approved move to :
- [x] Auth  - #272 & #282
- [x] App version ID  - #342
- [ ] Sync configs resources based on creds - To be done once #296 is complete 
- [ ] Patient registration  (to be configured based on the G6PD Questionnaire) 
- [ ] Patient profile (to be configured based on the requirements) 
- [ ] Manual entry patient's observation details

**mADX**
- [x] Test and implement measure reporting #177 & #310
- [x] Auth  - #272 & #282
- [x] App version ID  - #342
- [ ] Sync configs resources based on creds - To be done once #296 is complete 
- [ ] Patient registration  (to be configured based on the mADX Questionnaire)
- [ ]  Patient profile (to be configured based on the requirements)  
- [ ] Test Measure reporting from [server side](https://github.com/DBCG/cqf-ruler/blob/5f50c55bf17d1b1afe15c37152647c333bed8eeb/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L145) based on DBCG cqf-ruler
