### ISSUE TITLE
Update the GeoWidget Topbar to add the filter Icon next the Navigate to register one

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3565]
**Describe the feature request.**
- We would like to update the GeoWidget module to add a filter button next to the navigate to register one.  
- This button should have the following properties
   - Be configurable i.e can be hidden and shown by changing configs
   - Can launch questionnaires
   - Can launch the multi-select widget 

**Additional context**
- Due to the performance issues we are facing on the maps we would like to decouple the filtering of data on the maps from the multi-select widget used to determine what data to sync.  
- We would then move the filtering to a multi-select launched from the filtering icon described above. 

**Acceptance criteria**
- [ ] Be able to show a filter icon on the geowidget toolbar
- [ ] This icon should be configurable as defined above
- [ ] This widget should be able to launch the workflows defined above

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by AnnieMungai** [comment]
EUSM v.2.0.0.RC12
LGTM!
