### ISSUE TITLE
Filter content referenced on the Composition or IG using the `_lastUpdated` during download

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3580]
**Describe the feature request.**
- Currently, the configurations are re-downloaded every time a user logs in with their **_username_** and **_password_**. While this ensures we fetch updated configurations, it also results in re-downloading content that hasn’t changed, impacting sync time during subsequent syncs.
- This ticket aims to introduce a **_`lastConfigSync`_** timestamp, which will work alongside the **_`_lastUpdated`_** property on FHIR resources.
    - The **_`lastConfigSync`_** timestamp will have the following characteristics:
    - It will be updated each time the content download is completed successfully.
    - When available, it will be included in subsequent content requests after login.
    - It will be stored in the application’s shared preferences.

**Acceptance criteria**
- [ ] Always save the **_`lastConfigSync`_** timestamp everytime the configs are complete sync successfully
- [ ] Always attach the **_`lastConfigSync`_** to requests for content referenced on the Composition or IG
- [ ] Correctly store the **_`lastConfigSync`_** on the application share preferences

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_

**Comment by dubdabasoduba** [comment]
@ellykits @pld please review this

**Comment by pld** [comment]
One issue is how to set `lastConfigSync`, pretty sure we'd need to set this with a time that is provided by the remote server, since I believe that is also where the `_lastUpdated` is set.

Is there a way that the current server time is already being set back? It might be somewhat cludgy to add that as a returned value from the remote server.

An alternative approach would be to take the largest timestamp in `_lastUpdated` from the synced resources and use that as the `lastConfigSync` timestamp. Then we'd make sure we are using the same timezone/etc the server is. If we use this approach we'd have to make sure we use a strict `>` comparison, as opposed to a `>=` comparison.

**Comment by ndegwamartin** [comment]
> One issue is how to set `lastConfigSync`, pretty sure we'd need to set this with a time that is provided by the remote server, since I believe that is also where the `_lastUpdated` is set.
> 
> Is there a way that the current server time is already being set back? It might be somewhat cludgy to add that as a returned value from the remote server.
> 
> An alternative approach would be to take the largest timestamp in `_lastUpdated` from the synced resources and use that as the `lastConfigSync` timestamp. Then we'd make sure we are using the same timezone/etc the server is. If we use this approach we'd have to make sure we use a strict `>` comparison, as opposed to a `>=` comparison.

I believe this is how the FHIR SDK does it for the data FHIR resources - https://github.com/google/android-fhir/blob/master/engine/src/main/java/com/google/android/fhir/sync/download/ResourceParamsBasedDownloadWorkManager.kt#L115-L127

**Comment by dubdabasoduba** [comment]
@Aleem92 I just tested the HAPI API on the current version we use.  

`_lastUpdated` doesn't seem to work when performing GET `{{base_url}}/Composition/<uuid>` however it works on `{{base_url}}/Composition?_lastUpdated=<date>`


e.g https://{{base_url}}/fhir/Composition?_lastUpdated=gt2025-04-18

**Comment by dubdabasoduba** [comment]
@pld @ndegwamartin We might have to pause this until we test it on the latest version of HAPI. If still doesn't work then we close the ticket

**Comment by Aleem92** [comment]
> @Aleem92 I just tested the HAPI API on the current version we use.
> 
> `_lastUpdated` doesn't seem to work when performing GET `{{base_url}}/Composition/<uuid>` however it works on `{{base_url}}/Composition?_lastUpdated=<date>`
> 
> e.g https://{{base_url}}/fhir/Composition?_lastUpdated=gt2025-04-18

Thanks for 

> @Aleem92 I just tested the HAPI API on the current version we use.
> 
> `_lastUpdated` doesn't seem to work when performing GET `{{base_url}}/Composition/<uuid>` however it works on `{{base_url}}/Composition?_lastUpdated=<date>`
> 
> e.g https://{{base_url}}/fhir/Composition?_lastUpdated=gt2025-04-18

Thanks for confirming this, @dubdabasoduba. I had raised this issue regarding {{base_url}}/Binary/<uuid>?_lastUpdated=<date> not working as expected. I appreciate you taking the time to test and confirm the behavior on the ticket.

**Comment by Aleem92** [comment]
> Can you clarify, it works on Composition, but does not work for Binary?

I have also tested the {{base_url}}/Composition?identifier=<appid>&_lastUpdated=<date>. However, in either case, the _lastUpdated parameter does not work.

**Comment by pld** [comment]
Can we pass UUID as a search param?

**Comment by dubdabasoduba** [comment]
Just changing how we define the URLs might work. 

The tests above use the current servers. THe assumptions is this does not change on the new server versions
