### ISSUE TITLE
Remove Location Hierarchy fetch for Practitioner details Endpoint

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3583]
**Describe the feature request.**
- We currently, fetch the user location hierarchy when we access the Practitioner Details endpoint.  
- While this was useful before we couldn't access the Location Hierarchy endpoint via the app configs,  we need it now since the location hierarchy can be accessed and queries via the Location Hierarchy endpoint.  
- This ticket is to completely remove the functionality to fetch the Location Hierarchy via the Practitioner details endpoint

**Implementation Plan**
- [ ] Remove the functionality to fetch the Location Hierarchy when fetching the Practitioner details.  
- [ ] The Practitioner details endpoint should just return the following items 
    - [ ] CareTeam
    - [ ] Practitioner Role
    - [ ] Practitioner
    - [ ] Organization
    - [ ] Locations 

**Acceptance criteria**
- [ ] The Location Hierarchy should not be returned on the Practitioner details endpoint

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_
