### ISSUE TITLE
[Product] Update quest with the latest OpenSRP branding. 

### ISSUE THREAD

**Issue by dubdabasoduba** [opensrp/fhircore#3646]
**Describe the feature request.**
- The OpenSRP logos have been updated recently, we need to update the default application to brand the latest logos.  This involves updating the following areas 
    - OpenSRP icon for the app
    - The OpenSRP logo is on the login, pin setup, and pin login. 
    - OpenSRP logo on the documentation site favicon 

**Acceptance criteria**
- [ ] The OpenSRP app icon on devices should match the new logo
- [ ] The Logo image on the different pages should match the new logo
- [ ] The Documentation site  favicon should match the new logo

**Area path**
A list of ordered steps in the app on usage of the feature to support anyone testing it e.g. Code reviewer, QA e.g.
1. Login to the app
2. Open _Navigation bar_
3. Click on _Children register_
4. Click on _Child profile_
5. Click on _Edit profile_ from menu

**Implementation plan (For Engineers)**
The plan for implementing the solution e.g. via a _description_ or a _check list_ for the various ordered tasks that will need to be completed.
_i.e. Describe how you intend to solve the problem_
