### ISSUE TITLE
Refactor extraction to use Resource Mapper in FHIR SDK

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/fhircore#403]
**Refactor to remove resource based extraction**
We have parts of the code base that are using _Manual based resource extraction_. We have _SDC form data extraction_ supported by the FHIR SDK through the `ResourceMapper` class. SDC form data extraction make extraction business logic configurable and shareable
 
**For this task we need to**

- [x] Rewrite the FHIR patient registration Questionnaire(s) to the format supported by _SDC form data extraction_
- [x] Delete or Clean up the [QuestionnaireUtils.kt](https://github.com/opensrp/fhircore/blob/389f9851a23e36d5522a0ef1df2219f41701715e/android/app/src/main/java/org/smartregister/fhircore/util/QuestionnaireUtils.kt) class and remove the manual extraction helper methods. The FHIR SDK [ResourceMapper.kt](https://github.com/google/android-fhir/blob/master/datacapture/src/main/java/com/google/android/fhir/datacapture/mapping/ResourceMapper.kt) class functionality should replace this. 
- [x] Refactor the code from manual extraction in the [QuestionnaireActivity.kt](https://github.com/opensrp/fhircore/blob/389f9851a23e36d5522a0ef1df2219f41701715e/android/app/src/main/java/org/smartregister/fhircore/activity/QuestionnaireActivity.kt) class to use _SDC form data extraction_

**Example usage**
- [ResourceMapperTest.kt](https://github.com/google/android-fhir/blob/master/datacapture/src/test/java/com/google/android/fhir/datacapture/mapping/ResourceMapperTest.kt)
- [QuestionnaireActivity.kt#L80](https://github.com/opensrp/fhircore/blob/389f9851a23e36d5522a0ef1df2219f41701715e/android/app/src/main/java/org/smartregister/fhircore/activity/QuestionnaireActivity.kt#L80)

**Related issues** 
- #196

**Comment by ekigamba** [comment]
The way forward needs clarity
