### ISSUE TITLE
CHW/ANC SubTask - Search for Patient Observations

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#405]
- [ ] User can be able to search for different patient observations based on the search parameters defined [here](https://www.hl7.org/fhir/observation.html#search)

To start off we can start by searching observations based on  :
- [ ] Observation.encounter(Encounter)
- [ ] Observation.status
- [ ] Observation.effective (date)
- [ ] Observation.subject(Group, Device, Patient, Location)
- [ ] Observation.subject.where(resolve() is Patient)(Patient)
- [ ] Observation.performer(Practitioner, Organization, CareTeam, Patient, PractitionerRole, RelatedPerson)
- [ ] Observation.basedOn (CarePlan, MedicationRequest, NutritionOrder, DeviceRequest, ServiceRequest, ImmunizationRecommendation)

6.5 days FTE + 20% buffer
