### ISSUE TITLE
CHW/ANC SubTask - Register an ANC Patient 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#416]
To register an ANC Patient (mom), we may need to capture the following fields 

1. Patient.language	preferred	CommonLanguages
2. Max Binding: AllLanguages
3. Patient.identifier.use	required	IdentifierUse
4. Patient.identifier.type	extensible	Identifier Type Codes
5. Patient.name.use	required	NameUse
6. Patient.telecom.system	required	ContactPointSystem
7. Patient.telecom.use	required	ContactPointUse
8. Patient.gender	required	AdministrativeGender
9. Patient.address.use	required	AddressUse
10. Patient.address.type	required	AddressType
11. Patient.maritalStatus	extensible	Marital Status Codes
12. Patient.contact.relationship	extensible	PatientContactRelationship
13. Patient.contact.telecom.system	required	ContactPointSystem
14. Patient.contact.telecom.use	required	ContactPointUse
15. Patient.contact.gender	required	AdministrativeGender
16. Patient.communication.language	preferred	CommonLanguagesMax Binding: AllLanguages
17. Patient.link.type	required	LinkType

1.5 days FTE + 20% buffer

**Comment by f-odhiambo** [comment]
This ticket can be closed once the ticket #429  is DONE

**Comment by maimoonak** [comment]
This needs to be done on refactored code branch. Started on it.

**Comment by f-odhiambo** [comment]
**Updated mocks and steps** 
1. When you select a family member you will be presented with an empty profile page for the 1st time post registering them 
<img width="265" alt="Screen Shot 2021-09-07 at 11 09 05 AM" src="https://user-images.githubusercontent.com/4540684/132316384-6e28f808-0114-4a56-b135-4b040f984f19.png">

2. Form the profile page you can mark the female member as an ANC Client. _NB. We will need to add a validation check so that only members who fit the ANC criteria will be marked as ANC clients e.g. Must be female, Not a child or male etc._ 
<img width="265" alt="Screen Shot 2021-09-07 at 11 09 13 AM" src="https://user-images.githubusercontent.com/4540684/132316393-fb6d919d-ec82-4c9b-8b69-bca85724963f.png">

3. ANC registration questionnaire will be served to add detail of the Pregnacy this will be saved as a Condition resource . NB. Will need to confirm wether to add the risk factors to an Observation resource
<img width="265" alt="Screen Shot 2021-09-07 at 11 09 21 AM" src="https://user-images.githubusercontent.com/4540684/132316403-7c7863f8-6cb7-4a1c-80e6-2626023e9348.png">
<img width="265" alt="Screen Shot 2021-09-07 at 11 09 29 AM" src="https://user-images.githubusercontent.com/4540684/132316407-35f590d0-320e-4f6f-b775-9d316abec38a.png">

4. Once the enrollment is complete, show the user an alert and present them with the updated profile page that contains 
- [ ] CarePlan  - This will be updated once the Workflow API is complete. For now, we can have a placeholder  
- [ ] ANC Overview   - ANC details collected during ANC Enrollment 
- [ ] Upcoming services  - based the details from the ANC overview whats the next service based on the care plan  
<img width="316" alt="Screen Shot 2021-09-07 at 11 09 52 AM" src="https://user-images.githubusercontent.com/4540684/132316411-49d43f43-d29a-4fa1-83ea-792d03e88f54.png">


CC @maimoonak @RaaziaTarique @syedowaisali90

**Comment by f-odhiambo** [comment]
This ANC enrollment and adding the pregnancy details  triggers the application of the guideline, resulting in the creation of:
1. Condition
```
{
  "resourceType" : "Condition",
  "clinicalStatus" : {
    "coding" : [
      {
        "system" : "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code" : "active"
      }
    ]
  },
  "verificationStatus" : {
    "coding" : [
      {
        "system" : "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code" : "confirmed"
      }
    ]
  },
  "category" : [
    {
      "coding" : [
        {
          "system" : "http://terminology.hl7.org/CodeSystem/condition-category",
          "code" : "problem-list-item",
          "display" : "Problem List Item"
        }
      ]
    }
  ],
  "code" : {
    "coding" : [
      {
        "system" : "http://example.org/tbd",
        "code" : "TBD",
        "display" : "Pregnancy"
      }
    ],
    "text" : "Pregnancy"
  },
  "subject" : {
    "reference" : "Patient/XXX"
  },
  "onsetDateTime" : "XXXX-05-22" 
}
```
2. Episode of Care 

```
{
  "resourceType" : "EpisodeOfCare",
  "status" : "active",
  "type" : [
    {
      "coding" : [
        {
          "system" : "http://terminology.hl7.org/CodeSystem/episodeofcare-type",
          "code" : "hacc",
          "display" : "Home and Community Care"
        }
      ]
    }
  ],
  "diagnosis" : [
    {
      "condition" : {
        "reference" : "Condition/XXXX "
      },
      "role" : {
        "coding" : [
          {
            "system" : "http://terminology.hl7.org/CodeSystem/diagnosis-role",
            "code" : "CC",
            "display" : "Chief complaint"
          }
        ]
      },
      "rank" : 1
    }
  ],
  "patient" : {
    "reference" : "Patient/XXX"
  },
  "period" : {
    "start" : "XXXX-05-22"
  }
}
```
3. Encounter 
```
{
  "resourceType" : "Encounter",
  "status" : "in-progress",
  "class" : {
    "system" : "http://terminology.hl7.org/CodeSystem/v3-ActCode",
    "code" : "TBD",
    "display" : "Home Visit"
  },
  "type" : [
    {
      "coding" : [
        {
          "system" : "http://example.org/CodeSystem/encounter-type",
          "code" : "anc-contact",
          "display" : "Antenatal care contact"
        }
      ],
      "text" : "Antenatal care contact"
    }
  ],
  "subject" : {
    "reference" : "Patient/XXX"
  },
  "episodeOfCare" : [
    {
      "reference" : "EpisodeOfCare/XXX"
    }
  ],
  "participant" : [
    {
      "type" : [
        {
          "coding" : [
            {
              "system" : "http://terminology.hl7.org/CodeSystem/v3-ParticipationType",
              "code" : "PPRF",
              "display" : "primary performer"
            }
          ]
        }
      ],
      "individual" : {
        "reference" : "Practitioner/XXX"
      }
    }
  ],
  "period" : {
    "start" : "XXXX-05-24"
  },
  "diagnosis" : [
    {
      "condition" : {
        "reference" : "Condition/XXX"
      },
      "rank" : 1
    }
  ]
}

```
3. Goal 
```
{
  "resourceType" : "Goal",
  "lifecycleStatus" : "active",
  "subject" : {
    "reference" : "Patient/XXX",
    "display" : "Name of ANC Client"
  }
}
```
4. CarePlan - _To Be Discussed_

**Comment by maimoonak** [comment]
ANC Enrollment Questionnaire - https://fhir.labs.smartregister.org/fhir/Questionnaire/1770

**Comment by maimoonak** [comment]
@f-odhiambo in Family member registration we have a question 'is pregnant' if gender is Female. Do we want to use that well in decision making?n Or alternatively remove that. Also when we mark someone as pregnant we also add a Flag/Tag to their 'Patient' resource to allow querying them directly. Do we want to keep that or remove?

**Comment by f-odhiambo** [comment]
@maimoonak I would propose this to be a classic use case for skip logic. If a patient is checked as pregnant then make visible and ask the ANC enrollment questions i.e (EDD, GA, Foetus count and Risks #288 ) and then save the relevant resources. They would appear in the ANC register and also they would have tags and references to the Condition - Pregnancy, Episode of Care and Encounter.

**Comment by pld** [comment]
Are we using StructureMaps to create the Condition, EpisodeOfCare, Encounter, and Goal from the QuestionnaireResponse?

For the scope of this issue, I don't think we need to flag/tag, that can be discussed/completed in an issue for functionality that requires it.

**Comment by maimoonak** [comment]
https://github.com/opensrp/fhircore/pull/529 Resolved with this PR

![Screenshot from 2021-09-20 13-51-13](https://user-images.githubusercontent.com/4829880/133977369-a34b555c-3073-4a65-a299-984108db75b4.png)
