### ISSUE TITLE
Required Fields for the Covax Demo app for WHO

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#426]
**Required Fields for Immunization tracking**

**General Patient info**   
1. Unique identifier - Unique identifier for the vaccinated person, according to the policies applicable to each country. There can be more than one unique identifier used to link records (e.g. national ID, health ID, immunization information system ID, medical record ID)  - ID
2. Name - ​​The full name of the vaccinated person  - String 
3. Date of birth  - The vaccinated person's date of birth (DOB) if known. If unknown, use assigned DOB for administrative purposes - Date - ​​Complete date, following ISO 8601 (YYYYMMDD or YYYY-MM-DD)
4. Sex - Documentation of a specific instance of sex information for the vaccinated person.
- [x] New Questionnaire Link  - https://fhir.labs.smartregister.org/fhir/Questionnaire/940

**COVID-19 specific Immunization details** 
- [x] 1. [Vaccine or prophylaxis](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.vaccineCode) - Generic description of the vaccine or vaccine sub-type, e.g. COVID-19 mRNA vaccine, HPV vaccine.
> COVID-19 vaccine
> COVID-19 vaccine inactivated virus
> COVID-19 vaccine, live attenuated virus
> COVID-19 vaccine, non-replicating viral vector
>  COVID-19 vaccine, replicating viral vector
> COVID-19 vaccine, virus protein subunit
> COVID-19 vaccine, virus-like particle (VLP)
> COVID-19 vaccine, DNA based
> COVID-19 vaccine, RNA based
- [ ] 2. Vaccine brand  - The brand or trade name used to refer to the vaccine received - **Text in vaccine code** 
- [x] 3. Vaccine [manufacturer](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.manufacturer) - Name of the manufacturer of the vaccine received. e.g. Serum institute of India, AstraZeneca. If the vaccine manufacturer is unknown, the market authorization holder is REQUIRED/OPTIONAL.
- [ ] 4. Vaccine market authorization holder - Name of the market authorization holder of the vaccine received. If the market authorization holder is unknown, the vaccine manufacturer is REQUIRED/OPTIONAL  - Pharmacy and Poisons Board (FIXED)
- [x] 5. [Vaccine batch number ](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.lotNumber) - Batch number or lot number of vaccine
- [ ] 6. Date of vaccination - Date in which the vaccine was provided - **Encounter ? Occurance ? recorded (When ) ?**
- [x] 7. [Dose number ](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.protocolApplied.doseNumber_x_)- Vaccine dose number.
- [x] 8. [Total doses](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.protocolApplied.seriesDoses) - Total expected doses as defined by Member State care plan and immunization programme policies
- [ ] 9. Country of vaccination - The country in which the individual has been vaccinated i.e KE FIXED  **- Do we use the location for this?**
- [ ] 10. Administering centre - The name or identifier of the vaccination facility responsible for providing the **vaccination.**
- [ ] 11. Signature of health worker  - REQUIRED for PAPER vaccination certificates that have been filled out with handwriting ONLY.   A printed paper vaccine certificate does not require the handwritten signature of a health worker. The health worker who provided the vaccination or the supervising clinician's hand-written signature. -NA
- [x] 12. [Health worker identifier ](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.performer)- OPTIONAL for DIGITAL and PAPER vaccination certificates. The unique identifier for the health worker is determined by the member state. There can be more than one unique identifier used. (e.g. system-generated ID, health profession number, cryptographic signature, or any other form of health worker unique identifier). This can be used in lieu of a paper-based signature. 
- [x] 13. [Disease or agent targeted](https://www.hl7.org/fhir/immunization-definitions.html#Immunization.reasonCode) - Name of disease vaccinated to protect against (such as COVID-19). OPTIONAL
- [ ] 14. Due date of next dose - Date on which the next vaccination should be administered if the next dose is required. - Date	Complete date, following ISO 8601 (YYYYMMDD or YYYY-MM-DD) - **_Calculated from recorded/encounter via CQL_** 

Current bundle https://fhir.labs.smartregister.org/fhir/Immunization?patient=969
Target bundle  - https://fhir.labs.smartregister.org/fhir/Bundle/f03267d1-7945-455e-bf54-103c97cd554a

**COVID-19 Immunization tracking**  _Backend_ 
- [ ] 15. Certificate issuer - The authority or authorized organization that issued the vaccination certificate. String -    **Public health authority** 
- [ ] 26. Health Certificate Identifier (HCID)  - Unique identifier is used to associate the vaccination status represented in a paper vaccination card to its digital representation(s). ID - **Bar Code number** 
- [ ] 27. Certificate valid from - Date in which the certificate became valid.   No health or clinical inferences should be made from this date - Date	Complete date, following ISO 8601 (YYYYMMDD or YYYY-MM-DD) - **_To be defined by the SVC service** 
- [ ] 528 Certificate valid until - Last date in which the certificate is valid.  No health or clinical inferences should be made from this date.  - Date	Complete date, following ISO 8601 (YYYYMMDD or YYYY-MM-DD) - **_To be defined by the SVC service** 
- [ ] 19. Certificate schema version - Version of the core data set and HL7 FHIR Implementation Guide that the certificate is using.  String -**_To be defined by the SVC service** 

**SubTasks**

- [x] #176 
- [x] #474 
- [x] #452
- [x] #472
- [x] #488
- [x] #473
- [x] https://github.com/opensrp/web/issues/793
- [x] https://github.com/opensrp/web/issues/795

**Comment by f-odhiambo** [comment]
**Base Implementation**  

1. Load the StructureDefinition 
2. Create a new Java model
> a. Sync Client 
3. New Java class 
4. QA

**Server-side** 

1. Add Controllers
2. Add API EndPoints - To post data based on the provided StructureDefinition 
3. Add New Table maybe

**Android  FHIRCore**
Change the methods in 
1. Save 
2. Retrieve
3. Status

WHO should have a complete package NPM to also support this and also do the SVC generation Endpoint to retrieve the QR code

**Comment by pld** [comment]
> **Base Implementation**
> 
>     1. Load the provided [StructureDefinition ](https://worldhealthorganization.github.io/ddcc/StructureDefinition-DDCCCoreDataSetPoV.html)
> 
>     2. Create a new Java model
> 
> 
> > a. Sync Client
> 
>     1. New Java class
> 
>     2. QA
> 
> 
> **Server-side**
> 
>     1. Add Controllers
> 
>     2. Add API EndPoints - To post data based on the provided [StructureDefinition ](https://worldhealthorganization.github.io/ddcc/StructureDefinition-DDCCCoreDataSetPoV.html)
> 
>     3. Add New Table maybe
> 
> 
> **Android FHIRCore**
> Change the methods in
> 
>     1. Save
> 
>     2. Retrieve
> 
>     3. Status
> 
> 
> WHO should have a complete package NPM to also support this and also do the SVC generation Endpoint to retrieve the QR code

I don't think this is related to the issue here

**Comment by f-odhiambo** [comment]
@ndegwamartin

**Comment by f-odhiambo** [comment]
**Next steps** 
1. Agree on the contractual agreement  
2. We are currently storing the Immunization resource for a patient using the Immunization resource https://www.hl7.org/fhir/immunization.html
3. They would like us to adhere to the  shared StructureDefiniton  here https://worldhealthorganization.github.io/ddcc/StructureDefinition-DDCCCoreDataSetPoV.html
4. We can check and share feedback on any missing field that is not mapped based on the StructureDefiniton i.e The country should be mapped to Location etc.
5. Have the app generate the following QuestionnaireResponse here https://worldhealthorganization.github.io/ddcc/Bundle-DDCC-TX-SHE-bundle-example-1.json.html for consumption by the SVC server. This could be a button on the patient profile for the fully vaccinated patient and log the QuestionnaireResponse required for this
6. Let WHO SVC team know if the LOE for 2 weeks is feasible to do this  & Push forward the  demo slotted for this coming Friday
