### ISSUE TITLE
[Roadmap] fhirengine-alpha-02 release: ERD 04-06-21 #508

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#456]
This alpha-02 release of the fhirengine library addresses a dependency issue that was causing an error when trying to build from maven and API change related to Sync.

- [x]  Remove CQL dependency in fhirengine: Remove FHIR engine's dependency on CQL and bump up version [#454](https://github.com/google/android-fhir/pull/454)
- [x]  Rework sync API to be separate form data access API: Rework sync API to be separate from data access API [#482](https://github.com/google/android-fhir/pull/482)

Release checklist:
- [x]  Have run relevant tests
- [x]  Documentation updated (if required)
- [x]  Released

More details [here](https://github.com/google/android-fhir/projects/7#card-62011427)
