### ISSUE TITLE
[Roadmap] sdc-alpha-03 release | ERD 12-06-30

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#457]
This alpha-03 release of the data-capture library will add in the additional features:

- [x]  Pagination [Questionnaire pagination #186](https://github.com/google/android-fhir/issues/186)
- [x]  Language support [Render questionnaire in different language using language extension #465](https://github.com/google/android-fhir/issues/465)
- [x]  Validation API [API for validation in the sdc lib #374](https://github.com/google/android-fhir/issues/374)
- [x]  Element extension (regex) [Add support for element extension: regex #466](https://github.com/google/android-fhir/issues/466)
- [x]  Element extension (min/max Length) [Support max length and min length #185](https://github.com/google/android-fhir/issues/185)
- [x]  Handle required fields in questionnaires [Handle required fields in questionnaires #470](https://github.com/google/android-fhir/issues/470)
- [x]  Auto complete [autoComplete (filter forward based on inlined answer Options) #520](https://github.com/google/android-fhir/issues/520)
