### ISSUE TITLE
[Roadmap] fhirengine-alpha-03 | ERD 30-06-21

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#459]
FHIR engine alpha 03 release. Adds additional features across search, sync and data access:
 **Search**:

- [x]  modifiers with :contains [Support Contains for string search #426](https://github.com/google/android-fhir/pull/426)
- [x]  modifiers with :exact [Support Contains for string search #426](https://github.com/google/android-fhir/pull/426)
- [x]  multiple search criteria joined by AND operator
- [x]  search by number type [Support Search for Number Type #435](https://github.com/google/android-fhir/issues/435)
- [x]  search by token type [Adds token search #461](https://github.com/google/android-fhir/pull/461)
- [x]  search by date [Support date and date-time in search #375](https://github.com/google/android-fhir/issues/375)
 
**Sync:**
- [x]  Retry functionality [Retry in syncing resources #535](https://github.com/google/android-fhir/issues/535)

**Data access:**
- [x] Database failure model design and implementation: [Review database failure model design+implementation (exceptions, failure mode, transaction) #510](https://github.com/google/android-fhir/issues/510)
