### ISSUE TITLE
[Roadmap] fhirengine-alpha-04 release | ERD XX-08-21

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#462]
This alpha-04 release of the fhirengine library includes feature updates, new features and addresses existing issues:

 **Search**

- [ ] * Optional support for fuzzy search on Patient name field - [FTS on Patient name to support for fuzzy search #608](https://github.com/google/android-fhir/issues/608)
- [ ]  * Resolve ValueSet lookups via Search API - [Resolve ValueSet lookups via Search API #609](https://github.com/google/android-fhir/issues/609)
- [x] * Search with joins of different types of resources - [Search by multiple resource types #611](https://github.com/google/android-fhir/issues/611)
- [ ]  * Multiple search criteria joined by OR operator - [Adds union operator in the or clause #438](https://github.com/google/android-fhir/pull/438)
- [x]  * Support for prefixes: eq, ne, gt, lt, ge, le - [Support prefixes in search: eq, ne, gt, lt, ge, le #474](https://github.com/google/android-fhir/issues/474)

 **Sync**

- [x]  * Sync status - [Provide a `StateFlow` for sync status #554](https://github.com/google/android-fhir/issues/554)
- [ ]  * Improved syntax for sync API (using Kotlin DSL) - #

 **New features (TBC)**

- [ ]  * (Deployment) ImplementationGuide deployment support
- [ ]  * (Security) SQL Cipher support for enhanced data privacy

 **Addresses the following issues:**

- [x]  * Ensure there is only one instance of fhirengine in db (per process, per database) - [Making Fhir engine a singleton per process per db name #100](https://github.com/google/android-fhir/issues/100)
- [ ]  * Block fhirenigne upload cross processes - [Disable simultaneous upload from multiple processes #103](https://github.com/google/android-fhir/issues/103)
