### ISSUE TITLE
[Roadmap] FHIRCore Milestone 11

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#491]
At the end of this milestone, we expect to have accomplished 80% of the below-listed items 

**WIP to complete** 
- [ ] Workn on [Sprint 11](https://github.com/opensrp/fhircore/milestone/20)

**Updated Covax app**
- [ ] Update the Covax demo app questionnaire with the new requirements i.e. Update the save vaccine method and also post extra fields for Covid-19 Vaccination in Covax demo app https://github.com/opensrp/fhircore/issues/488
- Prepare sample APK

**CHW/ANC App**
Based on the milestone -  [CHW ANC App MVP](https://github.com/opensrp/fhircore/milestone/17)
- [ ] CHW/ANC - Family Registration #453
- [ ] CHW/ANC - Patient registration and management #277

**G6PD**
- [ ] Requirments validation and scoping  - DONE
- [ ] Clinical workflow validation workshop  - Pending
- [ ] Revised designs  - Pending
- [ ] Updated project plan & budget  - Done
- [ ] Revised Gannt  - Pending 
- [ ] Revisewd LOEs for the different work package items   - Pending

If the above is approved move to :
- [ ] Sync configs resources based on creds - To be done once #296 is complete 
- [ ] Patient registration  (to be configured based on the G6PD Questionnaire) 
- [ ] Patient profile (to be configured based on the requirements) 
- [ ] Manual entry patient's observation details

**mADX**
- [ ] Test and implement measure reporting #177 & #310
- [ ] Patient registration  (to be configured based on the mADX Questionnaire)
- [ ]  Patient profile (to be configured based on the requirements)  
- [ ] Test Measure reporting from [server side](https://github.com/DBCG/cqf-ruler/blob/5f50c55bf17d1b1afe15c37152647c333bed8eeb/r4/src/main/java/org/opencds/cqf/r4/providers/MeasureOperationsProvider.java#L145) based on DBCG cqf-ruler
