### ISSUE TITLE
Patient Search - Master

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#50]
User story :
As a CHW, I want to search for  a patient so that I can be able to retrieve their details 

- Search can be implemented based on FHIR [parameters](https://www.hl7.org/fhir/search.html) 
- Search will be based on the search API in the  Android FHIR SDK 

Acceptance criteria :

- [x] Clicking on the search icon should present you with a patient search screen - related to issue no [#385](https://github.com/google/android-fhir/issues/385)
- [x] Able to add the search criteria via a selection list - related to issue [#385](https://github.com/google/android-fhir/issues/385)
- [x] If the query returns a result,  display  search results and on select view and on click view patient details in a [patient profile view](https://github.com/OpenSRP/fhircore/issues/22) 
- [x] If the query is  null result display not found message/notification

This issue is related to the below-listed issues on  [Android FHIR SDK](https://github.com/google/android-fhir). Part of the implementation will be done there
- [x] Investigate using DSL in Kotlin for search [#57](https://github.com/google/android-fhir/issues/57)
- [x] Create a search panel in the patient list view in the reference app [#385](https://github.com/google/android-fhir/issues/385)
- [x] Support contains for string search [#376](https://github.com/google/android-fhir/issues/376)

Sub Tasks
- [x] Basic Patient search [#20](https://github.com/OpenSRP/fhircore/issues/20) 
- [x] Search from a list of patients (eg. pre-enrolled) in a FHIR datastore on the device or from the server https://github.com/OpenSRP/fhircore/issues/53
- [x] Filter and pagination https://github.com/OpenSRP/fhircore/issues/54
- [x] Handle "OR" in search filters [#292](https://github.com/google/android-fhir/issues/292)

For ANC app
- [x] Ability to search from a list of patients (eg. pre-enrolled) in a FHIR datastore on the device or against the entire access permitted patient list on the health information system.

For the Covid app, we can add a filter  in the search for 
- [x] [Overdue](Filter patients whose second dose is overdue #176) - Missed appointment for/next jab 
- [x]  Record Jab - Start the care plan
- [x]  Partially vaccinated  - If had the first dose, the due date of 2nd dose 
- [x] Vaccinated  - If completed vaccination, view the certificate

**Comment by f-odhiambo** [comment]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-15e444f7-7fff-b3dd-77d0-6d1380f24da8"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Search use cases to be covered in FHIR SDK</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

P | Search title | Description | Example
-- | -- | -- | --
  | Patient search | Commonly used within app home screen to quickly find an existing patient | Search for a patient using a set of pre-defined parameters from the <Patient> resource e.g: Name, MRN, National ID, mobile phone number should be able to join by AND/OR operators
  | Search by multiple resource types | Search with joins of different types of resources (e.g. patients with an observation with a certain code) | [Need help here]Show all patients that have had a vaccination and have an immunization status of overdue
  | Generate worklist | For a set of patients return associated resources (e.g. CarePlan task resources) | Generate a worklist of patients and tasks (from a CarePlan). For each patient, return the Task activities
  | Search by data-types | Construct a search query from different data-types (not just String) e.g. Date, DateTime, Code, Number | Find all observations where Code = X
  | Searching with prefixes | Be able to construct a search query with prefixes such as <, >, !=, NOT | Find observation with Code X where value is < Y
  | Search ValueSets for Code | Look-up a specific term within a ValueSet resource and return the ‘code’ | When constructing a complex query, look up the codes for Diabetes and then use those in the next query
  | Search for resources based on ValueSet result | Be able to complete the above search with a single query | Find all patients where condition contains (codes from ValueSet lookup for Diabetes)

</div></b>

We can add comments on any search use cases that have not been covered here @rkodev @pld

**Comment by f-odhiambo** [comment]
All Items here are DONE
