### ISSUE TITLE
Patient Registration - Master

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#51]
User story : 
As a CHW, I want to register a patient so that they can be enrolled on the platform.
The patient details will be based on the FHIR resource as a  [Questionnaire](https://www.hl7.org/fhir/questionnaire-example.json.html)
Acceptance criteria : 

- [x] On the landing page, you can view a list of already enrolled patients on the platform. - Design mocks will be required [issue](https://github.com/OpenSRP/fhircore/issues/39) 
- [x] The patient list should show details of the patient (ID, Firstname, Lastname, Gener, DOB)- Design mocks will be required [issue](https://github.com/OpenSRP/fhircore/issues/39) 
- [x] On clicking a patient you can view the patient profile ([details here](https://github.com/OpenSRP/fhircore/issues/22))
- [x] Click on the add patient button to be presented with a form to fill in patient details. 
- [x] Provide an option to save the response  which will be saved as an FHIR [QuestionnaorResponse](https://www.hl7.org/fhir/questionnaireresponse-example.json.html) 

Related item on [Android FHIR SDK](https://github.com/google/android-fhir/)
- [x] Support for uploading resources to FHIR server [#366](https://github.com/google/android-fhir/issues/366) 
- [x] API for validation in the sdc lib [#374] (https://github.com/google/android-fhir/issues/374)

Sub Tasks 
- [x] Basic Patient registration https://github.com/OpenSRP/fhircore/issues/19
- [x] Input validation https://github.com/OpenSRP/fhircore/issues/56
- [x] Save FHIR resource to SQLite DB & Sync to FHIR server https://github.com/OpenSRP/fhircore/issues/55
- [x] Patient Profile view https://github.com/OpenSRP/fhircore/issues/22
