### ISSUE TITLE
APK Release checklist for both  Covax app and ANC MVP  - Pre Release & Final

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#516]
**Covax Demo app** 
- [x] User authentication
- [x] Sync in progress in Navigation drawer
- [x] Patient list with sync progress bar
- [x] On sync complete alert user 
- [x] Pagination of the patient list
- [x] Filter by overdue immunization
- [x] Search First name, Last name 
- [x] Patient enrollment 
- [x] Record vaccine with correct alert dialog for Doses 1 & 2 
- [x] One receive dose of vaccine refresh the patient profile page
- [x] View patient profile if partially vaccinated and fully immunized 
- [x] Sync details to HAPI FHIR Server

**ANC MVP**
- [x] User authentication
- [ ] Family list with sync progress bar
- [ ] On sync complete alert user 
- [x] Assign head of household
- [ ] Add members of the family
- [ ] View Family Profile 
- [x] View Family member profile  
- [x] Search for a Family by Family name 
- [ ] Search for an individual ANC client i.e. by  First name, Last name

**Comment by f-odhiambo** [comment]
Is it however noted that the Barcode implementation is not yet merged on the Andsropif FHIR SDK thus may be missing from the generated APK

**Comment by f-odhiambo** [comment]
**Covax review** 
1. Questionnaire with Comorbidity risk flagging should only be visible for JnJ use case/workflow 
2. Remove Comorbidity Questionnaire and related-person details  for WHO Covax demo and leave only patient details 
3. Integrate barcode functionality - still missing 
4.  Record vaccine questionnaire takes a while to load  
5. Language switching not supporting radio buttons 

**ANC Review**
