### ISSUE TITLE
Quest v0.2 / G6PD: Optimize Quest Synchronization (Filter Resources by app id)

### ISSUE THREAD

**Issue by trevorgowing** [opensrp/fhircore#668]
### Context

As per discussion https://github.com/opensrp/fhircore/discussions/676 initiated based on issue https://github.com/opensrp/fhircore/issues/642 the Quest App synchronization needs to be reordered and the resources filtered.

### Summary

The issues we are trying to resolve are minimizing unnecessary synchronization by moving synchronization to when it is applicable as well as minimizing the number of resources that are synchronized.

The ultimate goal is to improve the user experience by improving app performance and minimizing synchronization time.

### Tasks

- [ ] Add the application id as an identifiers to any create resources. e.g. `Patient`.
- [ ] Synchronize Application Configuration post login. Configuration is currently represented as a JSON object stored in the FHIR server in a Binary resource. This request requires authentication so it doesn't make sense to synchronize this resource prior to log in.
- [ ] Filter clinical resources by application id. Currently `quest-app`.
- [ ] Trigger periodic sync post log in rather than on app startup and filter resources by application id.

**Comment by mberg** [comment]
Please confirm way forward here. Do we have an implementation strategy or not

**Comment by maimoonak** [comment]
@shoaibmushtaq25 Kindly explore the http://hl7.org/fhir/searchparameter.html and compare it with primaryFilter class we are using

**Comment by maimoonak** [comment]
@shoaibmushtaq25 http://hl7.org/fhir/operationdefinition.html this one as well. This also resembles to Search Parameter with some more capabilities

**Comment by maimoonak** [comment]
{
  "resourceType": "Composition",
  ................ FROM  #594 ..................
  "section": [
    {
      "title": "WHO Quest App Defination Sync Params",
      "focus": {
        "reference": "Binary/sync-params-to-use",
        "display": "WHO Quest App Sync Points",
        "type": "clinical_sync_configurations"
      },
      "text": "Used to define the app sync config",
      "mode": "working"
    }
.......................... OTHER FROM #594 .......................
  ]
}

**How to parse or use the Params**
```
// Search Parameter for Patient = spp
// THIS is coming from database/server from Composition for given user
val spp = listOf<SearchParameter>().first() // first item in Binary

mapOf(
  // ResourceType.Patient to mapOf() -> NOW would be
  ResourceType.fromCode(spp.base[0].code) to mapOf(
    spp.expression to LoggedInUserInfo.fhirPath(spp.xpath) // $practitioner.organization
  )
)
```
@shoaibmushtaq25 can we write some sample that picks this only for Patient for now

**Comment by shoaibmushtaq25** [comment]
@maimoonak sure, I am on it. Trying to digest the things in order to work on sample to pick up patients.

**Comment by maimoonak** [comment]
Ok. Cool. Sure. Start from using hardcoded data and gradually move those to external files and then to server

**Comment by dubdabasoduba** [comment]
> clinical_sync_configurations

@maimoonak Do we have a sample json for the `clinical_sync_configurations`

**Comment by maimoonak** [comment]
```
{
  "code": "sync-by-organization",
  "base": [
    "Patient"
  ],
  "type": "reference",
  "expression": "Patient.managingOrganization",
  "xpath": "$user.organization",
  "xpathUsage": "normal",
  "target": [
    "Organization"
  ]
}
```

**Comment by dubdabasoduba** [comment]
> "expression": "Patient.managingOrganization",

@maimoonak The `expression` attribute here seems to suggest syncing the patients managed by a certain organisation.  Can we do the same thing when using groups? The location mapping pieces need that.

**Comment by dubdabasoduba** [comment]
Syncing via search parameters following the location mapping
---
- Using the[ location mapping](https://github.com/opensrp/fhircore/blob/main/docs/assets/resource-graph/unified-resource-graph-v01.png) definition we assign patients to different groups based on the health track e.g (ANC, CHILD, PNC e.t.c)
- We need to adapt the sync parameters to sync the groups holding each patient. 

Implementation
---
**Adding patients to groups**
- [ ] FHIR web creates groups for the different health tracks an app can handle. 
- [ ] Adding each group id/identifier to a config that the app uses. 
    - [ ] Figure out the config to use and the config structure
- [ ] These ids are co-related to each registration workflow point.  
- [ ] When a patient resource is created, the patient reference is also added to the `members` attribute on the group. 

**Filtering patients via a group** 
- [ ] Using the practitioner's careteam we can get the group the careteam manages. 
    - [ ] This will be using the `subject` attribute on careteam.
- [ ] Get all the group `members` and display the patients on the patient list.

**Comment by maimoonak** [comment]
We can handle the usecase above. Just that the approach for syncing  from mobile is reverse of above

Points to consider
- This issue refers to general search/sync for entities required on device including Patients, Encounters, QResponses, Observations etc. 
- For any filter reference to that entity or field should be contained in entity we want to sync. i.e. if we want to sync Patient by Location the entity should be referenced in patient. if we want to filter by Role it should be present inside Patient (directly or indirectly)
- The search support [indirect or chained or nested referencing](http://hl7.org/fhir/search.html#chaining).  
- Patient has association with Organization or Practitioner or PractitionerRole, and Location has association with Organization and not the Group. Hence we might want to use a property referenced into patient so that we can also sync other entities by chain which reference patients.i.e. Encounter.subject.managingOrganization or QResponse.subject.managingOrganization. Otherwise we would have to sync all other relevant data 1 by 1 for each patient which can lead to increased sync time and complex code
- We would want to provide a generic filter a smaller set of filter values instead of providing specific ids to sync (I guess above comment refers to same thing but just want to reiterate). It implies that we would assign each patient one or more Organization and remove patient association from that when needed. This is opposite of what is mentioned above. i.e. Remove reference into  Patient for given Org, and not removing Organization or Group data.
- If we want to sync or manage data by Groups it would need changes into the way we manage data. We deal with individual Patient into app and did not go with Group approach (We can discussed this on call)

Sync for Patient
The entity that is combining the Organization, Practitioner, and Location is PractitionerRole

Patient has two fields which allows association with broader community
- managingOrganization Reference(Organization) (0-1)
- generalPractitioner Reference(Organization | Practitioner | PractitionerRole) (0-*)

We can sync Patient by Organization or PractitionerRole or Location by actually getting the relevant data from Logged in User. This can be passed to sync filter
Sync Patient by Location -> Patient?generalPractitioner.location.id=$loggedInPractitionerRole.location
Sync Patient by Organization -> Patient?generalPractitioner=$loggedInPractitionerRole.organization
Sync Patient by Organization -> Patient?managingOrganization=$loggedInPractitionerRole.organization

Sync for Encounter/Observation/....
Sync by Location -> Encounter?subject.generalPractitioner.location.id=$loggedInPractitionerRole.location
Sync by Organization -> Observation?subject.generalPractitioner=$loggedInPractitionerRole.organization
Sync by Organization -> Encounter?subject.managingOrganization=$loggedInPractitionerRole.organization

**Comment by dubdabasoduba** [comment]
> We can handle the usecase above. Just that the approach for syncing from mobile is reverse of above
> 
> **Points to consider**
> 
> * This issue refers to general search/sync for entities required on device including Patients, Encounters, QResponses, Observations etc.
> * For any filter reference to that entity or field should be contained in entity we want to sync. i.e. if we want to sync Patient by Location the entity should be referenced in patient. if we want to filter by Role it should be present inside Patient (directly or indirectly)
> * The search support [indirect or chained or nested referencing](http://hl7.org/fhir/search.html#chaining).
> * Patient has association with Organization or Practitioner or PractitionerRole, and Location has association with Organization and not the Group. Hence we might want to use a property referenced into patient so that we can also sync other entities by chain which reference patients.i.e. Encounter.subject.managingOrganization or QResponse.subject.managingOrganization. Otherwise we would have to sync all other relevant data 1 by 1 for each patient which can lead to increased sync time and complex code
> * We would want to provide a generic filter a smaller set of filter values instead of providing specific ids to sync (I guess above comment refers to same thing but just want to reiterate). It implies that we would assign each patient one or more Organization and remove patient association from that when needed. This is opposite of what is mentioned above. i.e. Remove reference into  Patient for given Org, and not Patient from removing Organization or Group data.
> * If we want to sync or manage data by Groups it would need changes into the way we manage data. We deal with individual Patient into app and did not go with Group approach (We can discuss this on call)
> 
> **Sync for Patient** The entity that is combining the Organization, Practitioner, and Location is PractitionerRole
> 
> Patient has two fields which allows association with broader community
> 
> * managingOrganization Reference(Organization) (0-1)
> * generalPractitioner Reference(Organization | Practitioner | PractitionerRole) (0-*)
> 
> We can sync Patient by Organization or PractitionerRole or Location by actually getting the relevant data from Logged in User. This can be passed to sync filter Sync Patient by Location -> Patient?generalPractitioner.location.id=$loggedInPractitionerRole.location Sync Patient by Organization -> Patient?generalPractitioner=$loggedInPractitionerRole.organization Sync Patient by Organization -> Patient?managingOrganization=$loggedInPractitionerRole.organization
> 
> **Sync for Encounter/Observation/....** Sync by Location -> Encounter?subject.generalPractitioner.location.id=$loggedInPractitionerRole.location Sync by Organization -> Observation?subject.generalPractitioner=$loggedInPractitionerRole.organization Sync by Organization -> Encounter?subject.managingOrganization=$loggedInPractitionerRole.organization

@maimoonak I agree with this approach for how things are implemented right now. My suggestion is more on aligning the work we do with the location mapping pieces we had done earlier.

**Comment by maimoonak** [comment]
Could you plz reference the Location Hierarchy ticket here so that we can actually sync and test that as part of this ticket

**Comment by shoaibmushtaq25** [comment]
As a sample code, Me and @maimoonak tried to filter out patients of a specific organization using [SearchParameter](http://hl7.org/fhir/searchparameter.html) loaded from local assets just like we can do it using [RestApi call](https://fhir.labs.smartregister.org/fhir/Patient?organization=3454) and we were able to do this filtering and see that SearchParameter works in that case.

For the next steps, I am going to work to filter out Encounters of some specific Organization using SearchParameter loaded from assets just like we can do it using [this RestApi call](https://fhir.labs.smartregister.org/fhir/Patient?organization=3454)

Then move on the next steps towards more generic way of filtering.

**Comment by shoaibmushtaq25** [comment]
We are able to create generic filters for Patient, Encounter, Observation and CarePlan using [SearchParameters](http://hl7.org/fhir/searchparameter.html) to filter resources based on the organization and they are working fine.
Right now, we are assuming a hardcoded user (Practitioner with hardcode Organization assigned).
Now , we need an actual PractitionerRole assigned to our demo user(logged in user) with some organization assigned to it and we need the help of @dubdabasoduba here to assign this PractitionerRole to the demo user so that we can test out end to end flow. cc @f-odhiambo @maimoonak 

For the next steps, we will be working on moving these SearchParameters to Composition resource, load the config from Composition(DB) and also be testing it with other resources (Questionnaire etc.)

**Comment by pld** [comment]
For the next steps, I think we should track that in another issue and close this issue when the "quick fix" is complete

**Comment by shoaibmushtaq25** [comment]
For QUEST, We are now syncing loggedin user specific fhir resources based on organization or publisher using the [Search Parameters](http://hl7.org/fhir/searchparameter.html) . the linked PR is up [here](https://github.com/opensrp/fhircore/pull/797) for the review
we are syncing these resources based on the mentioned criteria below,
- Patient (organization = user's organization)
- Encounter(subject.organization = user's organization)
- Observation(subject.organization = user's organization)
- Condition(subject.organization = user's organization)
- QuestionnaireResponse(patient.organization = user's organization)
- Questionnaire(publisher = user's publisher)

If we receive organization, publisher(for Questionnaire) in the user-info call from server, we will prepare the Search Parameter based on the value of organization or publisher(for Questionnaire) otherwise, we will pass empty map to fetch all the Resources(Questionnaires and other Resources)

For the next steps, we will try to achieve this using the Composition resource as mentioned by the Benjamin

**Comment by maimoonak** [comment]
For further clarification
We have 3 users 
**demo** = publisher = null, organization = 105 
-> sync all-Questionnaires, all-Binary, and org-105[Patient, QResp, Obs,...]

**ona** = publisher = ONA Systems, organization = 3454 
-> sync all ona[Questionnaires], all-Binary, and org-3454[Patient, QResp, Obs,...]

**msf** = publisher = MSF, organization = 205 
-> sync all msf[Questionnaires], all-Binary, and org-105[Patient, QResp, Obs,...]

**Comment by shoaibmushtaq25** [comment]
> For the next steps, I think we should track that in another issue and close this issue when the "quick fix" is complete

Quick fix is done and merged, @f-odhiambo , Can you please create a separate issue for the next pieces (sync optimization using Composition resource) and assign it to me or If we have it already created, assign it to me?
