### ISSUE TITLE
ANC app checklist  - Tracked Issues, Bugs, Features implemented 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#692]
Checklist to ensure we are ready for CarePlan generation i.e  $apply($patient_id,$PlanDefinition_id) = CarePlan  for a patient

1. Authentication 
- [ ] Login page 
- [ ] Validation 
- [ ] Logout    

2. Sync
- [ ] Optimize sync takes more >1 minute to load clients 
- [ ] Remove Junk Dummy data 

3. Bottom navigation 
- [ ] Icons for Register, Tasks, Reports and Profile 
- [ ] Change register icon

4. Top bar
- [ ] Need to Menu item ?

5. Search 
- [ ] Patient Given name, Family name
- [ ] ID, Identifier 
- [ ] Filters ?

6. Family list
- [ ] Data matches  - Clients in list should be same in profile 
- [ ] If Head of Household (HHH) in ANC icon is circled 
- [ ] DOB Year, Month, Weeks 

7. Add Family 
- [ ] DOB validation <= today 
- [ ] DOB as date or integer 
- [ ] Mandatory vs Optional fields

8 Family Profile 
- [ ] UI/UX match 

9. Add Family member
- [ ] DOB validation <= today 
- [ ] DOB as date or integer 
- [ ] Mandatory vs Optional fields

10. Member profile
- [ ] UI/UX match 
- [ ] Add/View vitals
- [ ] BMI widget
- [ ] Switch  Household (HHH)

11. ANC List 
- [ ] UI/UX match 
- [ ] Add/View vitals
- [ ] BMI widget
- [ ] DOB Year, Month, Weeks 

12. Add ANC Client
- [ ] UI/UX match 
- [ ] Add/View vitals
- [ ] BMI widget - for each BMI measured add an encounter and save the BMI on an observation record 
- [ ] Mandatory vs Optional fields

13. ANC Client profile 
- [ ] UI/UX match 

14. Measure 
- [ ] CQL 
- [ ] Measure report 
- [ ] Add Filter report page 
- [ ] Report template UI/UX

15. UI/UX
- [ ] Horizontal layout 
- [ ] Family ID visibility 
- [ ] Village ID
- [ ] Upcoming services
- [ ] Past Encounter 
- [ ] Notifications
- [ ] Color codes

16. Open Questions
- [ ] Failed password attempts  ?
- [ ] Reset password  functionality ?
- [ ] Enter password as PIN ?
- [ ] Fetch practitioner details ?
- [ ] Location mapping / hierarchy ?

**Bug Fixes** 

- [x] #695 
- [x] #696 
- [x] #725
- [x] #697
