### ISSUE TITLE
[Roadmap] FHIRCore Milestone 15

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#694]
**Start**
- [x] Review/Close open Items in [Sprint 14](https://github.com/opensrp/fhircore/milestone/26)
- [x] Start Items in [Sprint 15](https://github.com/opensrp/fhircore/milestone/27)

**Expectations** 
- [x] Quest/G6PD v0.2 - RIM
- [x] Quest MSF - View QuestionnaireReponse and saving Observations
