### ISSUE TITLE
Optimize Quest Synchronization

### ISSUE THREAD

**Issue by trevorgowing** [opensrp/fhircore#702]
### Context

As per discussion https://github.com/opensrp/fhircore/discussions/676 initiated based on issue https://github.com/opensrp/fhircore/issues/642 the Quest App synchronization needs to be reordered.

### Blocker

There is a related discussion https://github.com/opensrp/fhircore/discussions/594 which is partially blocking this issue. The decision that needs to be made is how to filter resources. The implementation of the app configuration does not block this issue since the chosen filters can be represented in the current app configuration solution.

### Summary

The issues we are trying to resolve are minimizing unnecessary synchronization by moving synchronization to when it is applicable as well as minimizing the number of resources that are synchronized.

The ultimate goal is to improve the user experience by improving app performance and minimizing synchronization time.

### Tasks

- [ ] Synchronize Application Configuration. If authentication is required for these requests, it only makes sense to do this post user log in.
- [ ] Combine configuration resource filters with user specific resource filters from keycloak.
- [ ] Trigger periodic sync post log in rather than on app startup and apply above resource filters.

**Comment by trevorgowing** [comment]
Duplicate of https://github.com/opensrp/fhircore/issues/668
