### ISSUE TITLE
[Roadmap] FHIR Core Milestone 16

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#743]
**Start**
- [x] Review/Close open Items in [Sprint 15](https://github.com/opensrp/fhircore/milestone/27)
- [x] Start Items in [Sprint 16](https://github.com/opensrp/fhircore/milestone/28)

**Expectations** 
- [x] Quest/G6PD v0.2 - RIM
