### ISSUE TITLE
Quest v0.2 / G6PD : Questionnaire checklist for both Patient (client) Registration and G6PD Test/survey

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#806]
Sure the questionnaire need updates 
**Registration Questionnaire** 

- [x] 1. Family name
- [x] 2. Given name
- [x] 3. Gender (Male/Female)
- [x] 4. Date of birth/ Age - Date (dd-mm-yyyy) or integer 
- [x] 5. Phone number
- [x] 6. City
- [x] 7. Country
- [x] 8. Marital status
- [x] 9. Occupation
- [x] 10. Is Active?

**G6PD Test Questionnaire** 

- [ ] 1. Mode   - Control , Normal ***
- [x] 2. Type  : Number, Error , N/A 
- [ ] 3. Device Serial number ***
- [x] 4. G6PD Level
- [x] 5. Hemoglobin Level 
- [x] 6. Image capture 

*** Needs scoping and requirements defined by the client can be skipped in the short term

**Comment by f-odhiambo** [comment]
@maimoonak Kindly check this ticket #599  out as you implement this ticket
