### ISSUE TITLE
mADX  - Implement $evaluate_measure API  on SDK for measure reporting on FHIR Core reference app 

### ISSUE THREAD

**Issue by f-odhiambo** [opensrp/fhircore#882]
**Name of feature to enhance**
 Implement $evaluate_measure API  on SDK for measure reporting on FHIR Core reference app : Notice D - mADX project 
 
**Description of feature**
1. Sync and Load measures in reference app 
2. Select an ANC patient 
3. Implement calling the  $evaluate_measure API in FHIR Core and generating a MeasureReport *
4. View MeasureReport

**Prerequisite Task** 
- [x] Review #700
- [x] Review https://github.com/google/android-fhir/issues/657
- [x] Review https://github.com/google/android-fhir/pull/810

**Subtasks**
- [x] Review designs for measure reporting  - mADX - https://www.figma.com/file/bH9zok2Yvu6xQ7vGxY8jiC/FHIR-ANC?node-id=1907%3A59174
- [x] Design Implementation for reporting #700
- [x] Review Measures  - https://github.com/WorldHealthOrganization/smart-anc/tree/master/input/resources/measure
- [x] Implement $evaluate_measure API  from SDK for measure reporting on FHIR Core reference app*
- [ ] https://github.com/opensrp/fhircore/issues/992
- [ ] Add reference resources for the remaining 12 Indicators. Finally, load and test measure against patients **

**Acceptance  Criteria** 
- [ ] 1. Ability to search and filter ANC Clients for Individual reporting 
- [ ] 2. Append Practitioner ID forMeasureReporting with Practitioner related data only 
- [ ] 3. Load data and test for MeasureReporting for Subject 
- [ ] 4. Load data and test for MeasureReporting for Population 

**NB.** 
*To be implemented once the SDK PR https://github.com/google/android-fhir/pull/810 is merged 
**This may need patients to be loaded with relevant reference CareTeam, Encounters, Conditions & Observations. To be verified later as POC on SDK currently supports the 1st Indicator

**Comment by mwkhan1983** [comment]
blocked by this SDK PR google/android-fhir#810

**Comment by f-odhiambo** [comment]
> blocked by this SDK PR [google/android-fhir#810](https://github.com/google/android-fhir/pull/810)

PR is merged and now unblocked

**Comment by f-odhiambo** [comment]
@ellykits Kindly tag current PR for this implementation

**Comment by f-odhiambo** [comment]
**Update Feb 1st 2022**
1. Raised a PR https://github.com/google/android-fhir/pull/1092 for Population measure reporting 
2. Test Data missing 
3. Need to test and confirm if Measure Reports Generated are valid
